# Religion

## The Tibetan Book of Living and Dying [西藏生死书，Sogal Rinpoche]

<span color = "blue">Hui: 这本书让你严肃系统的思考死亡，从藏传佛教的角度讲述生死。这本书意在写给西方人看的，结合了中西方思想，时而引入基督教的例子，相对其它佛教书籍更加通俗易懂。书的核心观点是我们从出生的那一刻开始就在准备死亡，好好活着是为了最终能够好好死去。书中指出一切都是无常，看穿我执的虚妄，理解无常，回归本性。虽然对许多地方有疑问，但还是非常推荐这本书。看过之后或许能向不畏死，亦能好好活跨进一步。</span>

### Living [生]

<pre>
Karma: 业力
Phowa: 颇瓦法
Samsara: 轮回世界
Rigpa: 本觉
Nangpa: 佛教徒，内省的人
Luminosity: 觉明
Wisdom-energy: 智慧能
Heart-center: 心轮
Wisdom-channels: 智慧脉
Karmie winda: 业风
Prana: 呼吸
</pre>

#### In the Mirror of Death [在死亡的镜子中]

- The disastrous effects of the denial of death go far beyond the individual: They affect the whole planet. Believing fundamentally that this life is the only one, modern people have developed no long-term vision. So there is nothing to restrain them from plundering the planet for their own immediate ends and from living in a selfish way that could prove fatal for the future. （否定死亡的可怕影响力，绝不止于个人层面，它影响着整个地球。由于大多数人相信人生就只有这么一世，现代人已经丧失长远的眼光。因此，他们肆无忌惮地为着自己眼前的利益而掠夺地球。）

#### Impermanence [无常]

- To practice death is to practice freedom. A man who has learned how to die has unlearned how to be a slave. [Montaigne]

- Death is a vast mystery, but there are two things we can say about it: (1) It is absolutely certain that we will die; (2) It is uncertain when or how we will die.

- Why do we live in such terror of death? Because our instinctive desire is to live and to go on living, and death is a savage end to everything we hold familiar.

- Perhaps the deepest reason why we are afraid of death is because we do not know who we are.
Without our familiar props, we are faced with just ourselves, a person we do not know, an unnerving stranger with whom we have been living all the time but we never really want to meet.
Hui: 我们被各种各样的刺激、快感催眠(hypnotize)，生活渐渐沦为手段淹没目的的过程。不知道自己是谁，不知道为什么活着。

- Just look at your mind for a few minutes. You will see that it is like a flea, constantly hopping to and fro.

- The birth of a man is the birth of his sorrow. The longer he lives, the more stupid he becomes, because his anxiety to avoid unavoidable death becomes more and more acute. What bitterness! He lives for what is always out of reach! His thirst for survival in the future makes him incapable of living in the present. (人之生也，与忧俱生。寿者昏昏，久忧不死。何苦也！其为形也，亦远矣！《庄子至乐篇》)

- Our lives are monotonous, petty, and repetitive, wasted in the pursuit of the trivial, because we seem to know of nothing better…..The pace of our lives is so hectic that the last thing we have time to think of is death.

- As a Tibetan saying goes:“Tomorrow or the next life, which comes first, we never know.”
Discipline is to do what is appropriate or just; that is, in an excessively complicated age, to simplify our lives……the only serious goals in life are “learning to love other people and acquiring knowledge(学习爱别人和获得知识)”……Whatever we have done with our lives makes us what we are when we die.(我们一生的所作所为，造就了我们去世时的模样。) And everything, absolutely everything counts.

- In our minds changes always equal loss and suffering. And if they come, we try to anesthetize ourselves as far as possible. We assume that permanence provides security and impermanence does not. (我们害怕变化)

- The past is past, the future not yet risen, and even the present thought, as we experience it, becomes the past. The only thing we really have is now……Has my understanding of death and impermanence become so keen and so urgent that I am devoting every second to the pursuit of enlightenment?

#### Reflection and Changes [反省与改变]

- There is one way, and one way only, out of samsara’s ceaseless round of birth and death, which is the path to liberation.

- Those with dualistic perception（分别心） regard suffering as happiness, like they who lick the honey from a razor edge.

- We may idealize freedom, but when it comes to our habits, we are completely enslaved.
Learning to live is learning to let go.

- There is nothing wrong with the desire to be happy, but what we grasp on to is by nature ungraspable. The Tibetans say you cannot wash the same dirty hand twice in the same running river, and, “No matter how much you squeeze a handful of sand, you will never get oil out of it.”
How can we work to overcome attachment? Only by realizing its impermanent nature; this realization slowly releases us from its grip.

<span color = "blue"> Hui: understand and accept uncertainty. being mortal</span>

- Nothing has any inherent existence of its own when you really look at it, and this absence of independent existence is what we call “emptiness”.

<span color = "blue"> Hui: It reminds me the beginning of Ecclesiastes.

[Ecclesiastes 1:2-10] “Everything is meaningless”, says the Teacher, “completely meaningless!” What do people get for all their hard work under the sun? Generations come and generations go, but the earth never changes. The sun rises and the sun sets, then hurries around to rise again. The wind blows south, and then turns north. Around and around it goes, blowing in circles. Rivers run into the sea, but the sea is never full. Then the water returns again to the rivers and flows out again to the sea. No matter how much we see, we are never satisfied. No matter how much we hear, we are not content. History merely repeats itself. It has all been done before. Nothing under the sun is truly new. Sometimes people say, “Here is something new!” But actually it is old; nothing is ever truly new.</span>

- Always recognize the dreamlike qualities of life and reduce attachment and aversion. (认知生命有如梦幻，减少执著和嗔怨)

<span color = "blue">Hui: 无所不有是全，一无所有是空。全是面子，空是里子。什么都是也就无所谓是什么，等于什么都不是，意识到这一点，就可以放下了。</span>

#### The Nature of Mind [心性]

“the homage of the View” It is a devotion that springs spontaneously from seeing the View of the nature of mind.(“知见皈依”这是从看到心性的知见而当下产生的恭敬心。)
Life and death are in the mind, and nowhere else.

<span color = "blue"> Hui: It resonates what Bible says. Jesus came to show us the way, teach us the truth and invite us to find life. As Jesus said to the Samaritan woman:“Anyone who drinks this water will soon become thirsty again. But those who drink the water I give will never be thirsty again. It becomes a fresh, bubbling spring within them, giving them eternal life.” Indeed, life and death depend on your mind, your faith. </span>

- There are many aspects to the mind, but two stand out.
Ordinary mind, called by the Tibetans sem. One master defines it:“That which possesses discriminating awareness, that which possesses a sense of duality–which grasps or rejects something external–that is mind. Fundamentally it is that which can associate with an ‘other’–with any ‘something’, that is perceived as different from the perceiver.”(凡夫心，分别，相对心)

- Then there is the very nature of mind, its innermost essence, which is absolutely and always untouched by change or death. At present it is hidden within our own mind, our sem, enveloped and obscured by the mental scurry of our thoughts and emotions.(本性，心的底蕴，不受凡夫心影响。)

- The nature of mind is the very root itself of understanding. In Tibetan we call it Rigpa, a primordial, pure, pristine awareness that is at once intelligent, cognizant, radiant, and always awake. It could be said to be the knowledge of knowledge itself. (心性是了解的基础。)

- When a much larger number of people know the nature of their minds, they’ll know also the glorious nature of the world they are in, and struggle urgently and bravely to preserve it. It’s interesting that the word for “Buddhist” in Tibetan is nangpa. It means “insider-er”: someone who seeks the truth not outside, but within the nature of mind.

- The central truth of Buddha’s teaching: that we are all already essentially perfect.

<span color = "blue">Hui: I don’t agree that we are already essentially perfect.</span>

#### Bringing the Mind Home [把心带回家]

- In fact, we are already perfectly trained by and for samsara, trained to get jealous, trained to grasp, trained to be anxious and sad and desperate and greedy, trained to react angrily to whatever provokes us. We are trained, in fact, to such an extent that these negative emotions rise spontaneously, without our even trying to generate them.
We will find that with time, patience, discipline and the right training, our mind will begin to unknot itself and know its essential bliss and clarity. [只有有耐心，纪律和正确的训练，我们的心将开始解开它自己的结，并认识它自己本有的喜悦和清明]

- Because from the mind are derived all fears and immeasurable sorrows.
We are fragmented into so many different aspects. We don’t know who we really are, or what aspects of ourselves we should identify with or believe in. So many contradictory voices, dictates, and feelings fight for control over our inner lives that we find ourselves scattered everywhere, in all directions, leaving nobody at home.Meditation is bringing the mind home.

- Three things make all the difference between your meditation being merely a way of bringing temporary relaxation, peace, and bliss or of becoming a powerful cause for your enlightenment and the enlightenment of others:
Good in the Beginning: springs from the awareness that we can all sentient Beings fundamentally have the buddha nature as our innermost essence, and that to realize it is to free of ignorance and to put an end, finally, to suffering. [believe in the equality of all beings]

- Good in the Middle: frame of mind with which we enter into the heart of the practice, one inspired by the realization of the nature of mind, from which arises an attitude of non-grasping, free of any conceptual reference whatsoever, and an awareness that all things are inherently “empty”, illusory, and dream-like.

- Good at the End: the way in which we bring our meditation to a close by dedicating all its merit and praying with real fervor.....Merit is the positive power and benefit, the peace and happiness that radiate from your practice.

- Three sacred principles make meditation truly enlightening and powerful:
    1. the skillful motivation [善巧的动机]
    1. the attitude of non-grasping that secures the practice [让修行成功的不执着的态度]
    1. the dedication that seals it [结束时的回向]

The practice of mindfulness, of bringing the scattered mind home, and so of bringing the different aspects of our being into focus, is called “Peacefully Remaining” or “Calm Abiding” which accomplishes three things:
all the fragmented aspects of ourselves, which have been at war, settle and dissolve and become friends. In that settling we begin to understand ourselves more, and sometimes even have glimpses of the radiance of our fundamental nature.[自己被撕裂成碎片的所有部分，过去一直都处在战争之中，现在则安住而定下来，而溶化，而变成朋友。在那种安定之中，我们开始了解自己，有时候甚至还可瞥见自性的光芒。]
the practice of mindfulness defuses our negativity, aggression, and turbulent emotions, which may have been gathering power over many lifetimes. [正念的修行可以舒缓我们多生多世以来所累积的负面心侵略性和混乱情绪。]
this practice unveils and reveals your essential Good Heart, because it dissolves and removes the unkindness or harm in you. [这种修行揭开并显露出你根本的善心，因为它消除了你心中的仇恨或伤害。]
To release means to release mind from its prison of grasping, since you recognize that all pain and fear and distress arise from the craving of the grasping mind.
meditation is nothing other than getting used to the practice of meditation.
The mantra “Om Ah Hung Benza Guru Pema Siddi Hung” is uniquely powerful for peace, healing, transformation and protection in this violent, chaotic age.
There is a famous saying:“If the mind is not contrived, it is spontaneously blissful, just as water, when not agitate, is by nature transparent and clear.”
Hui: But why is human heart so easily disturbed? we are BORN WITH SIN!

In meditation, as in all arts, there has to be a delicate balance between relaxation and alertness.
Ancient meditation instructions:
at the beginning thoughts will arrive one on top of another, uninterrupted
steep mountain waterfall
water in a deep narrow gorge
still and placid ocean ruffled by only the occasional ripple or wave
So have a spacious, open and compassionate attitude toward your thoughts and emotions, because in fact your thoughts are your family, the family of your mind……thoughts are like the wind; they come and go. The secret is not to “think” about thoughts, but to allow them to flow through the mind, while keeping your mind free of afterthoughts……there is gap between each thought……the Rigpa, the nature of mind in revealed in the gap. So the work of meditation is to allow thoughts to slow down, to make that gap become more and more apparent.
Traditionally it’s said that for a real practitioner, it’s not the negative experiences but the good ones that bring obstacles.
Then after meditation, it’s important not to give in to the tendency we have to solidify the way we perceive things. When you do reenter everyday life, let the wisdom, insight, compassion, humor, fluidity, spaciousness, and detachment that meditation brought you pervade your day-to-day experience. (在禅修之后，不要回到我们易于将事物固化的习气。当你重新进入日常生活时，要让禅修所带给你的智慧、洞察力、慈悲、幽默、柔软、旷达和自在充满你每天的生活经验。)
When I eat, I eat; When I sleep, I sleep. (这就是禅修)
Meditation is an art and you should bring to it an artist’s delight and fertility of invention…..Be alert for any sign of beauty or grace.
4.1.1.6 Evolution, Karma, and Rebirth [演化、业与轮回]

Shelley 雪莱
Balzac 巴尔扎克
Voltaire 伏尔泰

How much would it help us, I sometimes wonder, if we did remember them? Couldn’t that just confuse us even more?
Dalai Lama: " The basis on which Buddhists accept the concept of rebirth is principally the continuity of consciousness. "

## Gravity and Grace [重负与神恩, Simone Weil]

Hui: 这是我在2012年读的一本书，书很薄但很实，没有废话。Weil认为，不幸是绝对的。人的存在的不幸是无法消除的。她尖锐的地指出任何社会形态——哪怕是最近完美的社会形态都不能消除人的不幸，不幸不同于不义，所以革命不能代替人的救赎，而只能掩盖不幸，忽略看轻人的不幸，这也就是柏拉图所谓的猛兽式的社会性残忍。“爱是一种神圣的东西。若深入内心，就会将它撕裂。人心被创造出来就是供撕裂的。当它被其它东西撕裂时，就是最可悲的浪费。但它宁可被其它东西撕裂而不是被神圣的爱。因为神圣的爱只撕裂自愿被撕裂的心。这种自愿是困难的。”从一个基督徒的角度，我对这句话的理解是我们只有摒弃过去的自己（也就是所谓的撕裂），将自己交给神，相信神，才能得到永恒的神恩。神恩的翻译是Grace，我及其喜欢这个关于Grace的定义： “Grace is God’s kindness, his love, his care, his work on our behalf, his blessings, his gifts, his goodness, his forgiveness, and his salvation. But it is more than that–it is all these things when they are undeserved, when they are pure gift”. 只有来自神恩的爱才能够改变我们，改变接受神恩的人，也改变了这些接受神恩后向其他人传递神恩的人。为什么放弃原来那个自己那么困难？因为骄傲，我们放不下内心的骄傲，便无法接受神的恩典。这种放下和自愿被撕裂当然是困难的，否则神恩来的太便宜了。
此外，作者认为包含真理的思想存在于不同的宗教经典，文学与科学著作中，真理遵循不同的途径显示在人们的精神中。比如希腊几何学和诗歌，中国的道教，埃及的俄赛里斯教，印度佛经等，都融合了圣经所包含的真理。

两种力量主宰着宇宙：光(light)和重力(gravity)。重负，一般地说，人们期待他人的事是我们身上的重负效果决定的；人们从他人那里得到的由他人身上重负效果所决定。为何一旦有人表示有一点，或非常需要别人时，别人会选择远离？重负所致。 灵魂的一切自然的运动受物质万有引力一类的规律制约。唯有神恩例外。
Hui: 神的爱是无条件的。

在这种情况下，我至少由有好几次忍不住说出伤人之语。向重负屈服了。这是大逆不道。话语的功能就是如此被滥用，话语是用来表达事物关系的。
伤害他人，就是要从中得到什么。得到什么呢？当伤害他人时，赢得了什么？人们扩展了自己。发展了自己。在他人身上建立虚无以填平自身的虚无。
若想到上帝不存在而爱上帝，他将会显示他的存在。
Hui: 我们对上帝的爱也需要是无条件的。

一切虚空，（不被接受）产生仇恨、刻薄、苦涩、积怨。人们盼望自己所恨的遭到恶报，以及人们想象的饿恶重建起了平衡。
创造是一种矮的行为，它是永久的。我们存在的每时每刻都是上帝对我们的爱。但上帝只能爱自己。他对我们的爱是通过我们去爱他自己。因此，是他赋予我们存在，他爱我们而甘愿不存在。……我们的存在只是由于他的期待，由于我们不同意不存在造成的他永久地向我们乞求他赋予我们的这个存在。他把存在给予我们是为了向我们乞求它。……正是上帝出自爱而离开我们，以便我们能爱他。因为倘若我们直接沐浴在他的爱的辉映下而没有空间、时间和物质的掩护，我们就会像阳光中的水一样蒸发掉；我们就不会有足够的我可以为了爱而放弃那个“我”。
只要我们尚未明白我们有底，我们便是无底的桶。……我们只拥有自己弃绝的东西。人们失去了自己不愿意弃绝的东西。在此意义上，不经由上帝，人们便不能拥有任何东西。
上帝并不仅只有一次使自己成为血肉，他每天都使自己成为物以共给人，供人食用。反之亦然，人由于劳累，不幸和死亡而成为物，并被上帝食用。怎么能拒绝这种相互性？
因为不幸的伤口和不幸所引起的屈辱使人认识人间疾苦，这种认识乃是一切智慧之门。
人的生命中只有两个完美的赤裸和纯洁的时刻：出生和死亡。
在没有我们的情况下创造了我们的人并不会在没有我们的情况下拯救我们——Saint Augustine
幕，就是人的苦难：甚至对于基督也有帷幕。……扎根于漂泊不定之中。
我身上具有的精力，天赋等等，又有何用？我受够了，可以消失了。……当我在某处时，我的呼吸，我的心跳，会玷污天上和地下的宁静。
必然的两面：行使必然和承受必然。阳光(sunshine)和十字架(cross)。……服从必然而非服从束缚。……行为是天平的指针。不应触碰指针，而是触碰砝码。……惟有完全的超脱才能使人透过骗人的价值的迷雾看到赤裸的事物。
Hui: 如何完全超脱呢？

我们接受在我们面前显现的虚假的价值，当我们认为在行动时，实际上我们静止未动，因为我们依然处在同样的价值体系中。……有关尘世事物的错觉并不涉及其存在，而是其价值。
我们身上源于撒旦的东西便是想象。
Hui: I don’t understand it.

期限，对于文明来说是以世纪计数，对于个人来说是以年，数十年计数，它具有一种不适者消亡的达尔文式的功能。
在屈辱中，傲慢使内在的谎言越来越大。……所有无价值的东西都逃避光照。在尘世，人可以借肉体隐藏自身。死后就办不到了。人就赤裸裸地把自己交付给光照。
Hui: 和西藏生死书里的观点类似。

人们不可能面对面见到上帝而不死，但人们并不愿死。……肉体并非是使我们远离上帝的东西，它是我们遮在面前的帷幕以在我们和上帝之间制造屏障。
Hui: 人一边说爱着上帝，要追随上帝，一边却又紧紧抓住尘世的光阴。我至今也不明白为什么。或许在活着的时候就是为了要努力的修行，使我们能够在死时见到上帝而不逃离，抓住那光明，并且于光明同在。所以我们在准备，一直在准备，我们抓住尘世，是因为觉得自己还没有准备好。

渴望躲避孤独是一种胆怯行为。……模仿上帝是一种不良企图。
恶，当人们身处恶中时它并不被感知为恶，而是被感知为必然性或者责任。
只有在无望使距离的意识变得无法容忍并且将痛苦转变为仇恨时，相应的犯罪才会产生。
人们无法注视人可能做的恶和可能承受的恶的规模而不感到恐惧。……只有处在他人无法再伤害我们的境地时，我们才可能厌恶对他人造成伤害（于是爱他人就像爱过去的自己一样是有限的）
Hui: 非常喜欢这两句

若这世上没有不幸，我们会以为自己在天堂。有一种不幸是：人们无力承受它延续下去，也无力从中摆脱出来。……有两种想法会减轻一点不幸。一是不幸即可就会停止，另一种不幸永不止息。
苦难，教育和转化。被授予宗教奥义者不应是学到些什么，而是在他们自身实现某种转化，这种转化使他们能接受教育。
必须通过快乐，拥有了真实的揭示才能在痛苦中获得真实。否则，生活只是一场或深或浅的噩梦。……必须在虚无和虚空的困难中努力找到更为充实的现实。同样，应当热爱生活以更加热爱死亡。
战争和情欲是人中间的两大幻想和谎言之源。两者的混合是最大的不纯。
基督治愈残疾者，使死者复活等等，这些是他使命中不足道的、人间的、几乎卑下的部分。基督的使命的超自然部分，则是血泪，是抚慰人的愿望并未实现，是祈求得到宽容，是被上帝抛弃的感情。……“My God, my God, why have you abandoned me? 我的上帝，我的上帝，你为何离弃我？”这就是基督成为某种神圣东西的明证。
穿过时间和空间的无限厚度，上帝为找到灵魂并诱惑它而精疲力竭。如果灵魂表示了纯净而全面的赞同，即使是闪电般的一瞬间，上帝便政府了灵魂。当灵魂变成完全归于他的东西时，上帝便抛弃它。他让灵魂孤身独处。轮到灵魂穿过时间和空间的无限厚度，摸索寻找灵魂所爱者。就这样，灵魂从相反方面重做上帝朝它而来的旅行。这就是十字架。
基督的仁慈宽厚，就是上帝与造物之间的距离。……中介的功能，在其自身，意味着左右为难。
上帝把自己奉献给人，作为强大无比者或者作为完美无缺者——由人自己选择。
基督十字架的秘密在于某种矛盾中，因为这即是一种自愿的奉献，又是一种他身不由己受到的惩罚。
Hui: “自愿”源自于上帝的仁慈和爱；“身不由己”则因为人性中的罪。

她否认上帝在自然中留下的不确定性和“无根据”的余地，而这种余地使自由和奇迹得以进入尘世。同样，在事实上，重负确实是强大无比的：圣.托马斯承认，大部分人的行为是受命于感官的盲目的欲望，并屈从于星辰的决定性的.[原编者注]

惟一不受偶然性支配的善是尘世之外的善。要知道_最珍贵的东西并不扎根于生存中_。这是美的。为什么？它把灵魂抛到时间之外。想生一个白如雪，红似血的孩子的女人，得到了这样的孩子，但她死了，孩子托付给了继母。

凡是存在的东西绝对不值得爱。因此，应爱不存在之物。

Hui:不太理解这点，那么神存不存在呢？抑或这里讲的的世俗意义的存在，而非精神。

信念（这里所说的是对自然的一种超自然的阐释）是一种建立在超自然经验基础上的通过类比做出的臆测。……神秘主义是人类品性的惟一源泉。因为，不相信在尘世的幕后有无限的慈悲，或是相信这种慈悲在幕前，两者都使人变得残忍。
Hui:也就是说，以作者看信念是一种主观想象，而非客观存在。

只有当我们在内心深处需要某种表示什么意义的声音，当我们呼叫以求得回音而我们却得不到回音时，只有这时，我们才触及上帝的沉默。
在两个不曾体验过上帝的人中间，否认上帝的人也许离上帝最近。
Hui:怀疑否认比不假思索的盲信要好。

专注，从其最高程度上来说同祈祷是一回事。它意味着信念和爱。专注丝毫不分心就是祈祷。高度的专注就是构成人的创造才能的东西，而惟有宗教的专注才是高度的专注。……若人们不把注意力从上帝的启示上挪开，若人们不拒绝这种启示，那么上帝的启示必定会不可抗拒的发生。对于上帝的启示，并无选择可做，只需要不拒绝承认它的存在。怀着爱把专注专向上帝（或转向更低层次，一切真正美的东西），这使一些事难以实现。这就是灵魂中祈祷的不起作用的行文。我不必担心不拼命努力。条件仅仅是不自欺并要专心。
极端的纯洁性可注视纯洁，也可注视非纯洁；非纯洁性两者均不能；前者使它害怕，后者将它吸收。
Hui:纯洁具有包容吸收的能力。海纳百川，有容乃大。能被玷污的，是因为原本就不够干净；能被伤害的，是因为原本就不够强大。

要触及不可能，必须完成可能。应在规定的时间完成职责，以确信外部世界的实在。应确信时间的实在，不然，就在幻想。
假如在此之后和余生之中自己会成白痴，真理却继续存在。
若人人都始终按照自己所读的正义来行事，公正与不公正之间的差别又是什么？
美：是一种人们看着它而不向它伸手的水果。
Hui: 占有有可能既是破坏。

我们一定是犯下了使我们被诅咒的罪过，因为我们已失去了宇宙的一切诗歌。
Hui: 这句话看了好难过啊。

艺术只有在大混乱中才能产生……因为不幸会使许多事情变得简单。
现代生活全由过度摆布，过度侵入一切：行为和思维，公众和私人生活。由此造成艺术的堕落。任何地方都没有平衡。时光在流逝中，销蚀，摧毁了世俗的东西。因此，在过去中有比现在更多的永恒。
在人所爱和所恨之间是否有同一性？人所恨的东西，当它出现另一种形式时，人们会有必要去爱它吗？反之呢？革命的经久不灭的幻想在于认为由于权利的受害者是无辜遭受着暴力。倘若把权力放在他们手中，他们就会公正地使用它。然而除了接近神圣的人，受害者如同刽子手一样被权利玷污。剑柄上的恶传送到了尖端。如此般登上巅峰的受害者由于变化而陶醉，他们会同样作恶或是更多地作恶，然后又马上跌倒在地。
劳动使人疲乏不堪地感受到了像球一样踢回来的合目的性现象。

## Christianity and World Religions

Hui: 这是我们教会的读书会大家一起阅读讨论的书，可能没有中文版的。我们之前读的3本都是Adam Hamilton的书。他是美国一个非常出名的牧师。写了一系列适用于小组讨论的书。书都不厚，每本都针对一个特定和主题，还配有音频。这里只推荐其中的这一本。如果有感兴趣的可以给我说。
这本书介绍了基督教和世界其它主要的宗教：印度教，伊斯兰教，佛教和犹太教。我们小组非常喜欢这本书的讨论。了解不同宗教的背景让我们更加宽容的对待世界上不同的人，不同的思想。
痛苦让人成熟，与其说宗教（或者说信仰，即使用宗教，这里也是广义上的）指引人走向快乐，不如说宗教帮助你的心灵强大到能够应付生活中的痛苦和困惑。
心智成熟的人知道如何去爱，知道要保持爱需要付出，他们能感受到更多的快乐，更少的痛苦。强大的心灵得到的快乐，是心理学家亚伯拉罕迈斯劳所说的“高原体验”，这与“高峰体验”不一样，前者的高度不会一下显露也不会一下消失，你可以长久停留在那里，不会轻易摔下来。

## The Case for Faith 

Is that what faith is all about —— fooling yourself into becoming a better person? Convincing yourself there’s a God so that you’ll become motivated to ratchet up your morality a notch or two? Embracing a fairy tale so you’ll sleep better at night?
Evidence to support the author’s statement: the resurrection of Jesus could not have been a legend:

The apostle Paul preserved a creed of the early church that was based on eyewitness accounts of Jesus’ return from the dead—— and which various scholars have dated to as early as 2-3 years after Jesus’ death. That is far too quick for mythology to have tainted the record.
Hui: How do you know it is too quick? Is there any reference to compare with?

Even David Hume, one of history’s most famous skeptics, said it’s just barely possible that God exists. That’s at least a somewhat reasonable position —— to say that there is at least a small possibility…How can a mere finite human be sure that infinite wisdom would not tolerate certain short-range evils in order for more long-range goods that we couldn’t foresee?

Faith is active; it demands a response. Unlike reason, which bows down faithfully to the evidence, faith is prejudiced.

If there is no God, where did we get the standard of goodness by which we judge evil as evil?

Hui: it is a very popular argument but I don’t understand why. How come the presumption that the existence of good/evil standard indicating a God? 1) the standard is not well objectively defined. It is actually very subjective and varies by time and location. 2) how can we be sure there is no other reason that we just can’t comprehend due to our intellectual limitation? 3) even there is well defined standard and it is from God, how can we know it is A God not many Gods? 4) Even it does indicate a God, how can we know it is the God described in Christianity?

If death has no meaning, how can life ultimately have meaning?
Hui: This is the point turned me on.

## If you want to walk on water, you've got to get out of the boat

- Comparison will lead to pride and a false sense of superiority if I'm ahead and misery if I'm behind. Or worse, I will discount and bury the irreplaceable treasure that the Lord of the Gift has given to me alone. 

- Your life---what you do with what I gave you---is a matter of supreme importance... unrealized potential is a sin --- a very serious sin --- the tragedy of the unopened gift. Comfort will often keep us from growth. Imagine watching all that God might have done with your life if you had let him...heaven will be that place where we finally experience the fullness of adventure, creativity, and fruitfulness we were made for. 