\mainmatter

# Parenting
## Expecting Better

Miscarriage risk:

- By week of 11, miscarriage rate drops to less than 2%.

Nausea:

- Some nausea is normal and is probably a good sign about pregnancy.
- Vomiting every day for weeks is more than the average person experiences.
- Treatment (in order): (1) small meals, (2) vitamin B6 + ginger ale, (3) Vitamin B6 + Unisom (or Diclegis, with a prescription), (4) Zofran

Food and drinks:

- Mercury is bad for your baby. Omega-3 fatty acids are good for your baby. Fish contain both. Your best option is to try to pick fish with a lot of omega-3s and not a lot of mercury.
- People who eat a lot of fish have smarter kids on average, even with the greater mercury exposure.
- Coffee is fine in moderation: all evidence supports having up to 2 cups. Much of the evidence supports having 3-4 cups. Evidence on more than 4 cups a day is mixed; some links are seen with miscarriage, but it is possible that they are all due to the effects of nausea.

Exercise:

- Exercise is encouraged during pregnancy and there is no evidence that bed rest will prevent preterm labor.

Labor:

- Normally, your cervix is closed. During labor, it opens to 10 cm. It also softens and shortens and thins.
