# Self-development

## Learn how to learn

### How to read a book? 

- 我们为了理解一件事，并不需要知道和这件事相关的所有事情。太多的资讯就如同太少的资讯一样，都是一种对理解力的阻碍。......（当今铺天盖地的资讯使人们）直接将包装过后的观点装进自己的脑海中，就像录影机愿意接受录影带一样自然。
- 我们需要主动阅读：为获得资讯而读，为求得理解而读。如果你对书的内容了解，那阅读就是获取资讯，理解力不一定增强。如果你并不了解这本书，此书包含了某些能增进你理解的东西。
- 阅读的艺术包括了所有非辅助型自我发现学习的技巧，敏锐的观察，灵敏可靠的记忆，想象空间，训练有素的分析、审思能力，阅读也就是一种发现。

### Make friend with time 

新知，纠错，重视这三种方式就是我们打磨概念最主要的工具。

- 新知，就是学习一个新概念。当我们脑子里没有一个概念的时候，就倾向于不去想这个事情。
- 纠错，就是改掉对一个概念的错误理解
- 重视，把一个平时耳熟能详，已经平常到被你忽略的概念上升到一个新高度。

三个容易被我们忽视或误解的概念：

（1）第一个概念：时间管理

时间管理这个概念本身就是个伪命题。时间是不可能被管理的，我们唯一能管理的就只能是自己。

如何才能运用好积累的力量？

首先要认清一个事实，速成没有可能。人们好像都特别急于看到结果，一方面的原因是我们天性追求即时满足，另一个原因是，现在的互联网世界把人们的生活都透明化了，没有比较就没有伤害。

怎么跳出这个怪圈呢？

认清自己的现状，接受自己的现状，一点一点的磨练自己，积累技能。

用“换”可以“实现”速成。每当想到“我想要什么”的时候，马上提醒自己，我到底有什么，我愿意花多少成本来换，你的成本包括金钱，时间，精力，体力，人脉，名气，如果能直接兑换当然最好，如果不能直接兑换，那就靠积累的力量一点一点的赞资源。

把时间当做朋友的心法就是接受现实，然后靠积累不断的让自己成长。

（2）第二个概念：自我证明

如果一个人本身就很优秀，是不用去证明的，别人自然能看到。

为什么总是得不到别人的认可的2个原因:

首先很可能的一个原因是自认为很优秀。

> 案例1：“自利性偏差”现象。一个人对别人的认识比对自己的认识通常准确的多。心理学家早就发现这么一个普遍现象，当一个团队成功的时候，多数人都觉的是自己的功劳，但是当一个团队面临失败的时候，每个人都觉的是别人的错，都习惯性的把错误归咎于别人。

> 案例2：大多数的司机都觉的自己的驾驶水平高于别人，哪怕一个新手也会觉的自己可以驾驭各种路况。

其次，一个人一方面强，肯定其他方面就弱。

（3）第三个概念：灵感

灵感就是时间积累到一定程度的必然产物。

> 案例1：“鸡尾酒会效应”，假设你参加一场鸡尾酒会，大家都手里拿着酒和自己对面的人聊天，这时候你会自动屏蔽周围人的声音，只关注自己的声音和你的聊天对象，但是如果周围人聊天的时候提到了你的名字，你只要听到了，你的注意力一定会被拉过去。一个孕妇怀孕了，她会突然发现满大街都是孕妇，一个人买了一辆白色的车，他会突然发现满大街都是白色的车。

> 案例2: 台湾作家李敖说自己从来不看书的，只拆书，拿上一本书之后看到有用的资料就剪下来，全都放在细分好的文件夹里，当他写小说的时候，根据标题去找材料。

总结：在这本书中李笑来给我们辨析了很多概念，从自我成长中遇到的问题开始说起，到如何管理自己的目标和行为，如何学习，如何思考和如何应用，一步一步的把我们脑海中常见的一些错误概念进行了纠错。

启示：成功本质上都是一样的，先花相当的时间和精力锁定一个方向或是目标，确定它实现的可行性之后，运用心智的力量，在这个方向上投入更多的时间，再投入比更多再多一点的时间，把时间当做朋友，一路前行，当时间的陪伴足够久的时候，不知里面过程的人可能会说那是运气，那是天命，而明白积累的过程是不可避免的人知道，所有的回报都是必然。

积累是解决成长问题的良药。不管你积累钱财，人脉，技能还是其他的什么东西，从接受现实开始，用沉着冷静的心态一点一点耐心的推进，不骄不躁，不紧不慢，不慌不急，用最稳的方式最快的成长，时间就是你的朋友。新的一年里，愿时间与你为伴，祝您好运。

人们总说他们真正感兴趣的是别的事情。可事实上，那应该仅仅是因为他们还没开始做那件事情，所以还没有在那件事情上遭遇挫折而已。

不是有兴趣才能做好，而是做好了才有兴趣。大多数事情需要熟能生巧。做的多了，自然擅长；擅长了，自然做得比人好；做得比人好，兴趣就大起来了，而后就更喜欢做，更擅长。

所有学习上的成功都只靠两件事：策略和坚持，而坚持本身就应该是最重要的策略。

没有什么比发现、培养、呵护、调整自己的心智力量更重要的事情了。

著名心理学家维克托.弗兰克：“即使在极端恶劣的环境里，人们也会拥有一种最后的自由，那就是选择自己态度的自由。”

我们自己的痛苦我们感同身受，而别人的痛苦我们很难做到感同身受。

<span color = "blue">Hui: 朴素的真理，但我们还是时不时觉得自己家的经特别难念......人类真是愚昧，健忘，又短视。</span>

Dan Goleman提出“Emotional Intelligence”， 他曾做过著名的“Delaying gratification” 实验
希望自己的欲望马上获得满足是大多数人的天性

野心永远是少数人的天性

“推迟满足”是心智成熟的人必备的能力，也是需要挣扎和锻炼才可以习得的能力 。

把每天的时间开销记录下来，一方面可以培养自己的成就感，另一方面可以避免轻易地原谅自己。
不要害怕修改，完成任何一个任务的过程中，修改都是不可或缺的。你在修改说明你在进步。很多人一生最终一事无成的原因，就是因为他们是脆弱的完美主义者，天真地希望自己可以在这个不完美的世界里完美地生存——所以注定以失败告终。

养成任何一个哪怕是很小的习惯，都需要挣扎。然而，貌似痛苦的挣扎过程，在将来的某个时刻终归会变得其乐无穷。

“浪费时间”这个说法是基于过程的，“成功失败”这个说法是基于结果的。对一个血肉之躯来说，最终的结果其实只有一个，就是死亡。失败从来都不是结果，因为绝大多数情况下，对大多数人来说，失败并不意味着死亡。人做事的时候，成也好、败也罢，通常还是要继续活下去。活下去，就意味着说还要不停地做很多事。

获得知识得途径：

- 体验
- 试错（Trial and error）
- 观察
- 阅读

面对无法亲身体验得知识，人们往往会心存恐惧，因为人们害怕未知。而群体面临无法体验得知识，往往会表现为疯狂。“很多时候人们的善良出自于软弱，而残暴不过来自于恐惧。”

日常生活中几乎所有主要的“沟通障碍”本质上都是因为沟通双方无法让对方理解与他们的经验相悖的知识或者信息造成的。

大脑中储存的信息要多到一定程度才有能力“融会贯通”。

自学能力：阅读，写作，检索。

很少有人仅凭天生的能力就可以拥有“神奇”的记忆力。“遗忘”是我们的自我保护功能。
嫉妒的产生源自于对自己与他人之间差异的扭曲理解。大多数人一生无法摆脱由比较而产生的情绪，不管是正面的，还是负面的。......

标记出并优先实施那些无需比较就可以获得欢乐和幸福的行动方案。时间会一如既往地分分钟钟、岁岁年年地流逝，但你会惊讶于你生活的变化。每一分钟，每一秒，每一天，每一年，时间的质量竟然会如此不同。

最为常见的逻辑错误是“以偏概全”。某个经验在某个人身上灵验了，并不意味着说这个经验在所有的人身上都会起作用。…“努力行动”并不是唯一导致成功的原因。…另外一个更加隐蔽的逻辑错误是“单向成立”。很多论断只不过是“单向成立”的。

接受自己和别人没有什么不同，至少没什么本质上的不同，是心智正常成长的重要前提之一。
电影精彩的原因：1）艺术加工；2）时间压缩。
浪费时间虚度年华的人有个共同特征——他们拼命想控制自己完全不能控制的，却在自己真正能掌控的地方彻底失败。

往往只有优秀的人才拥有有效的人脉。…注重自身的质量，知道不给他人制造麻烦，独善其身是美的。常言道：“事多故人离”。

证明自己给别人看恰恰是最浪费生命的一种行为。…所有傻逼都是自证的。

你比比人强一点根本没用，真正有用的是你不仅比别人强，还要强出很多才行。…可是你知道如果你最终竟然在某一方面比别人强出许多的时候，你会面临什么境遇么？你身边的人不再在这方面跟你比较了，他们会自动放弃，然后跟你比你不如他们的地方！…无论你怎么做，你还是很难获得对方承认的，因为你的想法和做法并不能影响他们的判断。所以，想办法“获取证明”实在是没有意义的事情。... 长久的观察和思考，有益于锻炼自己心平气和的能力。...

被别人左右，是一个人最可悲的状态之一。

忘记自己的优点，成熟的人总是知道如何让别人舒服。

1）人们普遍相信明天会拥有比今天更多的金钱；2) 人们普遍相信明天会有更多的时间。3) 人们对时间的曲解程度远远高于对金钱的曲解程度。

之所以可以“显得”游刃有余，是因为之前做过太多的准备。...

大多数的事情都需要提前准备，也都可以提前准备。

我们大脑中的灰质(gray matter)储存的各种信息只有很少一部分是有序储存的。...

随着信息输入越来越多，大脑就需要越来越多的灰质细胞(gray cells)。科学家们已经发现使用两种或者两种以上语言的人，有更多的灰质细胞(gray cells)。而颅腔的大小是有限的，于是gray cell的增加，最终会导致gray matter密度越来越高，于是gray cell之间就越有可能由神经元连接起来。于是就有可能产生我们所说的“融会贯通”的现象——那些原本可能貌似毫不相干的信息现在有机会被联系在一起了。 (Hui:这个科学上准确么？)

我们“对特定信息的注意力”会使得我们“神奇地”捕捉到那些于“我们所关注的信息”相关的某些信息。
反思能力，几乎是人类特有的。因为有这种能力才慢慢拥有了类比能力。而类比能力是一个人所拥有的理解能力高低之关键。…需要太长时间才可以获得的经验很难传递，就是因为缺乏现有的经验作为支撑。而想让一个孩子去真正理解“时间终究会越来越快”这样一个道理无比困难，就是因为他们不仅没有“类似的现有经验”，还恰好有相反的“现存经验”。几乎所有失败的青少年教育，都是因为粗暴简单而有愚昧地无视孩子们所拥有的“现存经验”和“现存经验的作用”而造成的。
Henri Poincare: 混沌理论告诉我们，初始条件的一个极小的差异将会导致最终结果的一个极大差异。

生活就是选择，而所谓的选择只不过是一个人所拥有的观念对之衡量后的结果。一个人所拥有的观念，说穿了，就是心智力的最终体现。
苏东坡《留侯论》：古之所谓豪杰之士，必有过人之节，人情有所不能忍者。匹夫见辱，拔剑而起，挺身而斗，此不足为勇也；天下有大志者，卒然临之而不惊，无故加之而不怒，此其所挟持者大，而其志者远也。

### 思维方法 {#siweifangfa}

- 信息海啸中独善其身之法
    - 沉浸能力：离开让你分心的事物，每天要有几个小时专注的时间
    - 放空能力：清理（焦虑，戾气，不需要的东西）＋输出（写出想法）
    - 精深能力：认真研究一些领域

当你在面对一个复杂问题时，应该努力做到： 想到一些方法来努力将该难题下某些边缘性的信息元素过滤掉，把某些次要 的东西组块化缩减，然后用图形来展现核心的复杂关系，同时用 分格化来确保过程的周密性。这样可以克服工作记忆（working memory）资源 有限的问题。

- 组块化：将多个信息单元压缩为一个信息单元（首字母略缩语） -在编程领域中，面向对象的思想是组块化思想的系统性实践，一个类显然就是一个组块，这种思想在编程领域是划时代的。
    - 下面讨论的组块化特指思考者自己构思出组块的过程，而不包括调用已有知识组块的过程。
        1. 同质信息合并
        2. 屏蔽部分信息
        3. 问题复杂性降低后将更多信息考虑进来（在一个更大的背景下） 
    - 一个成功的组块化，往往要把某些信息抽象到一个更高的层次。
    - Easy chunking: 基于对显而易见特征的归纳
    - Hard chunking: 基于对深层共性的抽象
    - 组块化阅读的两个关键特征（不仅是阅读，这是我们思考的一种“元模式”）：
        1. 只同时处理同一抽象层级的信息组块——这对工作记忆资源的占用是最小的。
        2. 从最抽象的层级开始处理，渐次降低抽象层级——这能保证全局观
处理多任务时，主流观点是按照重要性、紧迫性进行排序。换一种思路，根据不同任务的内在特征（涉及的知识和技能）进行组块化，然后将同一组块的任务进行集中处理。 
<span color = "blue"> Hui: 我赞同这种将任务组块化的方法。其实紧迫和重要并不是绝对的。你衡量重要性的标准取决于格局和眼界。你是只看当下，只为了完成任务而完成任务，还是将整个人生看作一个整体，思考自己生命的意义，然后以能最大化人生意义的标准去衡量事物的重要性。是活在别人的眼中，还是活在神的眼中，结果得出的重要的事情可能大相径庭。</span>

- 图形化：可认为是一种信息外部化（最常见的是思维导图）。简单的信息只需要浅层加工，庞大，复杂的信息应采用图解的方法来加工学习。练习图解式的信息加工甚至可以帮助我们从仅仅是一个学习者转变为一个创作者。图形化方法在思考中的四大功能：
    1. 信息外部缓存：将记忆外部化，把工作记忆中需要处理的部分信息外接到图纸上，这样就减轻了工作记忆的负担，提高思维效率。
    2. 构筑探索空间：“Game Storming”一书中作者强调，创造性思考是一个先发散再收敛的过程。而在发散和收敛之间，有一个关键的“探索阶段”。为了更好地进行探索，思考者需要一些基本的工具。思考者可以加入许多信息节点（卡片或者便签纸等）。节点的特点是“模块化的、可移动的物件，它们可以打乱重洗、排序和重新分组”。
    3. 支撑全局思考
    4. 抽象信息直观化

- 分格化（lattice）：这是一种穷举思想，避免人们因自己所能处理的信息有限而遗漏其他重要的信息和问题。 具体方法有checking list（清单降低了思考和行动的门槛，即便差别很大的东西，只要列入了同一个清单，就会具有形式上的统一感）、矩阵表和象限图等。分格化的作用是为思维过程引入了强制性，这种强制性包括强制拓展和强制分解两个部分。

> Edward de Bono [born 19 May 1933, a Maltese(馬耳他) physician, psychologist, author, inventor and consultant. He originated the term lateral thinking, wrote the book Six Thinking Hats and is a proponent of the teaching of thinking as a subject in schools.] 以铁球和凝胶(gel)来类比人类思维中的先入为主现象：一开始凝胶是平的，没有任何印记，然后一个铁球滚了过来，把凝胶压出一个凹陷后停在那里，然后第二个铁球滚过来时，其轨迹会受到之前铁球轨迹的影响，最终停在第一个铁球边上，之后的铁球也是如此…最后所有的铁球都会聚在一起，且大致不会偏离最初铁球所在的位置。

这种先入为主效应时人类思维的固有特点，很多时候它能够让人们更好地适应环境，因为人们可以仅基于少量和初步的信息就作出猜测和推演。在解决一个复杂或者创造性的问题时，它的弊端就凸显出来了。那么我们该怎么突破自己思维所设定的框框呢？ 

1. 抽象出尽可能完整的分解问题的维度 
2. 对每一维度，通过取反、细分等操作，找出尽可能多的表现值，以构成维度矩阵 
3. 在维度矩阵中，在不同维度的表现值之间尝试建立各种组合

人的思维不是凝聚的，稳定的，而是跳跃、流动和易变的。一个具有高度可塑性的大脑在良好思维工具的辅佐下，在持续不断的行动的打磨中，会变得强大的超乎想象。

### 拆掉思维里的墙 {#xiweifangfa2}

- 如何获得安全感?

(1) 小范围内冒险一下。这很好的试探了思维的墙，看其是不是表面坚固实际虚弱。比如用买一平方米房子的钱安排一次旅游，在一个永远不去的小群体里做做不好意思的事。

(2) 远离那些太容易获得的安全感。包括过于关心你的人，任意刷的信用卡，不犯错的任务，养老般的工作。

(3) 珍爱生命，远离恐惧。少和那些负能量的人在一起。（选择能够激励自己的环境）

(4) 做一个恐惧保险箱，把最恐惧的事情写在一张纸上，写10个，越详细越好，然后找一个安全的地方，或者信任的人保管，告诉自己，恐惧的事情随时可能会发生，但是我先要去做自己的事情，等做完之后再回来领取这个恐惧，这时候你就能放手去大干一场。回来的时候，你会发现，其实担心的事没多少会发生。

(5) 做成功日志。每天写5条个人成果，任何小事都行。你开始在每天的细节中，用成就感逐渐击退恐惧感。面对恐惧，触底反弹。恐惧其实有三个层次：1）恐惧本身，2）是害怕失去背后的价值，3）真正的恐惧，觉得自己没有能力去应对这个失去。明白恐惧的结构，就能更好的应对。

- 砌墙人

思维里的墙不单是自己内心的恐惧感和安全感形成的。我们身边还有一批砌墙的人。真正改变命运的，不是心态，而是心智，要懂得超越自己的心智模式，应对这个万变的世界。

### 怎样成为高段位的学习者？{#xuexi1}

(1) 提问

两种学习模式：

1. 直接传递模式：学习过程是简单的，线性的，传递－接受模式。学习的目标只是用静态的知识把头脑装满。
2. 建构主义模式：更合理的模式，知识不是简单的吸收而来，而是主动建构而来，学习者必须充分调用已有知识，在一个主动性的目标指引下，在一个丰富的情境中，去探索甚至撞击那些接触到的知识，在经过一系列复杂的交互之后，把这些知识纳入到原有的知识体系之中。《变构模型——学习研究的新路径》 一个好问题让我们成为“建构者”，因为我们不仅在学习知识，还在建构答案，在努力回答问题的过程中，我们筛选、评判和整合新知识和旧知识，并把它们融汇成一个自洽的整体。为了找到问题的解，我们可能会寻访任何可能的线索，查阅可能的资料，而不受既定的观点的束缚。（Linda Darling-Hammond: inquiry-based learning, ask deep explanatory questions）问题可以帮助我们形成长期的、一贯的思考路径。我们不仅仅是临时就一个问题寻找解答，而是持续地去思考和尝试解答这个问题，这个过程可以几个月、几年甚至贯穿我们的一生。问题就像一个富有韧性的细线，帮我们把各种知识、经验、观念和方法串在一起。有研究比较了在物理学和历史学领域专家和新手在知识组织上的差异，发现专家的知识不仅仅是对相关领域的事实和公式的罗列，而是围绕核心概念或大观点（big idea）组织的，这些概念和观点引导他们去思考自己的领域。一个高段位的学习者必定是一个优秀的提问者，从阅读、观察和思考的过程中产生问题。

(2) 解码(Decode)

对某一事实的了解应区分knowledge about 和 knowledge of两个层次。很多领域就像学画一样，需要一个漫长的临摹过程。除了基于样例的学习之外，解码之所以重要是因为我们常常需要面对各种各样全新的信息内容，如果不经解码这一过程，则不可能使其与我们原有的知识体系相整合。对信息材料的解码，其实就是内在知识重新建构的过程，因此也是一个创造性的过程。教育心理学家把在某一领域有专长的人分为：

1. Routing expertise：具有基本固定的知识系统，能高效地把接触到的信息材料按照已有的框架进行分析；因为这类专家接触的材料往往是一个固定的范围内的，如象牙塔内的学者，一生只看他所在学科的理论著作，那么他的知识体系就是固化的，他只能应对和解决在一个特定的理论范畴里的问题；
2. Adaptive expertise：可以不断进化、扩充核心能力，扩展专业知识的广度和深度来迎合需求和兴趣的增长。这类专家主动涉猎超出领域范围的、非常规的、情境化的问题，不排斥各种新鲜的经验刺激，所以他们的知识系统能够不断扩展。

解码是一个费时费力的过程，所以在有限的时间内，我们要尽量寻找最经典、最优秀的作品，进行深度解码。

(3) 操练

你掌握了多少知识，并不取决于你记忆了多少知识以及知识的关联，而取决于你能调用多少知识及其关联。认知心理学已有大量研究表明，记忆提取的操作其实起到了memory modifier的作用，一个曾经被调用过的知识和从未被调用过的知识相比，在今后更有可能被再次调用。法国教育学家Andre Giordan提出allosteric learning model，这个模型用了一个生物化学的隐喻——allosteric protein。这种蛋白质的特点是它的形态和功能并不是内在稳定的，而是由于外部环境的促发条件所决定。他认为构成学习者思维独特性的并非是他所录入的观点序列，而是他有能力启动和调用的关联。 一个人头脑中储存的知识可以分为：

- 陈述性知识（declarative knowledge）：有关事实或资料性的知识。不要将这种知识当做静态的东西，而是看作动态的、可运用的、可以用来完成某件事的技能来学习。
- 程序性知识（procedural knowledge）：按一定程序操作从而获取的知识。可以通过技能的训练不断强化和完善

在学校的学习是被动式的，满足于理解和记忆层面。虽然在学术研究中会有深入思考，但这种思考仍旧有很大的局限性，不是从理论到理论，就是从方法到方法，都没有跳到一个更大的视角，去反思这些知识的深层价值，没有去思考这些知识和我们自己的生活和思想的关联。一旦我们在应用的情景中去重新审视这些知识才会突然发现这些知识可以这样应用，发挥这些效力，可以当作这样一种技能。可能的三种操练知识的方法：

1. 写作

写作是一种典型的知识建构活动。在阅读时我们对信息的理解和纳入常常满足从一个浅表的层面去理解，但是在写作时，也就时信息输出时，我们必须去分析知识的深层结构，观察和调用知识和知识之间的深层关联，不然我们无法自如地将它们组织起来。因为一篇文章要被某人读懂、要把人说服，需要缜密的思维，清晰的表达和翔实的依据，这些都要求我们对知识的编码和组织达到一个相对高的水准才行。

1. 游戏

也可以称为“思想实验”。构造一个现实中并不存在的假象情景，然后运用所学的知识来设想事物在这个情景中的变化。在这样的操练中，思考者往往会得到比原先更为深刻的领悟。

1. 设计

调用已有知识，通过设计某一种解决方案来解决某个特定问题，迫使学习者综合性、创造性地调用知识。 （设计三国杀的例子）

(4) 融合

学习高手常常会有意识地把不同领域甚至不同学科的知识摆在一块，然后尝试去分析、对比它们潜在关联。Charlie Munger将那种只会用单一学科知识思考的人称为“铁锤人” (To a man with a hammer, everything looks like a nail)。只有广泛涉猎不同学科的知识，把这些学科中的基本理论编程用一观察和分析现实对象的思维模型，才能最大程度上避免思维上的偏差和狭隘。这种多学科模型的方法，可以产生一种爆炸性的合力效应，让人获得不同寻常的智慧。融合有3类结果。

1. 迁移
   Paul Granham: 著名的黑客将年少时学画的经验迁移到了他学习编程中。
   - 画家学画的方法时直接动手去画，而黑客学习编程的方法也是在实践中学习。Paul初学编程时还是抱着书读，不过随后就放弃了，直接动手。
   - 画家学画需要临摹，从大师的作品中学习。而黑客则是通过研究优秀程序员的代码来学习编程，开源社区是他们最好的学校。
   - 一幅画是逐步完成的，先画轮廓、草图，然后填入细节，一步步臻于完美。在这一启发下，Paul领悟到编程语言的首要特点是允许malleable(动态扩展)。编程语言是用来帮助思考程序的，而不是用来表达你已经想好的程序。它应该是一支铅笔，而非钢笔。因此在编程中过早优化(premature optimization)是一件危险的事情。

1. 印证
   印证式迁移能够帮助探索规律。思考者已经拥有了丰富的、充足的、多元的思考材料，潜意识的作用是借用其强大的并行计算能力，把这些思考材料进行各种组合。你素材准备工作越充分，那么获得创造性成果的概率越大。交替运用意识和潜意识。
   
2. 互补
    互补式的知识融合，是指我们可以对同一个议题，找到完全不同的视角下的论述，把他们综合在一起，就可以得到对这一议题比较全面和深入的认识。 （iPhone的发明并不是解决了什么难题，而是让大家惊讶的发现原来我们可以用这样的方式和电子产品进行交互，本质上是一种观念的颠覆。）

总的说来，将知识进行融合的关键是能够洞察出知识背后的深层结构。在表面上不相干的知识背后，发现潜在的相似性、互补性和启发性，找到知识与知识间隐含的联系。

###  How to Solve It?

1. Understand the problem

- What is the unknown?
- What are the data?
- What is the condition?

1. Devise A Plan

- How the various items are connected?
- How the unknown is linked to the data?
- Is there any related problem?

Mere remembering is not enough for a good idea, but we cannot have any good idea without recollecting some pertinent facts.

1. Carry Out Plan

- Check each step

1. Replay

- Can you check the result?
- Can you derive the result differtly?
- Can you check the argument?
- Can you see it at a glance?
- Can you use the result, or the method for some other problem?

### Learning How to Learn [MOOC]

#### What is Learning?

- Two modes:

1. focused mode: centered in the prefrontal cortex, involve thinking about things you are somewhat familiar with.
2. diffuse mode: broad-ranging perspective, representative of the brain’s many neural resting state

It often takes time for neural processing to take place, and time as well to build the new neural structures that allow us to learn something new. It’s through practice and repetition that we can help enhance and strengthen the neural structures we’re building as we’re learning something new. Practice and repetition is particularly important for more abstract topics.

- Tackle procrastination
  1. Pomodoro technique: brief 25 minute stretch of focused concentration, followed by a bit of mental relaxation.
  2. Keep a planner journal so you can easily track when you reach your goals and observe what does and doesn’t work.
  3. Commit yourself to certain routines and tasks each day.
  4. Write your planned tasks out the night before so your brain has time to dwell on your goals and help ensure success.
  5. Arrange your work into a series of small challenges.
  6. Get rewards [养成习惯的一个步骤]. Deliberately delay rewards until you’ve finished a task.   
     
  7. Watch for procrastination cues. Try putting yourself in new surroundings with few procrastination cues, such as the quiet section of a library. Gain trust in your new system. You want to work hard during times of focused concentration and also to trust your system enough so that when it comes time to relax, you actually relax without feelings of guilt or worry. Have back up plans for when you still procrastinate. No one is perfect after all. Eat your frogs first every day.

- Memory
  - Working memory
  - Long term memory: storage warehouse.
- Learning
  - ILearning well often involves bit by bit, day by day building of solid neural scaffolds. This is why tackling procrastination is so incredibly important. It helps you build better memories. Because you start earlier. You want to keep up with your learning and avoid last minute cramming.
  - Sleep is important in washing away the toxins that develop during our day’s activities. You want to avoid taking tests or doing anything difficult with little sleep the night before, because it’s like trying to think with poison on the brain.
  - As importantly, exercise is surprisingly valuable in helping improve both our memory and our ability to learn.

#### Chunking

- Chunks are pieces of information, neuroscientifically speaking, that are bound together through use and often through meaning. You can think of a chunk as a scintillating [scintillate vi. 发出火花；闪烁] network of neurons that compactly synthesizes key ideas or actions.
- Chunks can get bigger and more complex. But at the same time, they’re a single easy to access item that you can fit like a ribbon into the slot on your working memory.
- Chunks are best built with focused, undivided attention, understanding of the basic idea, and practice to help deepen your patterns and to help you gain big picture context.
- Simple recall, trying to remember the key points without looking at the page, is one of the best ways to help the chunking process along. It seems to help build neural hooks. They help you better understand the material. Also try recalling material in places that are different from where you originally learned the material, so it becomes more deeply ingrained and accessible
- Transfer is the idea that a chunk you’ve mastered in one area can often help you much more easily learn chunks of information in different areas that can share surprising commonalities.
- Interleave your learning by practicing your choice of different concepts, approach, and techniques all in one session. Chunks are very important, but they don’t necessarily build flexibility, which is also important in becoming an expert with the material you’re learning.
- Illusions of competence in learning
  - Learn to recognize when you’re fooling yourself about whether you’re actually learning the material.
  - Test yourself frequently. Using little mini-tests to see whether you’re actually learning the material, or whether you’ve been fooling yourself, thinking you’re learning when you’re actually not.
  - Recall is actually a form of mini-testing.
  - Try to avoid depending too much on highlighting, which can fool you into thinking that the material is going into your brain when it actually isn’t.
  - Mistakes are a good thing to make when you’re learning. They allow you to catch illusions of competence. Avoid practicing only the easy stuff, which can bring the illusion that you’ve mastered the material. Deliberately practice what you find more difficult to gain full mastery of the material.
- Einstellung [思维定势] is when your initial thought, an idea you’ve already had in mind, or a neural pattern you’ve already developed well and strengthened, prevents a better idea or solution from being found. Or keeps you from being flexible enough to accept new, better, or more appropriate solutions. The Law of Serendipity is helpful:
  1. In order to discover anything, you must be looking for something.
  2. If you wish to make an improved product, you must already be engaged in making an inferior one.

#### Renaissance Learning and Unlocking Your Potential

- Metaphors and analogies aren’t just for art and literature. One of the best things you can do to not only remember, but more easily understand concepts in many different fields, is to create a metaphor or analogy for them.
- If you change your thoughts, you can really, truly change your life. It seems people can enhance the development of their neuronal circuits by practicing thoughts that use those neurons.
- Overconfidence in your results can result from using only one mode of thinking. Through sharing with others and hearing others’ opinions, you can more easily catch where your thinking has gone astray.
- Counterintuitive strategies such as the hard start jump to easy technique, can give your brain a chance to reflect on harder challenges even as you’re focusing on other more straightforward problems.

### How we learn? (如何学习)

本书深入浅出地解释了学习时，大脑的工作机制，包括记忆是如何形成和存储的，记忆的遗忘规律又是什么。在了解大脑工作原理的基础上，作者介绍了众多脑科学、心理认知学领域中，具有里程碑意义的研究成果，从中总结出了一系列颠覆传统认知的学习方法，帮你在同样的时间里，学得更快，记得更牢。

一、记忆是如何形成、被存储和提取的？

人的大脑中，用来记忆的核心部位有三个：内嗅皮层、海马体和新皮层。

内嗅皮层类似一个过滤器，负责过滤涌入大脑的海量信息。

海马体负责组合这些信息，把和这些新信息相关的神经细胞，通过神经突触连接起来，新记忆就这样构建起来了。

新信息被打上“记忆”的标记后，就会存储到新皮层上，新皮层就是大脑最外面那层褶皱。 每次提取这些记忆的时候，这部分皮层细胞就会活跃起来，同时，跟记忆有关的神经细胞之间的突触就被加厚一次，每次神经突触被加厚，神经信号就会传递得更快些，记忆就这样被加深了。

不过，海马体是一个编故事的高手。为了让每一段情节都合情合理，它要根据现有材料找出关系、做出判断，把松散的信息拼合成一个能让人理解的整体。海马体的这种“脑补”机制，到时我们在提取记忆的时候，总是出来一连串信息，没办法做到十分精确。

二、遗忘是怎么回事，遗忘的规律是什么？

作者认为，遗忘是大脑中很重要的一个功能，它能帮助过滤垃圾信息，使大脑专注在某一件事情上，只让跟这件事有关的信息被提取出来。 关于遗忘的规律，科研人员已经探索了一百多年： 19世纪80年代，柏林大学的教师赫尔曼·艾宾浩斯发明了著名的遗忘曲线。他提出，人们对新事物的记忆会随着时间的推移而不断减弱，而且最初几天遗忘的速度还特别快。 20世纪80年代，加州大学洛杉矶分校的比约克教授夫妇，提出了“记忆失用理论”。他们认为，人的记忆其实有两个纬度，一个是存储强度，一个是提取强度。存储强度不会随着时间减弱，而提取强度会随着时间慢慢减弱，但通过复习，提取强度和存储强度都是可以越用越高的。

三、如何学习才更科学有效？

1. 学习的时候多换几个场所，会帮你把学到的东西记得更牢。

传统的学习观念认为，学习就要找一个固定的安静场所。 但是作者的建议恰恰相反：学习的时候多换几个场所，会帮你把学到的东西记得更牢。每当我们要提取记忆的时候，大脑总会冒出一连串信息，比如当时学习的场景。 研究人员就推断并实验证明：如果能还原到最初的学习环境里，记忆的效果会更好。但是，还原最初的学习场景是一件可遇而不可求的事，要想让记忆的提取能力越来越不被周围环境影响，把学到的东西记得越来越牢，就要改变一些习惯，比如多换几个学习场所。

1. 交替学习，能快速提升辨别能力。

    交替学习的意思是把既相关又不相同的题材混合到一起来学习，和交替学习相对应的是集中学习。交替学习以前一直被用在音乐教育和体育训练中，比如，体育教练会让运动员交替进行力量训练和耐力训练，来保证运动员的局部肌肉有足够的恢复时间。

    后来，心理学家们发现，交替学习可以增强大脑的辨认能力，从而提高数学解题能力。在数学学习过程中，不同题型掺杂到一起，会迫使我们去分辨每道题属于哪种类型，把题型跟我们已知的解题方法相匹配，才能找到解决方法。

    比如说，很多人都觉得应用题太难，就是因为应用题很少会明确指出应该用什么概念，用哪个方法来解题，总搞得人措手不及。这时候，交替学习的好处就凸显了，它能让我们的大脑准备好随时面对意想不到的事情，快速分辨出这种情况应该用什么方法应对。

1. 脑科学家认为，睡眠可以巩固我们的学习成果。

脑科学领域有一个主流共识，睡眠可以帮助大脑巩固记忆，还可以把一些分散的、看起没有关联的信息给联接起来，另辟蹊径地解决某个难题。(periodic table of elements) 现代睡眠之父、芝加哥大学教授柯莱特曼和他的学生阿瑟发现，人在睡觉的时候，大脑皮层还在活动，尤其在“快速眼动期”，大脑皮层的活动跟醒着的时候一样剧烈。这时候，大脑做了很多信息整理工作，深化和巩固我们醒着的时候学到的技艺，让碎片化知识形成更完整的“图景”。脑科学家甚至认为，睡觉本身就是学习。

###  暗时间 {#anshijian1}

提到的心理学相关书籍：

1. Think Straight About Psychology: 与“众”不同的心理学
2. Nudge: 助推——我们如何做出最佳选择，Richard Thaler (经济学和心理学联姻)
3. Made to Stick: 让创意更有黏性，研究创意点子之所以流行之本质原因
4. The Social Animal: 社会性动物
5. Searching for Memory: 找寻逝去的自我，讲大脑记忆原理
6. The Tipping Point: 引爆点
7. Blink: 决断2秒间
8. Outliers: 异类
9. Psychology of Judgment and Decision Making: 决策与判断
10. Predictable Irrational
11. Miskates were made, but not by Me: 错不在我
12. Mean Genes
13. Influence
14. Sway: 摇摆
15. Evolutionary Psychology: 进化心理学
16. Asking the Right Questions
17. Nonsense
18. Crimes Against Logic

- 善于利用思维时间的人，可以无形中比别人多出很多时间，从而能比别人多活很多年。思考得多得人往往心理年龄更大…讲临时得记忆变成硬编码的行为。……每个人的手表都走的一样快，但是每个人的生命却不是。衡量一个人生活了多少年应该用思维时间来计算。......用投入时间和效率的乘积来衡量。......看书并记住书中的东西只是记忆，并没有涉及推理，只有靠推理才能深入理解一个事物，这部分推理过程就是思维时间。......充分利用走路，买菜，洗脸，出游，吃饭，睡觉等所有这些时间进行思考，反刍和消化读过的东西，日积月累将产生庞大效应，无形中多出一大块生命。

#### 设计自己的进度条 {#anshijian2}

为什么要进度条？没有的话我们不知道什么时候能完成。可以分割任务，设计进度条。这需要你对整个目标的几个重大步骤有清晰的界定，能够对每个步骤的耗时作出靠谱的上界估计。（<span color="blue>Hui:我觉得这个“靠谱估计”本身就非常难（Planning fallacy </span>））。

学习新事物时总会遇到各种各样的困难，在面对未来不确定性时会过早退出。其实我们畏惧的不是困难本身，而是其所暗示的时间经济学意义。可以上网查下遇到相似问题的人，绝大多数时候你并不孤单，你踩过的坑里尽是前人的脚印。不要仅仅因为一时摸不着头绪，找不着出路就退出，问一问自己的决策是否基于足够的信息。

#### 学习密度和专注力 {#anshijian3}

- 能够迅速进入专注和长期保持专注（抗干扰）是高效学习的两个最重要的习惯。抗干扰能力可以练习：
    - 在有干扰的环境中看书
    - 利用碎片时间阅读思考，锻炼迅速集中／保持注意力

- 只要在一个选择上专心致志地专研下去，最有必然能成为高手或者绝顶高手。不要做饿死在干草堆之间的驴子。如果你有钱不知道花在哪，先不做决定没问题，因为钱还是你的。但如果你有时间不知道花在哪，不行，因为过去的时间就不是你的了。所以面对纠结的选择不要回避决定，既然终归是个痛苦的决定，那就痛一回，好好思考和调查之后作出一个决定并坚持下去。

#### 为什么应该从现在开始写博客？ {#anshijian4}

用博客的形式来记录下你有价值的思考，会带来很多好处，却没有任何明显的坏处。 

1. 书写是为了更好的思考。将一件事讲出来是最好的“学”，如果你讲不清楚，你还没有理解。为了让一个不明白的人明白，你必须知道从明白到不明白究竟要掌握哪些概念，这就迫使我们对大脑中整个知识体系寻根究底，把藏在水面之下的那些东西统统挖出来，把大脑中那些我们知道，但不知道自己知道的潜在概念或者假设都挖出来，把它们从内隐记忆拉扯到外显记忆中。不要担心太幼稚或者有漏洞被人笑话。**人非圣贤，正是因为有漏洞才值得交流，得到改进。藏着掖着的想法永远不可能变得成熟**。

- “我强烈感觉它是对的，但我说不出所以然来”，这时候往往是到大脑中翻箱倒柜，弄清来龙去脉，深入反思，纠正一直以来错误的潜在前提假设的时候。“我强烈感觉这个说法有问题但说不出哪有问题”，这也是一个极有意义的瞬间，它几乎总是意味着你对一个问题的认识有潜在的偏差，在你没有觉知的地方引入了一个潜在的假设、偷换了一个重要的概念。如果你选择经常总结自己的知识体系，并说出来给你的读者听，你就会发现自己创造了这样的机会。如果我们不反思，很多事情都感觉理所当然，但一开口说给人听常常会发现事情开始变得不那么明显。如果你只感觉到了答案，却不知道大脑得到这个答案之前做了哪些推理，你又怎么知道哪一环节出了问题呢？

- 注意一下很多人的发言，如果你把他们的发言分为“前提”，“假设”，“逻辑”，“结论”这四个部分，你会发现一大堆只会不断下结论，摆立场却见不到这些结论前提，假设和个中逻辑。

- 不要担心写不出来。不用急于求成，在一个主题上深入下去思考，总能挖到别人挖不倒的角落。你能让一个问题在大脑停留的时间越长，就越是能够发现新的东西。有时即使已经想通写下来，大脑仍旧会继续回味，没有撤出潜意识，可能之后在某种激发下会有新的感受。能把问题长时间停靠在潜意识中是一种技能，能够带来很大的好处。停留时间越长你越琢磨得透彻，比别人看到得就越多。如果你逼着自己将一些不成熟的想法写下来，看着自己写的内容，试着进一步拓展它们，就有可能在理性的道路上走得很远。

1) 激励你持续学习和思考：如果没有持续学习和思考，很快你的博客就没有内容了。如何长期写一个价值博客？让自己成为持续思考的人，并只写你真正思考和总结之后的产物，其它一切会随之而来。

> 只做你最感兴趣的事情，钱会随之而来。

2) 学会持之以恒地做一件事情。很多人在生活中容易觉得迷失，不知道想要做什么，是因为没有一件能够持续地做的事情，用俗话说就是没有主心骨。用积极心理学的话来说就是没有一件能够创造流体验的事情，而书写自己的思想则是一件容易产生流体验的事情，在理性书写的时候，大脑逐渐进入推理分析模块，一切不愉快的情绪，烦躁感会逐渐消隐下去。

3) 一个长期的价值博客是一份很好的简历。

#### 时间和效率 {#anshijian5}

1. 根据主题来查阅资料，而不是根据资料来查阅主题。避免见树不见林。获得针对同一个主题的不同观点（参见《如何阅读一本书》的主题阅读）

2. 学习一个东西之前先在大脑中累积充分的“疑惑”

3. 有选择的阅读：选择一本书中感兴趣的章节优先阅读；对书中技术性较弱密度较低的部分快速略读。

4. 利用时间碎片阅读：点滴时间汇聚成长尾！阅读不能停，要将这个习惯变成每天吃饭睡觉一样的事情。
为什么看不懂：
    - 看得不够使劲：书读百遍，其意自现
    - 涉及到你不懂的概念：这是技术性不理解，需要cross reference
    - 作者讲述的顺序不对，你接着看下去可能就懂了
    
#### 知识结构 {#anshijian6}

- 抓住不变量
    - 知识分为本质和非本质的
    - 要有基本的知识存量。不具备必要知识是无从思考的，如果你不知道某个工具的存在，遇到问题的时候很难想到需要使用这么样一个工具，本质知识就是使用得最为广泛的工具。
    - 熟悉你的工具，并非指熟悉所有细节，而是那些重要的，或者无法在需要用到的时候按需查找的知识。
    - 在学习新知识的时候，常常问自己这3个问题：本质是什么？第一原则是什么？该知道的结构是什么？
    - 分析问题和解决问题的方法也是本质知识，但需要很长时间的锻炼和反思。
    
#### 学习习惯 {#anshijian7}

- 时常反省注意自己的思维过程。尤其当遇到无法理解或解决的问题，最需要将原先的思维过程回顾一遍，看看到底哪个环节被阻塞了妨碍了理解。问题到底出在哪里。并分析以后需要加强哪方面的思维习惯，才能够不在同样或类似的时候被绊住。将思维的大致脉络写下来是一个很好的习惯。

- 养成反驳自己想法的习惯

- 重视知识本质：底层知识，算法数据结构，基本的程序设计理论，良好的编码习惯，分析解决问题的能力，强大的学习能力和旺盛的求知欲，大脑思维方式永远不过时。

- 重视提前累积的强大力量。计划订长一点，自然可以多获得准备时间。设想你若干年后会在做什么事情，需要哪些技能，现在就开始准备。你比别人往后多看一年，你就比别人领先一年时间来准备，这个差别是巨大的。一个5年计划可以让你获得从现在开始5年准备时间。5年中每天腾出半个到一个小时专心于某一件事，认准一个方向，每次走一点，其实不用5年，两年就会发现宏大的效应。

- 抬起头来：人的思维非常容易见树不见林。时不时抬起头来审视一下自己正在做的事情，问一问它有什么价值，时不时你真正希望做的。你的时间就是你的资源，你投入这些资源来掌握知识，所以到底用来掌握哪些知识是一个很重要的问题。仅仅遵循兴趣是不够的，人会对很多次要的东西产生兴趣，并一头钻进去浪费好多时间。所以判断一个东西值不值得学习是很重要的。

- 记忆机制 我们在记忆的时候将许多线索（场景，问题背景，甚至所处语言环境，空间位置）一并编码记忆，事后能否提取出这单记忆眼中取决于线索是否丰富、以及在回忆的时候是否重现了记忆时的线索。...理解记忆，知识中包含了精细的概念，逻辑，一般的解题原则，通用解题手法，背景知识，类似问题等等无数的记忆和提取的线索，而非孤立的，任意的文本序列。...缺乏线索的记忆就像记忆海洋中的孤岛，虽然在那里，但是难以访问。而富含线索的记忆则是罗马，条条大路通罗马。...环境，味道，声音都被作为提取线索和记忆编码在一块了。 我们甚至会把语言背景作为线索编码进记忆。例如：

> 在一个著名的悲剧爱情故事中，双方因为家庭不同意最终双双殉情，故事主角是？In a famous love story, what were the names of two lovers who died because of family disapproval? 前一个问题答案可能是：梁山伯和祝英台；后一个问题的答案是：罗密欧和朱丽叶

在回忆的时候若不能呈现当初记忆时候某些关键线索，就可能导致所谓的线索依赖性遗忘（cue-dependent forgetting），在线索依赖性遗忘中，你的大脑并非没有存放目标记忆，只是线索不对，无法提取出来而已。...由于记忆的提取很大程度上依赖于一些表象上的线索来提取的，因此这些表面不相似性便阻碍了我们在问题之间进行类比，阻碍了我们将在一个情境下掌握的道理运用到另一个情境下。

大脑记忆的简化模型：
    - working memory：当前在意识、思考的区域。
    - long-term memory 我们的working memory容量有限，同时只能容纳约5个有意义的信息组块（COURSERA: learn how to learn）。我们记忆的这种工作方式对学习的启发：
        1. 事实性知识先于技能：事实性知识使得组块成为可能，扩大了我们工作记忆的容量（<span color="blue">Hui:虽然我们脑子能够处理的组块数目有限，但组块大小的改变能改变工作记忆的容量。</span>）假设A有10000个事实性知识，B有9000个事实性知识。假设两人每个月同样学习500个新知识，由于A背景知识充足，A能记住10%，B能记住9%。十个月后，知识差距就从1000扩大到1047。照这个趋势，A的知识存量只会越来越多，B很难追上，这就是知识的马太效应。
        1. 记忆是思考的残留物：你的记忆不是你想要记住或你尝试记住的事情，而是你所思考的事情。大脑总是避免思考，而学习是要对抗这个趋势。“必要难度”理论指出：记忆的储存和提取呈负相关。存入记忆容易，提取出来会不容易；反之如果存入吃力，提取会更牢。只有在工作记忆中进行深度加工过的知识，才能有效存储在长期记忆。

> <span color="blue"> Hui:很多事物本质上是有相似性的，找到光怪陆离的表象下的实质是最重要的认知能力。</span>

**我们在从既有经验总结知识的时候，应利用适当的抽象来得出适用范围更广的知识；在遇到新问题时，同样应该对问题进行抽象，触及其本质，去除不相干因素避免干扰，从而有效提取之前抽象出来的知识。**
我们的记忆并不像电脑的存储设施那样忠实记录，忠实读取，而是在记录和读取的时候都是相当程度上“构建性”的，而构建所用的“素材”则是我们之前在生活中积累出来的经验。这也是为什么同一个故事经不同人口口相传之后会出现形形色色的版本的原因。

- 如何有效地从日常经验中总结知识，以及如何能够真正学以致用。

1. 创造机会回顾知识（讨论分享，整理笔记，书写：将一段时间学习的知识按照一个主题系统地“串”起来，大大地丰富了知识之间的关联，平添无数提取线索。）

2. 虚拟情境：努力设想自己处于别人的境地。你无法真正遍历每条人生路径看看会发生什么，你没有这样的时间资源，取而代之的是你只能通过别人的“替代经验”，自己的“虚拟经历”来获得尽量多的信息。

3. 抽象和推广：我们从大量经济决策中得到一条适用范围很广的规律——经济决策可以抽象为投入／回报比例的考量。这是知识获取阶段的抽象；如果不懂得看到问题本质，便很难利用之前推广出来的结论（如：投入／回报，风险估计等等），而是会被我们的原始大脑的一些可预期的非理性所控制（例如从众、从权威），成为正常的傻瓜。

4. 联系比较自身经历：将别人的经历或者通过阅读和观察得来的经历和自身的经历进行比较，常常能够得到非常有价值的结论。

- 如何甄选知识？解决方案如下：

1. 经验主义：理论好不好用，必须眼见为实，拿出大家都认可的证据，经得起实证检验。
2. 实用主义：理论要有实用价值。
3. 可证伪性：科学就是建立在经验主义基础上，以实用主义为原则筛选，可以被证伪的理论。波普尔《猜想与反驳》讨论证伪性。因为科学能够被证伪，才能发展，思维才能迭代。<span color="red">鸡汤理论的问题就在于不可证伪。这些不可证伪的理论有巨大的心理吸引力，因为它们符合任何人的认知，貌似完全正确，还能够解释一切。无论发生什么事情，你都能预先理解它，这不仅给你智力上的掌控感，而且让你拥有应对这个世界需要的安全感。</span>

甄别有价值的信息的能力，成为继资源、胆识、机遇之后获取信息不对称的的第4手，权重越来越高。

因为知识的局限性而对事物的看法产生无法消除的偏见，有时候打破这种偏见的唯一途径就是开阔视野，多积累知识，以及和具有不同知识背景的人讨论。

### 如何高效学习 {#gaoxiaoxuexi}

（来自得到，许岑）

- 高效学习是以解决问题为导向，而非总是依靠兴趣。学了东西之后一定需要反馈：讲或者用，这样才真正学会了这个东西。
- 练习不必顾全大局，针对不熟悉的细节反复练习
- 碎片化学习是个趋势，必须掌握这个能力。碎片化学习需要带着问题去寻找碎片。最重要的是将这些碎片链接起来。
- 将任务“严峻化”：可以定好给别人做报告
- 设定小目标，形成惯性。
- 购买昂贵的学习工具。东西少而精，就更容易专注。
- 营造仪式感: 比如使用射灯营造舞台的感觉
- 高质量睡眠：缺少睡眠很难专注；运动有助于睡眠。
- 用文字，语音，录像制造反馈： (1) 写摘要：照着文本，用自己的话; (2)语音反馈：录音; (3) 肢体类反馈：录像

### 阅读学习方法 {#xueduxuexi}

**深度阅读**：

- 阅读姿态：尽可能让自己沉浸进去，把手机放远一点，躲到一个僻静的角落。沉浸到书里面去，进入心流状态。
- 阅读选择：元知识
- 阅读定力：对关心的主题不惜代价，需要信息上的穷举，没有遗漏。
- 阅读野心：批判思维，平视的心态阅读而非仰视。 阅读又许多功能，最重要的是对生活、人生带来改变。是否用行动将其转化为价值，智慧是否得以增加，解决生活现实问题的能力是否提高，心态是否更加平和，与他人关系是否得到改善。

**深度学习**:

- **反复练习**: 我们都知道大脑灰质，但大脑还有近50%由“白质”构成，即髓磷脂，也叫髓鞘质，它得以产生并包裹大脑神经元轴突的过程叫作神经髓鞘化。神经髓鞘化能使神经传导速度变快，好比由拨号变成宽带，对高级动作技巧和反应的学习来说至关重要。  
神经髓鞘化会在两种情况下发生：小朋友在成长过程中自然获得；成人也可获得，但必须付出大量努力反复练习才行。 好消息是大脑的可塑性伴随我们一生，也就是说，什么时候学习都不晚，坏消息则是这并不容易。重搭大脑回路，需要大量、反复、有针对性的练习，这就需要我们：
    - 反复练习: 形成肌肉记忆是成人学习的必由之路。
    - 正确练习: 仔细聆听反馈给你的信息，有针对性地调节练习方式同样重要 ——你不会想给大脑搭条错误的回路。
    
- **善用注意力剩余**: 注意力是我们最宝贵的资源。时间碎片化对我们的消磨，主要就来自于在多件事中来回切换，注意力随之损耗，于是忙碌、焦灼，效率低下。我们试图多任务处理以获得效率，结果却适得其反。接受人脑的黏性，我们只能克制多任务处理的冲动，转而致力于两件事：
    - 一个时间段只做一件事
    - 前后相邻的时间段尽量做相关的事情，专注做一件事，会形成注意力剩余，对做相关的事有用，不要浪费它。 把时间组块，把相关的工作组块，善用注意力剩余，事半功倍。
    
- **养成适合自己的工作节奏**: 好习惯是最强大的，而坏习惯是最顽固的，所以要刻意养成好的工作习惯。习惯最有用之处就是自动克服拖延症，并把对工作的焦虑化解为一连串固定流程，不再需要耗费心理能量去启动，去克服。 下面这些模式都可行，看看哪个适合你： 
     - 隔绝模式：工作时与世隔绝，像僧侣一样； 
     - 双模式：在两种模式中切换，既像僧侣一般与世隔绝，也有正常生活； 
     - 节奏模式：定期，最好是每天，都固定做同一件事，形成节奏； 
     - 记者模式：记者有截稿期，按需写作。

- **敢于关机**
- **干票大的**: 把视线从眼前事务中抽出来，往远方看，当然也不要太远。给自己定下未来半年到一年要做成的一件大事，然后去完成它。高远目标－任务分解－针对性练习－反馈调整－朝下一个目标迭代提高，这是摆脱低效忙碌的终极大法。

### 好好学习 {#haohaoxuexi}

这是一本讲学习方法，讲如何管理自己知识的书。它将帮助你把零碎的知识打造成为高效的知识管理体系，构建你的学习竞争力，让所学知识真正变成你的资产，让学习成为财富积累的过程。

一、什么是知识？

1．信息和知识的区别: 只有那些能够改变你行动或者认知的信息才是知识，否则它只是信息。

2．低水平的勤奋: 努力但效率很低，进步很慢的学习，就是低水平的勤奋。比如，有的人读了很多书，上了很多培训课，但是能力仍然提升不起来。

二、如何高效学习

1．两种学习效率

（1）技术效率：不断学习解决具体场景下问题的学习方式。在技术效率层面去解决问题的水平比较低。

（2）认知效率：在解决任务的时候，不仅掌握了解决的办法，还弄明白了这类问题背后的规律，这种努力方式就归类为提升认知效率。

2．一个观点，两个假设

关于学习方法的观点：多花时间去研究事物背后的规律，从规律入手进行学习，效率才会更高。这个观点是建立在两个假设基础之上。

（1）假设一：世界上大部分领域，看似复杂的现象其实往往是由少数重要的规律决定的。也就是说假设复杂现象背后是简单的规律。本书也是建立在这个假设基础之上。

（2）假设二：世界上各个事物之间的关系，不是简单的因果关系，而是彼此相互联系、互相影响的。

3．临界知识

通过学习和掌握少数重要但是影响广泛的规律，并以此建立的认知，应用在各个领域中，就能形成自己的跨界竞争优势。而这些能够在各个领域广泛应用的重要基本规律，被称为临界知识。 如果能够在学习的过程中优先主动地掌握临界知识，掌握事物背后重要的基本规律，那学习效率就会高得多。

三、如何掌握临界知识

1.基本原则

掌握临界知识的基本原则是：要了解知识的可靠性和局限性。要确保这个规律是可靠，经过了广泛地验证，并且清楚这个规律的适用和不适用的领域。 优先使用“硬科学”的规律。所谓硬科学，是相对软科学而言。硬科学是指数学、物理、化学、生物学这样的学科，而软科学是指社会学这类的学科。

2.三个底层方法

（1）刻意练习

如果你要掌握某一领域的知识，那么你可以去寻求这个领域一流的导师，然后学习他是怎么思考和解决问题的。坚持这样刻意练习，往往就能够更快速地发现和掌握问题背后的规律，理解一点就通达一点，从而极大地提高学习的效率。

（2）反思

总结不是反思。反思是对产生结果的原因进行分析，反思的实质是对假设进行校正。比如，反复思考研究当初做这个决策的依据是什么，为什么是这样，当初的假设正确吗？

（3）以教为学


3.三个学习技巧

（1）记录：记录和写下来是不一样的。

一个好的记录，要做到两点：第一点，要记录整个事情发展的过程；第二点，主动地记录看不见的关系，而不仅仅是记录流水账。

（2）定期回顾：一方面的原因是，时间一久，我们很容易忘掉学的东西；另一方面，很多事情发生的原因和最后的结果之间时间间隔很长。如果不去回顾，往往没有意识到这两者之间其实是有联系的。

（3）付费学习：一方面是指通过“买时间”来增加有效学习时间；另一方面是指，通过买“高质量的知识产品”或“向专家付费”获得咨询建议，来提高学习效率。


### 跃迁 {#yueqian}

身法：头部战略（价值高/低，自身竞争力优势高/低），资料源头，跨界联机学习(自己打磨一个知识模块，抛出去换别人的知识模块)，问题树取代知识树。

心法：专注的站在头部区，保持开放的心态，迟钝让人更有定力
2015

## Emotion Management

### Emotional First Aid 

> Dr. Guy Winch is a licensed psychologist, author, and in-demand keynote speaker whose books have been translated into 24 languages. His first TED Talk, Why We All Need to Practice Emotional First Aid has been viewed over 5 million times and is rated as the #5 most inspiring TED Talk of all time on ted.com He also writes the popular Squeaky Wheel Blog on Psychology Today.com (https://www.psychologytoday.com/blog/the-squeaky-wheel) and he has dabbled in stnad-up comedy. His website is www.guywinch.com. You can view his TED Talks here: https://www.ted.com/speakers/guy_winch

Healing Rejection, Guilt, Failure, and Other Everyday Hurts

### How To Keep People From Pushing Your Buttons

> About the author: Albert Ellis(1913-2007) held M.A and Ph.D. degrees in Clinical Psychology from Columbia University. He was the founder of Rational Emotive Behavior Therapy (REBT), the pioneering form of the modern Cognitive Behavior therapies. He was the president of the Albert Ellis Institute in New York, where he practiced individual and group psychotherapy, supervised and trained psychotherapists, and presented many talks and workshops at the Institute and throughout the world. He published over seven hundred articles and more than sixty books on psychotherapy, marital and family therapy, and sex therapy.

4 fatal "Overly":

1. Anxious
1. Angry
1. Depressed
1. Guilty

3 nutty beliefs (Realistic Preferences):

(1) Awfulizing
(2) Shoulding
(3) Rationalization

The three nutty beliefs will further lead to 10 nutty beliefs:

(1) Worry too much about what other people think of you
    - Please others
    - Overly defensive

(2) Excessively fear of failure
    - Lack of risk-taking
    - Stagnation
    - Mediocrity

> If you are hitting the bullseye every time you shoot, you are standing too close!

(3) Low frustration tolerence
    - impulsive reactions, premature quitting, nagativism, avoidance of responsibility, lack of perseverance
    
(4) Blame others

(5) Worry obsessively about things to happen

(6) Perfectionism

(7) Avoid responsibility

(8) Detachment

(9) Blame past experience

(10) Bad things/people shouldn't exist

<!--

Ellis列出了四种不好的过激情绪：
过分的烦躁（紧张、沮丧、恼火、担惊受 怕）；比如你为准备一个工作面试而紧张，为孩子最近的表现而烦躁。
过分生气（戒备、被激怒，气得发疯，挫 败）：当你的配偶批评你不干活，当工作上的同事不配合或做不来时。
过分抑郁（无精打采，一蹶不振）：失去所爰的人，或失去工作。
过分内疚（过分承担责任，过分悔恨，过分自责）：比如你因为离婚而对孩子内疚，处处宠溺。
如何判断过分？其实人们在85%的时间里，是能识别出自己什么时候反应过激。而你要做的就是让尽可能多的过激反应不要发生。

你的坏情绪是怎么来的？人不是天生就有坏情绪的，Ellis给出了诱因ABC公式。
A代表曰常遇见的人或事情。除了那些重大的事件外，A就是那些烦人的小事，比如难缠的 上司、同事，办公室的勾心斗角，沟通不够； 生活中与配偶或情人的冲突，家务劳动，财务 问题。

C代表在A的情形下你的感觉和行为。如果你有一个重要的会议，但路上大堵车，这时你就会从平时的绅士变成路怒一族，不断并线加塞，嘴里骂骂咧咧。那么真的是堵车导致了你这样的路怒行为了吗？不是的，在A和C之间，有一个B

B就是我们对具体发生的人或 事的思考、判断。

这样你就会明白，不是A这件事一定会产生C的结果，A本身不会导致C，而是B导致了C，A只是诱因。

三类病态的思维模式导致情绪和行为反应过激
恐怖化的思维方式。把什么都看成了灾难，非常害怕，思维模式就是“万一……怎么 办”？比如你去面试一份工作，你可能会想 到：万一我回答不上问题怎么办？万一他们不 喜欢我怎么办？万一我被人难堪了怎么办？越想越多，就越恐慌，你高度紧张，未战而败。

应该化的思维方式。“我必须……’”我一定……“，这种”必须”“应该”的思维可能源自孩提时代，父母说：你应该对弟弟好一点；老师说：你应该五讲四美。一旦有了 “应该”的思维，就会使你对自己要求过于严苛，把自己弄得很惨。当你达到了我应该“的标准时，你就开始了对别人的”你应该”。

合理化的思维方式。这种思维就是认为什么都很合理，不可思议地将不道德或不得体的 行为合理化，骗自己接受这种行为，简单地说 就是逆来顺受。典型的表现就是：谁会关心？ 那又怎样？这种思维方式会把很多不合理的事情也认为是合理的，合理化思维是一种软弱的应对方式。

你如果老是用恐怖化、应该化、合理化去思考 问题的话，就会陷入以下10种非理性人生信条：

信条1:太在乎别人怎么看待你。因为太在乎 会导致你对拒绝的强烈的恐惧感，要么你会四处讨好别人，避免冲突；要么你就把自己装扮 成一只刺猬，逮谁扎谁。其实你更好的选择可以是这样的：“我希望你们喜欢我，尊重我， 你们要是做不到，我也能忍受”。（恐怖化）

信条2:无法忍受在重要任务上失败。如果你让自己相信在任何重大事件上都输不起，你就 不敢冒险，会墨守成规。还有就是无法忍受别人的批评。（恐怖化）

信条3:人和事都应该朝着我要的方向发展。这是由于低耐挫性和对不公平的敏感而造成的 冲动反应，会导致半途而废，逃避责任。（应该化）

信条4:某件事出错了，肯定是有人出了问题。凡事绝对化，认为事情做得那么糟，肯定 是有人不尽力，这些人善于把脏水往别人身上泼。（应该化）

信条5:对即将发生的事情总是抱着深深的忧虑。（恐怖化）

信条6:每个问题都有完美的解决方案，我必须立即找到这些方法。有时候完美主义造就了拖延症。（应该化）

信条7:在很多困境和责任面前可以让自己置身事外，凡事都能找到一个合理化的理由。 (合理化）

信条8:如果事事不投入，保持若即脱离的关注，会永远开心。很多人貌似参与了很多事， 但其实他们只是坐在那儿，被动地观察。（合理化）

信条9:因为过去或者小时候发生的一些不好的事情造成了我现在这个样子，我努力也改变不了。（合理化）

信条10:这些坏人坏事就不应该存在，真不知道拿他们怎么办。他人他事会逼得你反应过激。（应该化）

怎样应对病态的思维方式？
把事情恐怖化、应该化和合理化是三大逼迫我们就范的方式，要我们不去这么想的方法就是 第四种思考模式：你要看看在这三种思维模式 之外有什么是更好的选择，比如“我想 要……，”我更喜欢……“，”如果……就更好了“。它不是必须时刻要积极，并不表明你能够或一定成功，而是说要去试一试，即使可能会失败、被拒绝。

比如你是个演讲新手，但最近你有一场重要的 演讲，你很可能会把前面三类病态思维都用一 下：“万一我搞砸了，没人听，大家聊天会怎 么办？（恐怖化）我应该能够做好公共演讲， 我用不着害怕。（应该化）其实，这有多大的事，就是搞砸了也没人在乎。（合理化）”但如果你能更好的选择思维方式：嗯，我想要做好演讲，但也不是非做好不可，现在还有一点时间，我可以在脑子里再过一次提纲；其实我更喜欢演讲的过程，我想我肯定能从中学到什么。这样你就不会背负心理包袱。

如何让“更好的选择”成为习惯？
改变想法需要觉悟，还有需要用大量的练习建 立起第四种思维模式的习惯‘‘更好的选择“。 有四个步骤：

反思自己的C (感觉和行为）：我的感觉和行为是不是合适？
认真审视自己的B是怎么把自己弄成了C的样子（过分的焦虑、愤怒、抑郁、内疚）
如何反击和对抗自己的非理性思考方式
用什么样的更好选择来替代非理性思维
用“我想要……”，“我喜欢……”，“如果……就更好了”
-->

### Others

- From TED talk: [How to fix a broken heart](https://www.ted.com/talks/guy_winch_how_to_fix_a_broken_heart?utm_source=newsletter_weekly_2018-02-10&utm_campaign=newsletter_weekly&utm_medium=email&utm_content=talk_of_the_week_image)

Heartbreak is far more insidious than we realize. There is a reason we keep going down one rabbit hole after another, even when we know it's going to make us feel worse. Brain studies have shown that the withdrawal of romantic love activates the same mechanisms in our brain that get activated when addicts are withdrawing from substances like cocaine or opioids.

Getting over heartbreak is not a journey. It is a fight, and your reason is your strongest weapon. There is no breakup explanation that is going to feel satisfying. No rationale can take away the pain you feel. So don't search for one. Don't wait for one, just accept the one you were offered or make up one yourself and then put the question to rest, because you need that closure to resist the addition. And you need something else as well: you have to be willing to let go, to accept that it's over. Otherwise, your mind will feed on your hope and set you back. Hope can be incredibly destructive when your heart is broken.

### Feeling Good

- Depression is one of the worst forms of suffering, because of the immense feelings of shame, worthlessness, hopelessness, and demoralization. 

## Obsessive Love 

本书主要回答3个问题：

一、如何识别自己是否处已经在执迷的感情状态中？   
二、这种执迷的感情状态是由什么造成的？  
三、如何科学地走出这种状态？

执迷感情的三种表现

(1) 把对方幻想成自己的理想恋人

在完全不了解对方的情况下，就把对方当成了自己的完美情人，急于和对方建立亲密关系。产生这种理想化倾向的原因是，在刚开始一段感情时，恋人们都会极力表现出自己最好的品质来吸引对方，却无法一直坚持下去。

(2) 思想极端，得不到要毁灭

总是希望掌控对方的一举一动，认为只要足够爱对方，对方就必须爱你。当被对方拒绝时，会使用暴力手段报复对方，或采取自残的方式，来唤起对方的罪恶感。

(3) 感情中的“救世主”

享受被对方需要的感觉，总觉得只要自己多付出一点，就能帮助恋人度过难关。

造成执迷感情的原因通常是童年时期的阴影。在成长的过程中，父母的躲避，责骂，拒绝和感情上的虐待，往往会让执迷者的心灵产生强烈的被抛弃感。于是长大后，执迷者就把另一半当成了象征式的父母。

科学地走出执迷的状态要遵循三个步骤

- 转变自己的概念：你最重要的任务是改变自己，而不是改变别人。你没办法让一个不爱你的人爱上你，就像你永远都叫不醒一个装睡的人。

- 通过记录日志，打破执迷系统
    - 执迷系统由想法、感受和行为三者共同构成。
    - 执迷状态中的人往往很难控制自己的想法和感受，所以想要走出来，需要先把想法、感受和行为区分开，打破执迷系统，学会控制自己的行为，让行为脱离想法和感受的干扰，再通过行为的改变来带动想法和感受的转变。
    - 区分想法、感受和行为需要用到记录日志的方法。记录时要注意以下6个问题：(1)是什么引起这种想法的？(2)你想到了什么？(3)你有什么感受？(4)你想做什么？(5)你做了什么？(6)结果怎么样？
    
- 改变行为的四个关键方法
    - 给你的行为贴上标签；
    - 重新找回自己的兴趣；
    - 避开执迷行为的引爆器；
    - 给自己一个的时间限定，更有计划地走出不良状态。


## 思考的技术 {#sikaojishu}

大前研一的代表作。在这本书里，他提出，在瞬息万变的新经济时代，无论是企业还是个人，要想获得成功就必须掌握科学的思考方式，不被经验的藩篱所困，不被固有的立场所左右。要在掌握数据的基础上，大胆地假设，努力求证，导出结论，这也就是他提及的科学的思考方法。

一、关于经验的藩篱

这本书里最颠覆人的认知的是：经验有时候只是一时的想法，大多数时间，都是不靠谱的。其实经验是用过去的事实来验证今天的假设。这当然是不合时宜的。而在一个公司内部，很多自称有经验的人，他们总是用一时的想法来左右你的判断。

二、关于对事不对人

对事不对人的核心在于对事。也就是对于事实要有大量的掌握、分析，才能得出正确的结论。不能被一些预设的立场所左右。 一般来说，一家公司、一家分公司、一个部门都长着同一条舌头，他们习惯了人云亦云，看似从自己的立场出发，实则伤害了整体的利益。进一步说，特别是日本公司，有一种“同质化”的性格。每个人都不愿意做“出头鸟”，或者站在自己部门、公司的立场出发，而忽视了事实本身的状况，由此作出错误的判断。而不尊重事实，会让我们用预设的立场作为结论，而这样的结论通常是错误的。 

三、关于预测未来 

只要运用科学的方法，无论是在茹毛饮血的原始时代，还是今天这个互联网、移动互联网如此发达的时代，都能预测未来。 作者对于预测未来有一套自己的方法，总体来说就是分解法和实地考察法。分解法就是对已有的技术、产品进行分解，从而预测它的发展趋势；实地考察法就是要实地观察人们的消费习惯，总结规律，预测商业发展的方向。人性比技术更重要，洞悉人性才是根本。

四、思考的技术每天都可以练习 

每天坐地铁过程中，你可以思考如果你是地铁里广告发布的公司老板，你会如何提升本公司的业绩？如果你是一个在地铁里卖盒饭的老板，你会如何提升自己的销售业绩……这些都是锻炼思考力的方法。 

总结： 我们需要掌握思考的技术。思考的技术对于我们职场升迁、业绩的完成或者日常生活都有重要的意义。科学的思考方法要求我们必须抛弃固有的经验、预设的立场，从事实出发，对已有的数据进行分析，得出假设，然后再运用数据和案例来验证假设，从而导出正确的结论。这才是科学的思考方法。 

## 系统化管理人脉 {#renmaiguanli}

- 第一个方法是记录要点。想要拥有丰富的人脉网络，就需要从见面的第一天开始建立联系。不论初次见面是在什么场景，都要在交换联系方式的同时做记录，记录的信息应该包括：见面的时间地点、介绍人、主要谈论的话题、对方的关注点、需要跟进的事项等，甚至还可以简单描述一下对方的外貌特征。有了这些信息，下次需要找这个人帮忙时，就可以迅速地重建联系进行沟通。

- 第二个方法是及时跟进。和别人初次会面后的24小时内，最好给对方发一封邮件或者微信消息，时间隔得太长，对方就会觉得你没有诚意。跟进的内容倒不用太复杂，可以简单地表示很高兴见到对方，或者感谢对方拨出时间会面，也可以提及你们谈话的重要内容和你受到的启发。这样通过简单的一封邮件，你就能给对方留下可信、靠谱的印象。

- 第三个方法是区分“绑定资本”和“桥梁资本”。“绑定资本”指的是和你自己的背景比较相似的群体，比如你的同行。“桥梁资本”指的就是其他和你领域不同的多样化人脉。绑定资本可以帮你在行业内建立深厚的关系，但桥梁资本可以帮你延伸到其他领域，为你提供多样化的人脉资源和信息资源，所以二者都需要好好维护。当你看到和他们相关的行业资讯，可以迅速分享给他们；在领英上发现了对方的职位变化时，也可以向对方简单祝贺，通过信息交流构建再次联系的机会。

- 第四个方法是分类进行维护。每个人都应该把人脉按照重要程度分类，然后以不同的频率进行维护。比如重要的业务伙伴每个月联系一次，方式可以是见面或者打电话沟通。你的导师和信用背书人可以6~8周联系一次，不一定非要向他们咨询什么问题，只要简单地问候一下，让他们了解你的动向即可。如果是只有一面之缘的朋友，或者级别高很多的领导，那么一年联系一次就可以了。一个比较好的选择是过节时给对方拜年，过程不用很长，但一定要叫出对方的尊称，并表示对对方的感谢，而且千万不要用群发的方式，群发的信息会让人觉得自己并不受重视，反而起不到应有的效果。


## How Will You Measure Your Life? 

> Clayton M. Christensen: American scholar, educator, author, business consultant, and religious leader who currently serves as the Kim B. Clark Professor of Business Administration at the Harvard Business School of Harvard University. He is best known for his theory of “disruptive innovation”—first introduced in his first book, The Innovator’s Dilemma—which has been called the most influential business idea of the early 21st century.

作者将自己的人生经历与企业管理研究成果相结合，用通俗易懂的文字阐述人生规划问题。书中指出：我们一生最大的成功并不是来自他人的评价，而是内心深处的满足；搞清楚什么是你这辈子最重要的东西，才是如何评价自己人生的关键。

人们通常认为，金钱和名望是衡量成功的主要标准，不少职场新人都将收入作为选择工作的首要动机。但是克里斯坦森却认为：一千个人眼里就有一千个成功的定义，只有找到一份发自内心去热爱的工作，才会在工作中找到幸福。他还进一步告诫我们，追求事业的同时，别忘了经营好家庭关系，工作和事业给我们带来的是即时成就感，而家人给我们带来的则是长久的幸福感。

一、如何找到自己真正热爱的事业

这一部分主要探讨了三个问题，真正激励你的动力到底是什么，如何把握周密计划与偶然机会的平衡，你所实施的战略与你的最终目标是否一致。

1) 动力因素和基础因素有什么不同

我们最容易想到的，可能也是最普遍使用的，就是经济或物质激励。在作者看来，物质激励只是我们从事某项工作的一个基础因素，动力因素则来自于人们内心深处的热爱和兴趣。

2) 周密战略和应急战略在人生中发挥不同作用

所谓“周密战略”，是你在做一件事情之前，就已经制订好的周密计划，也可以说是预期机遇；而所谓“应急战略”，则是面对意外出现的机遇临时采取的措施。我们的人生规划，总是处在周密战略和应急战略相互交错和调整的状态。

3) 合理配置资源，确保我们努力的步伐不会脱离梦想的轨道

很多成功人士尽管知道家庭对他们来说最为重要，可是陪伴爱人、教育孩子是一个漫长的过程，于是他们把更多的时间都用在了职位晋升和赚取财富上。所以要避免资源投入与战略目标的不一致，就要搞明白什么是最重要的事情，然后重新配置资源。

二、把热爱的事业坚持下去

对待目标的态度不能过于死板和顽固，面对那些意外的机会和危险，要学会及时调整最初的目标，但是一旦确定下来什么是自己真正想要的，就要毫无保留地坚持，不能为了眼前利益抛弃长远的成功和幸福。

1) 有效的企业目标包括三个组成部分：一是未来的“画像”，二是员工对“画像”的认同感，三是衡量标尺。

2) 实现未来“画像”过程中的每一个阶段，都要问自己这样一个问题——我到底想要成为谁？如果有一天，你发现“画像”中的自己并不是你想成为的人，就必须停下脚步，重新考虑和选择。但是一旦确定你想成为什么样的人，就要付出100%的坚持。

3) “只犯一次错”的代价看起来总是很低的，可问题是一旦开始纵容自己犯错，心中的价值标尺、道德准则都会坍塌。人的毁灭不是瞬间造就的，而是多个“仅此一次”累积的结果。

4) 坚持是人生中最重要的事，破例一次“没有不良后果”所带来的窃喜将会诱惑人们一而再，再而三地破例，最终踏入深渊。所以，抵制诱惑的最好办法就是，永远不要迈出最危险的第一步。

三、在发展事业的同时，如何经营好家庭关系

1) 投资时间

企业管理中的“好钱”和“坏钱”理论，用在我们的生活中同样行得通。如果你只花了很少的钱，就发现自己投资方向是错误的，并且及时调整方向，这种情况下所投入的就是“好钱”。 相反，如果你把所有钱都投进去以后，才发现最初的策略从根本上就是错误的，这就是“坏钱”。不要忽视世界上你最在乎的人，要在你对这种关系有需求前就进行投资。

2) 了解爱人的需要

明确爱人的需求，是与爱人建立良好关系的前提和基础。我们的一生都在从事着一份最重要的工作，那就是当别人的配偶。许多建立在无私奉献基础上的婚姻之所以失败，就是因为他们只给对方自己想给的，却从不考虑对方想要什么。

3) 培养孩子获取成功的能力

对于一家企业来说，最重要的能力是三点，一是资源，二是应用流程，三是行为价值取向。这个模型同样可以应用在对孩子的培养过程当中。 对于孩子来说，资源指的是他们从别处获取的知识和经验，应用流程指的是他们的思考方式。 现在很多家长工作非常忙碌，但同时又急于要让孩子赢在起跑线上，于是他们把孩子送到舞蹈、音乐、钢琴等各种课外辅导班和夏令营中去。这样虽然减轻了家长的负担，但孩子们可能并不喜欢，也难以投入进去，结果浪费了大量的时间和资源。 正确的做法是：家长要时刻留意自己的一言一行；在孩子遇到困难的时候，家长要鼓励他独自解决问题，而不是替他解决；帮助孩子找到他们真正热爱的事情，而不是逼迫他们学习某种知识。

4) 看不见的手：家庭文化

企业文化决定企业员工的价值取向，家庭文化同样决定家庭成员的价值取向。特定的家庭文化一旦形成，孩子们不再需要做每件事之前都来征求父母的意见，因为他们知道父母希望他们怎样做，怎样做符合这个家庭的文化。

## Seeing the Forest for the Trees

> Dennis Sherwood now runs his own consulting business, The Silver Bullet Machine Manufacturing Company Limited, which specialises on organisational creativity and innovation. Dennis studied physics at Clare College, Cambridge University (MA), molecular biophysics at Yale University (MPhil), and biology at the University of California at San Diego (PhD); Dennis is also a Sloan Fellow (with distinction) of London Business School. Dennis was for 12 years a consulting partner with Deloitte, Haskins and Sells, and subsequently Coopers & Lybrand; he was an Executive Director with Goldman Sachs; a partner in Bossard Consultants; and Managing Director of the UK operations of SRI Consulting.

书中列举了大量运用系统思考解决问题的案例，并详细阐述了什么是系统思考，为什么需要系统思考，如何使用系统循环图来思考问题，是一本比较详实的介绍系统思考的入门书籍。

如何才能掌握系统思考的能力？系统思考本质上就是一种整体性的思维方式，它要求我们用整体的观点观察周围的事物，看清事件背后的结构和各要素之间的互动关系，并主动地“建构”和“解构”的思维能力。要掌握系统思考的能力，必须认清系统中的增强回路和调节回路，并学会利用系统循环图来帮助自己实现系统思考。

- 掌握系统思考的两个关键：增强回路和调节回路

1. 什么是回路

    回路简单说就是一种闭合的因果循环。回路当中包含了两个要素：一是实体，二是关系。而在关系中又分为两种，正反馈和负反馈。正反馈指的是一个实体如果表现出增强，另一个实体也表现出增强的状态；而负反馈就是一个实体增强导致另一个实体衰弱。

2. 增强回路

    增强回路就是不存在负反馈，事物之间的关系全部都是正反馈。事物之间的关系全部都是增强的效果，都是一方力量上涨，另一方的力量也随之增加。增强回路能够不断推动局势的强化，不管是好的还是坏的，一旦回路形成，就会开始不断的增强。
    
3. 调节回路    

    没有一个增强回路可以独立存在，在不同时间或是条件下，它都会碰上一些限制因素，而这些限制因素就是调节回路。调节回路的变化是慢慢趋于稳定的，如果这个回路呈现下降趋势，开始时会下降得很快。但随着时间的推移，下降的速度会越来越小，最终不再下降，达到一个稳定的平衡状态；如果事情呈现上升趋势，开始会上升得很快，但随着时间的推移，上升速度也会越来越慢，最终不再上升，达到一个稳定、平衡的状态。
    
4. 延迟

    延迟不是一个孤立的因素，它附着在增强回路或调节回路上。比如调节回路的特点是平滑、稳定地向一个目标前进，如果存在延迟，就可能产生其他问题或者调节过头的现象。

- 掌握系统思考的有效工具——系统循环图

系统循环图也叫因果回路图，因为它用因果关系链表示系统的结构。绘制系统循环图的5个步骤：

- 第1步：准备一张 A4纸和笔，选一个较为舒适安静的环境。
- 第2步：找问题。在纸上写下你工作或是生活中经常遇到的问题或是非常困扰你的问题。
- 第3步：找原因。思考这个问题可能发生的原因有哪些，即找出问题产生的原因。你可以把问题写在一张纸的中间，在问题周围写上三到五条原因。
- 第4步：找后果。找出现在的问题可能进一步导致的后果。
- 第5步：找回路。所谓的找回路，就是说思考你找出问题原因与问题导致的后果之间有没有相互连接和闭合的回路。如果有，就用带有箭头的直线标出，从原因指向结果，如果原因和结果之间是正反馈的关系，在箭头处标记一个加号，如果原因和结果之间是负反馈的关系，在箭头处标记一个减号。

绘制系统循环图的两个关键点：

- 不要使用动词，要使用名词。用动词来表述，得到的往往不是系统的结构，更像是在描述一个故事。
- 要注意箭头的方向，箭头方向代表了特定的含义，如果箭头的方能画反，很可能会陷入思考的误区。
    
## Asking the right questions

<font color = "blue"> Hui: 通过一系列的短小的课程式章节，这本书帮助我们培养批判性思维。它教读者如何分解一个论证过程：问题，结论，理由，证据，假设还有使用语言。我是看的英文版，但其中讲到的思维方式和语言无关。里面讲到了很多逻辑谬误。我总结了书中讲到的一系列逻辑谬误：http://hui1987.com/self-development.html#chapter-7-are-there-any-fallacies-in-the-reasoning
但和很多教授各种学习方法的书一样，告诉你这些逻辑谬误，以及如何拆解论证过程，注意其中哪些部分并不能保证你能拥有批判性思维，因为在现实中，这种一连串的理解，分析，提问的过程通常要在很短的时间内完成。所以，需要你通过练习，将这个思维方式熟悉到直接在潜意识中，这样每次使用的时候就只要调用大脑的一个模块（chunk）而不是多个模块，因为同一时间大脑能够处理的模块数目是有限的。（目前我看到的是7（ ± 2）个）。所以需要……练习！</font>

### The benefits of asking the right questions

Other’s mental slave?

1. Critical thinking to the rescue (begins with the desire to improve what we think, beliefs & conclusions)
2. Critical thinking consists of an awareness of a set of interrelated critical questions

- Non-selective: sponge reacts to water
- Selective: panning for gold (need question-asking attitude: ask herself a number of questions designed to uncover the best available decisions or beliefs)
- Weak sense critical thinking: defend your beliefs, resist & annihilate different opinions and reasoning
- Strong sense critical thinking: evaluate all claims, beliefs, especially your own

<font color = "blue">  Hui: Being critical != 鸡蛋里挑骨头 </font>

- You want to learn from the speaker or writer (需要知识储备: can’t be critical about things you don’t know). 

- Many of your most valuable social interaction or learning experience starts with communication among those with similar value priorities. Our challenge is to understand the reasoning of those have different value priorities.

- Value: importance one assigns to abstract ideas

Value of critical thinker:
    - Autonomy: 兼听则明，偏听则暗
    - Curiosity
    - Humility: We know that we don’t know
    - Respect for good reasoning

Be open: We bring lots of personal baggage to every decision we make—–experiences, dreams, values, training, and cultural habits. Emotional involvement should not be the primary basis for accepting or rejecting a position.

When you argue with someone/are critical, the goal is to learn not to win. You have to be respectful, make certain that your face and body suggest humility rather than the demeanor of a know-it-all.

Argument = conclusion + reason

Attention: the danger of group thinking.

### What are the issue and conclusion?

Getting straight about the person’s conclusion and issue is an essential first step in effective human interaction. Two kinds of issues (it is oversimplified but still helpful): 

1. Descriptive issue: questions about the accuracy of descriptions of the past, present or future 
2. Prescriptive issue: questions about what we should do or what is right or wrong, good or bad (social controversies are often prescriptive issues)

Conclusion: message that the speaker or writer wishes you to accept.

1. When the conclusion is implicit, you need to infer the conclusion from what you believe the author is trying to prove by the set of ideas presented. 
2. When you have figured out the conclusion, use it as the focus of your evaluation.

How to find the conclusion: 

1. Ask what the issue is 
2. Look for indicator words: consequently, suggests that, therefore, thus, it follows that, the point I’m trying to make, shows that, proves that, indicates that, the truth of the matter is 
3. Looking in likely locations: usually beginning and end 
4. Remember what a conclusion is not: examples, statistics, definitions, background information, and evidence 
5. Check the context of the communication and the author’s background 
6. Ask the question “and therefor?” (Conclusions are often implied, ask “and therefore?” to draw it)

### Reasons

Reasons: beliefs, evidence, metaphors, analogies, and other statements offered to support or justify conclusions. You cannot determine the worth of a conclusion until you identify the reasons.

Characteristics of arguments: 

1. They have intent 
2. Their quality varies 
3. They have two essential visible components: Reasons + Conclusion = Argument

**Find the reasons:**

- Ask why. Put yourself in the communicators’ position and ask yourself: “Why am I in favor of this conclusion that I am supporting?” To be fair to the person who made the argument, identify the argument. Then evaluate the reasoning carefully later.

- Words indicating reasons: As a result of, for the reason that, because of that, in view of, is supported by, because the evidence is, studies show

**Kinds of Reasons:**

- Many **reasons** are **statements** that present evidence (specific information to furnish “proof” for something that is claimed to be true).
- Kinds of evidence: research findings, examples from real life, statistics, appeals to experts and authorities, personal testimonials, metaphors, and analogies.
- Keep reasons and conclusions straight:
    1. Circle indicator words
    2. Underline reasons and conclusions
    3. Label reasons and conclusions in the margin
    4. After reading long passages, make a list of reasons at the end of the essay (putting reasons in your own words helps clarify their meaning and function, paraphrase it)

- Reason first and then conclusion (确实，要是认真注意下周围人说话，很多人都是发表成篇的观点，意见，声明，但是没有证据支撑。)

### What words of phrases are ambiguous?

- Locating key terms:
    1. Review the issue for possible terms
    2. Look for crucial words or phrases within the reasons and conclusion
    3. Keep an eye out for abstract words and phrases: more abstract, more likely to be ambiguous
    4. Use reverse role-playing to determine how someone might define certain words and phrases differently: Ask yourself if you were to adopt a position contrary to the author’s, would you choose to define certain terms or phrases differently?

- Ambiguity and loaded language: Different emotional reactions to selected terms and phrases can greatly influence how we respond to arguments. Terms and phrases have both denotative and connotative meanings. The denotative meaning refers to the agreed upon explicit descriptive referents for use of the word. The connotative meaning is the emotional associations that we have to a term of phrase.

- Only the ambiguity in the reasoning is crucial to critical thinkers.

- Meanings usually come in one of the three forms: synonyms, examples, and specific criteria. Synonyms and examples are inadequate when evaluating most controversial issues.

### What are the value and descriptive assumptions?

- The end-product of critical thinking is someone who is open to multiple points of view, assesses those perspectives with reason, and then uses that assessment to make decisions about what to believe and what actions to take.

- Assumptions (unstated ideas) are:
    - hidden or unstated (in most cases)
    - taken for granted
    - influential in determining the conclusion
    - potentially deceptive
    
- An assumption is an unstated belief that supports the explicit reasoning. Look for assumptions needed for the reasons to support the conclusion and look for ones necessary for a reason to be true.

- Value conflicts and assumptions: By value assumption,we mean a taken-for-granted belief about the relative desirability of certain competing value.

- Discovering values: Values are the unstated ideas that people see as worthwhile. It is the importance one assigns to abstract ideas that has the major influence on one’s choices and behavior. Values are standards of conduct that we endorse and expect people to meet.

- From values to value assumptions

A value assumption is an implicit preference for one value over another in a particular context. Unstated assertions about value priorities function as value assumptions. Remember value assumptions are very contextual.

| Typical value conflict             | Sample controversies                                         |
|------------------------------------|--------------------------------------------------------------|
| Loyalty-honesty                    | Should you tell your parents about your sister’s drug habit? |
| Competiiton-cooperation            | Do you support the grading system?                           |
| Freedom of press-national security | Is it wise to hold weekly presidential press conferences?    |
| Equality-individualism             | Are racial quotas for employment fair?                       |
| Order-freedom of speech            | Should we imprison those with radical ideas?                 |
| Security-excitement                | Should you choose a dangerous profession?                    |
| Generosity-material success        | Is it desirable to give financial help to a beggar?          |
| Rationality-spontaneity            | Should you check the odds before placing a bet?              |
| Tradition-novelty                  | Should divorces be easily available?                         |

- Clues for identifying value assumptions:
    1. Investigate the author’s background
    2. Ask “Why do the consequences of the author’s position seem so important to her?”
    3. Search for similar social controversies to find analogous value assumptions
    4. Use reverse role-playing. Take a position opposite the author’s position and identify which values are important to that opposite position.
    5. Look for common value conflicts, such as individual responsibility versus community responsibility

- **Descriptive assumptions**: **beliefs about the way the world is**; prescriptive or value assumptions are beliefs about **how the world should be**.

- Illustrating descriptive assumptions

One important kind of descriptive assumption to look for is a **definitional assumption**——the taking for granted of one meaning for a term that has multiple possible meanings.

1. "On what basis can that conclusion be drawn from that reason?"  
2. "Is there any basis for accepting the assumptions?"

- Clues for discovering descriptive assumptions

1. Keep thinking about the gap between the conclusion and reasons
    - How do you get from the reason to the conclusion?
    - If the reason is true, what else must be true for the conclusion to follow?
    - Supposing the reason(s) were true, is there any way in which the conclusion nevertheless could be false?

2. Look for ideas that support reasons
3. Identify with the opposition
4. Recognize the potential existence of other means of attaining the advantages referred to in the reasons
5. Avoid stating incompletely established reasons as assumptions

### Are there any fallacies in the reasoning?

Refer to Section \@ref(badarguments) and \@ref(artofthinkingclearly).

- Examine the reasoning structure to spot the reasoning fallacies. Three common tricks:
    1. providing reasoning that requires erroneous or incorrect assumptions
    2. distracting us by making information seem relevant to the conclusion when it is not
    3. providing support for the conclusion that depends on the conclusion’s already being true

List of reasoning fallacies

- **Ad hominem**: An attack, or an insult, on the person, rather than directly addressing the person’s reasons.
- **Slippery Slope**: Making the assumption that a proposed step will set off an uncontrollable chain of undesirable events, when procedures exist to prevent such a chain of events.
- **Searching for perfect solution**: Falsely assuming that because part of a problem would remain after a solution is tried, the solution should not be adopted.
- **Equivocation**: A key word or phrase is used with two or more meanings in an argument such that the argument fails to make sense once the shifts in meaning are recognized.
- **Appeal to popularity (Ad populum)**: An attempt to justify a claim by appealing to sentiments that large groups of people have in common; falsely assumes that anything favored by a large group is desirable.
- **Appeal to questionable authority**: Supporting a conclusion by citing an authority who lacks special expertise on the issue at hand.
- **Appeal to Emotions**: The use of emotionally charged language to distract readers and listeners from relevant reasons and evidence. Common emotions appealed to are fear, hope, patriotism, pity and sympathy.
- **Straw person**: Distorting our opponent’s point of view so that it is easy to attack; thus we attach a point of view that does not truly exist.
- **Either-or (False dilemma)**: Assuming only two alternatives when there are more than two.
- **Wishful thinking**: Making the faulty assumption that because we wish X were true or false, then X is indeed true or false.
- **Explaining by naming**: Falsely assuming that because you have provided a name for some vent or behavior, you have also adequately explained the event.
- **Begging the questions**: An argument in which the conclusion is assumed in the reasoning
- **Glittering Generality**: The use of vague emotionally appealing virtue words that dispose us to approve something without closely examine the reasons
- **Red herring**: An irrelevant topic is presented to divert attention from the original issue and help to “win” an argument by shifting attention away from the argument and to another issue. The fallacy sequence in this instance is as follows:
    - Topic A is being discussed;
    - Topic B is introduced as though it is relevant to topic A, but it is not;
    - Topic A is abandoned
- **Fallacies on cause and effect**
    - **Causal oversimplification**: Explaining an event by relying on causal factors that are insufficient to account for the event or by overemphasizing the role of one or more of these factors
    - **Confusion of cause and effect**: Confusing the cause with the effect of an event or failing to recognize that the two events may be influencing each other
    - **Neglect of a common cause**: Failure to recognize that two events may be related because of the effects of a common third factor
    - **Post hoc fallacy**: Assuming that a particular event, B, is caused by another event, A, simply because B follows A in time

- Locating fallacies:
    1. Identify the conclusions and reasons
    2. keep the conclusion in mind and consider reasons that might be relevant to it
    3. contrast these reasons with the author’s reasons
    4. If the conclusion supports an action, determine whether the reason states a specific and/or concrete - advantage or a disadvantage; if not, be wary!
    5. Identify any necessary assumption by asking yourself, “If the reason were true, what would on have to believe for it to logically support the conclusion, and what does one have to believe for the reason to be true?”
    
- Factual claims can be conclusions, reasons or assumptions. Questions to ask:
    1. Why should I believe it?
    2. Does the claim need evidence to support it?
    3. How good is the evidence?
  
- The major difference between claims that are opinions and those that are facts is **the present state of the relevant evidence**

- Sources of evidence:
    - When the claim appears to be undisputed common knowledge
    - When the claim is the conclusion from a well-reasoned argument
    - When the claim is adequately supported by solid evidence in the same communication or by other evidence that we know

### How good is the evidence?

- **Intuition**
    - Be wary
    - No way to judge its dependability
- **Personal experience**
    - **Hasty generalization fallacy**: A person draws a conclusion about a large group based on experiences with only a few members of the group
    - Selectivity: what was the experience like for those whom we have not heard from?
    - Personal interest
    - Omitted information
    - The human factor
- **Appeals to Authority**
    - Keeping alert to authority doesn’t mean that we should doubt everything but to identify better explanations and make better choice
    - When we go online, virtually everyone becomes a potential “authority” because people are free to claim whatever they wish, and there is no built-in process to evaluate each claims
    - Problems with citers citing other citers
- **Clues for evaluation the evidence**
    - Intuition
        - Does the intuition have any other kind of evidential support?
    - Testimony
        - What biases or interests might be affecting the person’s testimony?
        - Does the person have any expertise to assist his or her judgement?
        - How do the person’s value assumptions affect his or her testimony?
        - Whose personal testimony might be helpful in assessing this person’s testimony?
        - What information has been left out in this personal testimony?
    - Authority
        - How much expertise or training does the authority have on this particular subject?
        - Was the authority in a position to have especially good access to pertinent facts?
        - Is there good reason to believe that the authority is relatively free of distorting influences?
        - Has the authority developed a reputation for frequently making dependable claims?
        - Have we been able to rely on this authority in the past?

- **Personal Observation**: Consider observer’s value, raises, attitudes, and expectations
- **Research Study**: attempts to avoid biases
- **Character of scientific method**: reproducible, controllable, precision in language
- **Clues for evaluation research studies**: 
    - Quality of the source of report? Sample? Analytical method?
    - Reproducibility
    - How selective has the communicator been in choosing studies?
    - Is there any reason for someone to have distorted the research? Distortion in surveys?
- **Case examples**
    - Is there counterexample?
    - Are there biases in how the example is reported?
- **Analogy**
    - To evaluate the quality of an analogy
        - The number of ways the two things being compared are similar and different
        - The relevance of the similarities and the differences
        - Generate alternative analogies
    - Faulty Analogy: Occurs when an analogy is proposed in which there are important relevant dissimilarities

### Are there rival cause?

- A rival cause is a plausible alternative explanation that can explain why a certain outcome occurred. You need to look for rival causes when you have good reason to believe that the writer or speaker is using evidence to support a claim about the cause of something.

- When you recognize situations in which rival causes are possible, you want to ask yourself questions like:

1. Can I think of any other way to interpret the evidence?
2. What else might have caused this act or these findings?
3. If I looked at this from another point of view, what might I see as important causes?
4. If this interpretation is incorrect, what other interpretation might make sense?

- We need to remember that any single cause that we identify is much more likely to be a contributory cause than the cause.

###  Are the statistics deceptive?

- Blind yourself to the communicator’s statistics and ask yourself, “What statistical evidence would be helpful in proving her conclusion?” Then, compare the needed statistics to the statistics given.

- examine the author’s statistics very closely while blinding yourself to the conclusion; then ask yourself :”what is the appropriate conclusion to be drawn from those statistics?”

- Deceiving by omitting information
    1. what further information do you need before you can judge the impact of them statistics?
    2. when only absolute numbers are presented, ask whether percentages might help you make a better judgment; when only percentages are presented, ask whether absolute numbers would enrich their meaning
    3. Another important kind of potential missing information is relevant comparisons. It is often useful to ask the question,”As compared to …?"

- Clues for assessing statistics
    1. Try to find out as much as you can about how the statistics were obtained. Ask, “How does the author or speaker know?”
    2. Be curious about the type of average being described
    3. Be alert to users of statistics concluding one thing, but proving another
    4. Blind yourself to the writer’s or speaker’s statistics and compare the needed statistical evidence with the statistics actually provided
    5. From your own conclusion from the statistics. If it doesn’t match the author’s or speaker’s conclusion, then something is probably wrong
    6. Determine what information is missing. Be especially alert for misleading numbers and percentages and for missing comparisons

### What significant information is omitted?

- It’s wise to hesitate and to think about what the author may not have told you. Omitted information is inevitable for at least five reasons.
    1. time and space limitations
    2. limited attention span
    3. inadequacies in human knowledge
    4. deception
    5. existence of different perspectives

- Clues for finding common kinds of significant information

1. Common counterarguments
    - What reasons would someone who disagrees offer
    - Are there research studies that contradict the studies presented
    - Are there missing examples, testimonials, or analogies that support that other side of then argument?
    
2.  Missing definitions
    - How would the arguments differ if key terms were defined in other ways?
    
3. Missing value preferences or perspectives
    - Would different values create a different approach to this issue?
    - What arguments would flow from values different from those of the speaker or writer?
4. Origins of “facts” referred to in the argument
    - What is the source for the “facts”?
    - Are the factual claims supported by competent research or by reliable sources?
5. Details of procedures used for gathering facts
    - How many people completed the questionnaire?
    - How were the survey questions worded?
    - Did respondents have ample opportunity to provide answers different from those reported by the person using the responses?
6. Alternative techniques for gathering or organizing the evidence
    - How might the results from an interview study differ from written questionnaire results?
    - Would a laboratory experiment have created more reliable and informative results?
7. Missing or incomplete figures, graphs, tables or data
    - Would the data look different if it include evidence from earlier or later years?
    - Has the author “stretched” the figure to make the differences look larger?
8. Omitted effects, both positive and negative, and both short and long term, of what is advocated and what is opposed
    - Has the argument left out important positive or negative consequences of a proposed action?
    - Do we need to know the impact of the action on any of the following areas: political, social, economic, biological, spiritual, health or environmental?
9. Context of quotes and testimonials
    - Has a quote or testimonial been taken out of context?
    - Would a different context have stimulated divergent responses?
10. Benefits accusing to the author from convincing others to follow her advice
    - Will the author benefit financially if we adopt her proposed policy?
    - Does the author’s career depend on some manner on a particular conclusion?

### What reasonable conclusions are possible?

- We form different conclusions from reasons because our diverse backgrounds and goals cause us to be attracted to different assumptions when we decide to link reasons to conclusions.

- Dichotomous thinking is the impediment to considering multiple conclusions

- You can always use the when, where, and why questions to help generate alternative conclusions

- Productivity of If-Clauses
    - Each optional conclusion is possible because we are missing certain information, definitions, assumptions, or the frame of reference of the person analyzing the reasons. Consequently, we can create multiple conclusions by the judicious use of if-clauses. In an if-clause, we state a condition that we are assuming in order to enable us to reach a particular conclusion.
    - When reasons in a prescriptive argument are statements of practical problems, look for different solutions to the problems as possible conclusions.
    
- Clues for identifying alternative conclusions
    - Try to identify as many conclusions as possible that would follow from the reasons
    - Use if-clauses to qualify alternative conclusions
    - Reword the issue to “what should we do about Y?”

### Practice and Review

1. What are the issue and the conclusion?
2. What reasonable conclusions are possible?
3. What are the reasons?
4. Which words or phrases are ambiguous?
5. What are the value conflicts and assumptions?
6. What are the descriptive assumptions?
7. Are there any fallacies in the reasoning?
8. How good is the evidence?
9. Are there rival causes?
10. Are the statistics deceptive?
11. What significant information is omitted?

- Strategies for effective critical thinking
    - Be certain to demonstrate that you really want to grasp what is being said. Ask questions that indicate your willingness to grasp and accept new conclusions.
    - Restate what you heard or read and ask whether your understanding of the argument is consistent with what was written or spoken.
    - Voice your critical questions as if you are curious. Nothing is more deadly to the effective use of critical thinking than an attitude of “Aha, I caught you making an error.”
    - Request additional reasons that might enable the person to make a stronger argument than the one originally provided.
    - Work hard to keep the conversation going. If critical thinking is deployed like a bomb, thinking on that topic is halted.
    - Ask the other person for permission to allow you to explore any weaknesses in the reasoning. The idea with this strategy is to encourage the other person to examine the argument with you.
    - Convey the impression that you and the other person are collaborators, working toward the same objective: improved conclusions.

## Innovation

### The Ten Faces of Innovation

是一本关于创新的书，作者叫Tom Kelley，世界著名设计公司IDEO的总经理。这家公司的主营业务就是帮别人设计东西，早期他们最著名的设计产品就是苹果电脑的第一只鼠标，内就是他们设计的，还有世界上第一台笔记本电脑，现在那个原型还摆在纽约现代美术馆里。他们的客户就多了去了，像三星，华为，中国移动，这些全都是他们的客户。这家公司的核心手艺就是创新。

我们以前以为，创新只有等到那么几个英雄一般的人物出现的时候，它才可能发生。而这本给我们的启示是创新不是一两个人的事情，是一个系统性的工程，只有一个公司的文化，环境形成了创新的氛围，每一个员工都发挥出自己的特长，那创新就是一件可以持续发生的事情。创新这个事情是要具体的人去执行的，奇思妙想一点都不缺，真正缺的是把想法落实下去，化为具体行动，最终做成具体产品的人。归根到底所谓的创新，就是人的创新。下面我们就从一个全新的角度去理解什么是创新。

过去我们经常谈论的是创新的模式：

1.开拓性创新，这种模式创造出来的东西是全新的，历史上从来没有见过，都属于从0到1式的创造。

案例：牛顿开创经典物理学，比如哥伦布发现新大陆，比如乔布斯发明的个人电脑

2.升级式创新，对一个新出现的东西进行无限改进。

案例：福特并没有发明汽车，但是他把原来的汽车进行了升级，创造出来的T型车成为了全美国卖的最好的车型，像比尔盖茨并没有发明图形化的操作系统，最早的图形操作系统是施乐公司发现的 ，但是比尔盖茨就是把他优化升级了，然后几乎统治了个人电脑。

3.组合式的创新，就像瑞士军刀一样，把一堆东西设计到一起。这种创新来自创新者对新需求的敏锐观察。

案例：给拖拉机装一门大炮，就变成了坦克， 比如给眼睛装上一台微型电脑，它就变成了谷歌眼镜，再比如给牙刷装上电池和动力设备，就成了电动牙刷。

4.破坏式创新，用一个外行的身份进入一个全新的领域进行破坏式的创新。就是重新制定一个行业的标准，让原来这个领域的人没有竞争力。

案例：当年淘宝和易趣对战，直接免费，让易趣毫无招架之力，一下子就把商户拉过去了。 好的想法一点都不缺，真正缺的是把想法落实下去，化为具体行动，最终做成具体产品的人。归根到底所谓的创新，就是人的创新。

作者把公司的人分成了10个类型，每个类型的人才都是创意的来源。只要一个公司能合理运用这10类人，那么就有可能像IDEO一样把创新能力训练成一项技能，产生源源不断的创意。

这10类人分别是:

- Learning Personas (gather new sources of information):
    - Anthropologist (人类学家)
    - Experimenter (实验家)
    - Cross-pollinator (嫁接员)
- The Organizing Personas (even the best ideas must compete for time, attention, and resources)
    - Hurdler (跨栏高手)
    - Collaborator (合作者)
    - Director (导演)
- The Building Personas (apply insight from the Learning Personas and channel empowerment from the Organizing Personas to make innovation happen)
    - Experience Archtect (用户体验师)
    - Set Designer (布景师)
    - Caregiver (关怀者)
    - Storyteller (和会讲故事的人)
    
1. Anthropologist: Observe, Interact, Look around; maintain a spirit of curiosity

    能通过仔细的观察人的行为，体察人环境的互动，重新定义问题，为后面的解决奠定基础，是不断给公司提出新观点的一类人。他们平时都有一个问题清单，会把所有遇到的不舒服的事情记录下来，哪怕是小到不能再小的一点不舒服，往往就是这些不舒服的地方，就是商机所在。

    案例：在IDEO里就有这么一群人，专门进行前期的调研，他们的方法和其他公司的调研方法不一样，不是填调查问卷，他们需要拍摄一系列的视频。比如如果接到一个医院想要改善医疗环境的任务，这些人就会去病房架起很多摄像头，连续拍摄一个星期左右，然后仔细的去观察这些病房里发生的事情。包括病人的任何不方便的事情，受到的干扰这时候都能在视频里表现出来。有的员工还要假伴病人，专门去医院住上一个星期，经过这么一番深度调查，一些问卷问不到的问题就有暴露出来了。

2. Experimenter: Hard work, Curious Mind; Prototype everything!

    把最原始的那个想法迅速实现的一群人，行动力超强，不怕把第一代的那个很丑的东西拿出来给大家看，肯一次一次尝试失败，不断迭代的一群人。

    案例：吸尘器的发明经历过5000次的失败。

3. Cross-pollinator: Draw associations, Make connections; Wide sets of interests and avid curiosity, Bring seemingly unrelated ideas together
    
    融会贯通的能力特别强，很容易把一个领域的技术和模式套到另外一个领域里。他们的能力是能迅速在陌生的领域发现新奇的元素，然后把它移植到自己的项目上。

    案例：现在大家都在用的键盘，其实他最早的模型是钢琴；比如每栋大楼里的电梯，他最早的创意来源是游乐场的升降梯；再比如吉列在剃须刀领域发明了“刀架”加“刀片”的营销模式，这样本来重复购买率很低的刀架就以很低的利润卖出去，这样可以迅速占领市场，最后通过卖刀片来赚钱，这个模式就被嫁接到亚马逊的kindle模式上了，亚马逊通过卖几乎没有什么利润的kindle阅读器来占领市场，最后通过卖电子书赚钱。IDEO放着不同领域的书。

4. Hurdler: Tireless Problem-Solver, Optimist, Quiet determination, perseverance, see beyond initial failures

    不惧困难，为了达到目的尝试各种方法。以目的为导向。毅力，耐心，随机应变的能力。遇到问题只想到解决，不会犹豫害怕。

5. Collaborator: The team over the individual, shared journey, more of a coach than a boss, multidisciplinary team

    善于沟通，就像一个团队里的粘合剂一样，让一个团队的信息共享，高度的协作，是创新过程中不可或缺的一个重要角色。

6. Director: big picture thinking, bring out the best in team members, give center stage to others

    负责幕后的运筹帷幄，统揽全局，导演的位置通常是CEO。在IDEO里面是不太关注这些头衔的，很多员工其实也是担任的导演的角色。

7. Experience Architect: fend off the ordinary wherever you find it, facilitate positive encounters with your products, services, organizations, spaces and events

    善于抓住人最细微的心理活动，就是能找到一个产品或是一个服务升级点。

8. Set Designer: liven up the workspace, promote energetic, inspired culture

    专门给公司创造良好的创意氛围。好的装修风格不仅可以给员工带来归属感，还能带来源源不断的创造力。

    案例：皮克斯公司，谷歌公司的装修风格就像幼儿园一样，到处都是不拘一格的装饰物，这些装饰的做用就是可以不断的暗示员工，这里需要创意，这里需要奇思妙想。又比如一家知识服务公司，一定是到处都是书，一家动漫公司，一定是到处都是动漫玩偶。

9. Caregiver: the foundation of human-powered innovation, empathy for individuals, create relationships
    
    如销售人员、客服，他们能从顾客那里拿到最真实的反馈信息，往往是一个公司和顾客的触点。

10. Storyteller: capture imagination with a story, spark emotion and action, video, narrative, animation, even comic strips

    能调动大家注意力，他们就是公司文化传播的布道者。

总结：

这本书从人的角度讨论了创新这件事，给我们列出了10种推动创新的人才，一个人实际上是可以充当多个角色的，也可以在多个角色当中来回切换。所以创新是一个团队的事情，是一项系统工程，每个人都做最好的自己，创新才能持续不断的发生。 本书给我们的启示是创新不是一两个人的事情，是一个系统性的工程，只有一个公司的文化，环境形成了创新的氛围，每一个员工都发挥出自己的特长，那创新就是一件可以持续发生的事情。

## Emotion Management

### How To Keep People From Pushing Your Buttons

> About the author: Albert Ellis(1913-2007) held M.A and Ph.D. degrees in Clinical Psychology from Columbia University. He was the founder of Rational Emotive Behavior Therapy (REBT), the pioneering form of the modern Cognitive Behavior therapies. He was the president of the Albert Ellis Institute in New York, where he practiced individual and group psychotherapy, supervised and trained psychotherapists, and presented many talks and workshops at the Institute and throughout the world. He published over seven hundred articles and more than sixty books on psychotherapy, marital and family therapy, and sex therapy.

Ellis的童年并不幸福，他的父母对孩子们感情冷漠，父亲常年在外经商，母亲“喋喋不 休，但从不倾听”，在他12岁时，父母离婚了。Ellis的梦想是当个作家，但成为作家前，需 要一份养家糊口的职业。他本想做个会计师，结果赶上大萧条。好在，他找到了另一个人生理想–心理咨询与治疗。

Ellis列出了四种不好的过激情绪：

1. 过分的烦躁（紧张、沮丧、恼火、担惊受 怕）；比如你为准备一个工作面试而紧张，为孩子最近的表现而烦躁。
2. 过分生气（戒备、被激怒，气得发疯，挫 败）：当你的配偶批评你不干活，当工作上的同事不配合或做不来时。
3. 过分抑郁（无精打采，一蹶不振）：失去所爰的人，或失去工作。
4. 过分内疚（过分承担责任，过分悔恨，过分自责）：比如你因为离婚而对孩子内疚，处处宠溺。

- 如何判断过分？其实人们在85%的时间里，是能识别出自己什么时候反应过激。而你要做的就是让尽可能多的过激反应不要发生。

- 你的坏情绪是怎么来的？人不是天生就有坏情绪的，Ellis给出了诱因ABC公式。
    - A代表曰常遇见的人或事情。除了那些重大的事件外，A就是那些烦人的小事，比如难缠的 上司、同事，办公室的勾心斗角，沟通不够；
    - 生活中与配偶或情人的冲突，家务劳动，财务 问题。
    - C代表在A的情形下你的感觉和行为。如果你有一个重要的会议，但路上大堵车，这时你就会从平时的绅士变成路怒一族，不断并线加塞，嘴里骂骂咧咧。那么真的是堵车导致了你这样的路怒行为了吗？不是的，在A和C之间，有一个B
    - B就是我们对具体发生的人或 事的思考、判断。

- **三类病态的思维模式**导致情绪和行为反应过激

1. 恐怖化的思维方式。把什么都看成了灾难，非常害怕，思维模式就是“万一……怎么 办”？比如你去面试一份工作，你可能会想 到：万一我回答不上问题怎么办？万一他们不 喜欢我怎么办？万一我被人难堪了怎么办？越想越多，就越恐慌，你高度紧张，未战而败。

2. 应该化的思维方式。“我必须……”，“我一定……”，这种“必须”、“应该”的思维可能源自孩提时代，父母说：你应该对弟弟好一点；老师说：你应该五讲四美。一旦有了 “应该”的思维，就会使你对自己要求过于严苛，把自己弄得很惨。当你达到了我应该“的标准时，你就开始了对别人的”你应该”。

3. 合理化的思维方式。这种思维就是认为什么都很合理，不可思议地将不道德或不得体的 行为合理化，骗自己接受这种行为，简单地说 就是逆来顺受。典型的表现就是：谁会关心？ 那又怎样？这种思维方式会把很多不合理的事情也认为是合理的，合理化思维是一种软弱的应对方式。

你如果老是用恐怖化、应该化、合理化去思考 问题的话，就会陷入以下10种非理性人生信条：

**信条1:太在乎别人怎么看待你。**因为太在乎 会导致你对拒绝的强烈的恐惧感，要么你会四处讨好别人，避免冲突；要么你就把自己装扮 成一只刺猬，逮谁扎谁。其实你更好的选择可以是这样的：“我希望你们喜欢我，尊重我， 你们要是做不到，我也能忍受”。（恐怖化）

**信条2:无法忍受在重要任务上失败。**如果你让自己相信在任何重大事件上都输不起，你就 不敢冒险，会墨守成规。还有就是无法忍受别人的批评。（恐怖化）

**信条3:人和事都应该朝着我要的方向发展。**这是由于低耐挫性和对不公平的敏感而造成的 冲动反应，会导致半途而废，逃避责任。（应该化）

**信条4:某件事出错了，肯定是有人出了问题。**凡事绝对化，认为事情做得那么糟，肯定 是有人不尽力，这些人善于把脏水往别人身上泼。（应该化）

**信条5:对即将发生的事情总是抱着深深的忧虑。**（恐怖化）

**信条6:每个问题都有完美的解决方案，我必须立即找到这些方法。**有时候完美主义造就了拖延症。（应该化）

**信条7:在很多困境和责任面前可以让自己置身事外，凡事都能找到一个合理化的理由。** (合理化）

**信条8:如果事事不投入，保持若即脱离的关注，会永远开心。很多人貌似参与了很多事， 但其实他们只是坐在那儿，被动地观察。**（合理化）

**信条9:因为过去或者小时候发生的一些不好的事情造成了我现在这个样子，我努力也改变不了。**（合理化）

**信条10:这些坏人坏事就不应该存在，真不知道拿他们怎么办。他人他事会逼得你反应过激。**（应该化）

- 怎样应对病态的思维方式？

把事情恐怖化、应该化和合理化是三大逼迫我们就范的方式，要我们不去这么想的方法就是 第四种思考模式：你要看看在这三种思维模式 之外有什么是更好的选择，比如“我想 要……，”“我更喜欢……”，“如果……就更好了”。它不是必须时刻要积极，并不表明你能够或一定成功，而是说要去试一试，即使可能会失败、被拒绝。

> 比如你是个演讲新手，但最近你有一场重要的演讲，你很可能会把前面三类病态思维都用一 下：“万一我搞砸了，没人听，大家聊天会怎么办？（恐怖化）我应该能够做好公共演讲， 我用不着害怕。（应该化）其实，这有多大的事，就是搞砸了也没人在乎。（合理化）”但如果你能更好的选择思维方式：嗯，我想要做好演讲，但也不是非做好不可，现在还有一点时间，我可以在脑子里再过一次提纲；其实我更喜欢演讲的过程，我想我肯定能从中学到什么。这样你就不会背负心理包袱。

- 如何让“更好的选择”成为习惯？

改变想法需要觉悟，还有需要用大量的练习建 立起第四种思维模式的习惯“更好的选择”。 
有四个步骤：

1. 反思自己的C (感觉和行为）：我的感觉和行为是不是合适？
2. 认真审视自己的B是怎么把自己弄成了C的样子（过分的焦虑、愤怒、抑郁、内疚）
3. 如何反击和对抗自己的非理性思考方式
4. 用什么样的更好选择来替代非理性思维

> 用“我想要……”，“我喜欢……”，“如果……就更好了”

### Feeling Good: The New Mood Therapy

> David D. Burns (born September 19, 1942) is an adjunct professor emeritus in the Department of Psychiatry and Behavioral Sciences at the Stanford University School of Medicine and the author of the best-selling books Feeling Good: The New Mood Therapy and The Feeling Good Handbook. Burns popularized Aaron T. Beck’s cognitive behavioral therapy (CBT) when his book became a best seller during the 1980s.

帮助人们预防和克服包括抑郁在内的多种负面情绪，树立积极乐观的生活态度。

一、我们为什么不开心：引起我们消极情绪的根源是我们的想法而非事情本身

我们的消极想法通常是没有任何事实根据的，只是臆想而已，而我们所产生的抑郁情绪，表面上是由于消极事件，实际上却是因为我们自己扭曲的认知和不合逻辑的想法导致的。

二、引发消极情绪的认知扭曲

(1) 乱贴标签：陷入这种思维的人，会给自己制定一个完全负面的错误评价，而实际情况其实并没有那么糟糕。

(2) 非此即彼：观点过于偏激、绝对，非黑即白。

(3) 放大：夸张地将生活中的不如意不合比例地放大。

(4) 心理过滤：习惯用心理过滤的思路来看事情的人们一般都有这样一个共同点，那就是只看见坏的，看不见好的。

(5) 以偏概全：俗语“一朝被蛇咬，十年怕井绳”，就是以偏概全的典型例子。有过一次被人欺骗的经历，就认定所有人都是骗子，否定了一切幸福的可能，这样的想法是很幼稚的。

<font color = "blue"> Hui: 这个和（3放大）重复了</font>

(6) 妄下结论：我们每个人都或多或少做过妄下结论这种事。

(7) 否定正面思考：这种人会收集一切证据来证明自己以及自己的处境很糟糕。

(8) 情绪化推理：被不开心的情绪牵着鼻子走。

(9) “应该”句式：指的就是“我应该怎么怎么样”的想法。很多对自己有要求的人常常会这样激励自己，然而实际上，这种想法只会让人感到深深的压力、烦恼和焦虑。

(10) 罪责归己：这种人恨不得包揽掉全世界的错误，只要有不好的事情发生，就会条件反射般认为是自己的责任，继而陷入深深的内疚和自责中无法自拔。

三、如何战胜拖延症

(1) 制作每日活动计划表

安排好每天、每小时计划做什么事情，并记录下来实际完成情况。这个计划表的目的不是在于督促人们一定要完成上面的每一项内容，而是帮助人们对比计划与实际，搞清楚自己的时间究竟花在了哪些事情上。

<font color = "blue"> Hui: 很难实践，太花时间，而且计划常常变会更加焦虑。</font>


(2) 制作反拖延症表

把手边较为复杂、迟迟不愿开始的活动分解成几个小步骤，比如，把做一场关于环保的演讲分解成查找相关资料、列出演讲提纲、写初稿、修改、定稿、练习演讲技巧等等一系列步骤，然后再针对每一项步骤，预估出它的难度和自己的完成度，可以用十分制来打分，等到具体实行时，每完成一项步骤，就给它的实际难度以及你的完成度打一个分。这样一来，等到将整个任务完成复盘时就会发现，每一个步骤的实际难度指数往往都远低于自己的预判，而实际完成情况也往往比想象中好得多。

<font color = "blue"> Hui: 这个也很困难，因为预估难度并不容易，而且很多时候不是任务分解了就会去做。</font>

四、如何不生气

重新调整在人际交往时抱有的心理预期。归根到底，所有的愤怒都是源于别人的行为和想法达不到自己心里的设想，人们感到失望，才因此而愤怒。

五、如何应对抑郁情绪

伯恩斯认为，引起抑郁情绪的原因主要有四个：（1）对他人的认同上瘾；（2）对他人的爱上瘾；（3）以成就论价值；（4）以及追求完美。

其中，认同上瘾是最为常见的。对认同上瘾的人，很容易受到外界因素的影响：在获得他人表扬和认可时，往往会非常振奋开心，充满干劲，然而只要受到几句否定和批评，便会怀疑人生，心灰意冷，陷入抑郁情绪。

认同上瘾导致抑郁的一个最为常见的例子，就是表白被拒绝之后的沮丧失落。被人拒绝后，首先要认清一个事实，那就是“各花入各眼”——有的人喜欢吃香蕉不喜欢吃苹果，并不是因为苹果哪里不好，只是每个人的口味不同罢了。如果这时依然觉得被人拒绝这件事情很难以接受，也千万不要成天深陷其中，而是应该允许自己适度悲伤——每天划出特定的十分钟，专门用来释放痛苦的回忆和想法，会有效帮助走出被拒绝的阴霾。

### Emotional First Aid

> Dr. Guy Winch is a licensed psychologist, author, and in-demand keynote speaker whose books have been translated into 24 languages. His first TED Talk, Why We All Need to Practice Emotional First Aid has been viewed over 5 million times and is rated as the #5 most inspiring TED Talk of all time on ted.com He also writes the popular Squeaky Wheel Blog on Psychology Today.com (https://www.psychologytoday.com/blog/the-squeaky-wheel) and he has dabbled in stnad-up comedy. His website is www.guywinch.com. You can view his TED Talks here: https://www.ted.com/speakers/guy_winch

Healing Rejection, Guilt, Failure, and Other Everyday Hurts

心理伤害的“七宗罪”

1. 拒绝：日常生活的摩擦伤害
2. 孤独：人际关系的“肌无力”
3. 丧失与精神创伤：心理的伤口
4. 内疚：情感体系的毒药
5. 反刍：重新揭开结痂的伤疤
6. 失败：情绪“感冒”如何发展为心理“肺炎”
7. 自卑：削弱你的情感免疫系统

1. Rejection：the emotional cuts and scrapes of daily life
2. Loneliness: Relationship muscle weakness
3. Loss and Trauma: walking on broken bones
4. Guilt: the poison in our system
5. Rumination: picking at emotional scabs
6. Failure: how emotional chest colds become psychological pneumonias
7. Low self-esteem: weak emotional immune systems

1. 拒绝造成的伤害 

    在所有情感创伤里，拒绝也许是最常见的一种。拒绝会导致4种不同的心理创伤：    
    A.被拒绝的人拒绝理性。   
    B.产生愤怒和攻击性。  
    C.伤害我们的自尊。  
    D.令我们找不到归属感。  

2. 拒绝的四种疗法：   

    A.与自我批判争辩   
    
    列出你对被拒绝产生的各种消极或自我批判的想法。针对不同的情境，驳倒你列出的想法。试试对恋爱、职场、社交中遭遇的拒绝进行反驳。  
    
    B.恢复自我价值   
    
    修补自信和恢复自我价值的最佳途径，就是提醒自己性格中那些有价值或让人满意的方面。列出一个清单，写出你认为自己最有价值的五个特质，针对每个特质写篇短文。  
    
    C.修补社交感受   
    
    当我们经历排斥和拒绝时，社交支持变得更加重要。有时候仅仅是和那些合得来的人在一起，就算很少说话，我们也会体验到一种强大的社会联系感。   
    
    D.自我脱敏   
    
    如果一个演员很少试镜，被拒绝后可能会很痛苦，但那些每周都试镜的人，会很容易接受这种拒绝。这就是脱敏。这个方法适合针对约会，交新朋友，申请工作，推销等。只有在你觉得你的自尊可以忍受多次轻微拒绝时才能使用。

3. 孤独造成的伤害

    决定我们是否孤独的因素并非人际关系的数量，而是它的主观质量。   
    A.长期孤独容易导致抑郁症、自杀倾向和敌意与失眠。  
    B.孤独对身体健康也有破坏效果，容易导致心血管系统疾病、内分泌系统疾病以及阿尔茨海默症。孤独对身体的伤害不亚于香烟。  
    C.孤独让我们对自己和他人产生不准确的看法，也会导致我们进入自我保护和回避他人的循环，推开那些想要帮助我们的人。  
    D.长期的孤独会导致我们社交能力的肌无力，既无法体会别人的感受，也无法寻求别人的帮助。  


4. 孤独的治疗

    A.摘掉有色眼镜。   
    
    把别人想象得好一点，不要胡乱猜疑，减少推理对自己的伤害。主动联系那些给你感觉良好的人。   
    
    B.找出你的自我拆台行为。  
    
    我们经常用自己的行动去证明自己错误的观点，不愿意面对现实。比如：勉强找个借口避免参加聚会，不重视向别人传达祝福和庆贺，假装看手机，回答别人的问题太粗鲁简短，约会时对别人不提任何问题。一旦找到自我拆台行为，就要提醒自己下次社交时避免类似行为的发生。 
    
    C.学会换位思考。   
    
    在讲笑话的时候考虑是否会伤人，在发送短信的时候想想要不要加上表情符号，以免对方误解。 越是亲密的人越容易出现缺乏换位思考的问题。通过换位思考深化你的情感联系。假设自己处于他们的情况，不是只想象一两秒钟，而是要完全进入对方的感受。  
    
    D.为社交设定一个额外的目标。  
    
    比如为了研究而参与相亲活动，要进行铁人三项赛所以参与跑步，为了摄影参加旅行团等。还可以努力成为帮助别人的志愿者，这也为你的社交创造了新的意义。   
    
    E.收养小动物。   
    
    研究表明，那些单独和狗在一起的人，比那些和其他人分享一只狗的人明显不孤独。

5. 丧失与精神创伤

    失去所爱的人，成为暴力犯罪的受害者，成为残疾人，患上严重疾病，都会破坏我们的生活。更常见的是失业、与朋友翻脸、父母或祖父母去世等。丧失主要造成四种伤口：  
    A.生活被打断。   
    
    我们可能失去思考甚至自我照顾的基本能力，淹没在情绪痛苦之中。失去某人后的第一顿饭，被暴力犯罪后的第一个晚上，手术后第一次照镜子……我们的生活在这里中断了。 
    
    B.身份被改变。   
    
    车祸、失业、离婚、失去亲人，这些事都需要我们重新定义自己。如果做不到这一点，我们的人生只能留下可怕的空白。   
    
    C.信念被切断。   
    
    失去的震惊之余，我们心中充斥着疑问和困惑，会怀疑以往的价值观。通常人们会在六个月以后建立新的价值观，接受事实。但也有人一辈子做不到。   
    
    D.人际被断开。   
    
    人们会觉得如果和别人联系或开心的生活是对失去亲人的背叛，所以会主动减少和他人的联系。

6. 治疗丧失的方法

    A.以你的方式舒缓情绪上的痛苦。 
    
    有时把创伤的细节谈出来对我们有帮助，但有时候过早的谈论细节会造成更大的伤害。我们能够做到最佳的处理方式，就是根据个人的倾向、个性和世界观进行治疗。愿意谈就谈，不愿意也不要逼迫自己。无论哪种方式，最有效的，永远是时间。   
    
    B.恢复你迷失的自我。  
    
    列出事件发生之前，你自己或者别人认为你有价值的品质、特点和能力（至少10项）。针对每项，写一小段话，说明你现在为什么失去了这项品质，以及你可以通过哪些人、活动或方式来恢复它们。   
    
    C.寻找悲剧的意义。   
    
    寻找丧失和创伤的意义，对于治疗创伤至关重要。但要在你觉得自己可以管理情绪引起的疼痛和不适时才能使用这个疗法。

7. 内疚造成的伤害

    人每天约有两小时感觉轻微内疚，每个月约有3.5小时感觉严重内疚。内疚感有很多益处，但较大剂量的内疚就会成为毒素。三种内疚伤害最大：未解决的内疚；幸存者内疚；分离的内疚。
    
    - 内疚会造成自我谴责，让我们无法体会喜悦和幸福感。 
    - 内疚会阻碍健康的人际关系，妨碍沟通。越是亲密的关系越容易引发愧疚。

8. 内疚的治疗方法

    A.掌握有效道歉的秘诀。 
    
    有效道歉的配方包括：对发生的事表示遗憾；明确说对不起；请求原谅；肯定对方的感受；提供补偿或赎罪；承认你违反了社会规范或者期望。在确定准备好以上六项材料后，找个好机会真诚道歉。并以实际行动取得对方的谅解。   
    
    B.自我原谅。   
    
    有时被道歉的人已经找不到，或就是不接受道歉，这时我们缓解痛苦的唯一方式就是原谅自己。但如果太容易原谅自己，可能无法改过自新。因此首先要对自己的行为承担全部责任，诚实面对自己的错误。在这个基础上再进行第二个步骤：赎罪。   
    
    C.重新投入生活。   
    
    当你没有必须承担的责任时，内疚更难治疗。比如幸存者内疚或分离内疚。这时你需要以书面的方式写下有助于祛除内疚的想法。

9. 反刍造成的心理伤害

在遭遇了痛苦时，有人会陷入反刍的恶性循环中。痛苦的场景、记忆和感觉一遍遍重放，每次都令我们感觉更糟。   

- 反刍增加了我们变的沮丧的可能性，并延长抑郁发作的持续时间。 
- 提高了酗酒和饮食失调的风险，让我们产生负面思想，阻碍问题的解决。 
- 增加心理和生理应激反应，提升心血管疾病风险。

10. 反刍治疗失败的原因

    很多治疗失败的原因是医生们相信把痛苦说出来会好。但当我们一遍遍谈论自己的痛苦时，会让心情变得更糟。具体伤害体现在：加剧痛苦；让愤怒膨胀；会变得麻木和反应迟钝；加剧紧张关系。

11. 反刍的治疗方法

    A.改变视角: 当人们从自我疏远的角度（像看电影一样）看他们的痛苦经历时，更能够提供新的观点重新解读事件。   
    
    B.分散注意力: 试试有氧运动、社交、拼图、电脑游戏这些分散注意力的方法。
    
    C.愤怒重构: 最有效的情绪调节策略是重构我们的情绪：找出积极意图；确定机会；拥抱学习时刻；将冒犯我们的人视为需要精神帮助者。   
    
    D.善待你的朋友: 问问自己，这件事过去多久了？你和别人讨论过多少次这件事？朋友是否愿意讲讲他自己的问题和困难？在和对方交流中，关于你的问题所占比例是多少？
    
    反刍常常会是抑郁症和强迫症的症状，所以当你自己无法处理时，一定要找专业医生帮助。
    
12. 失败的心理伤害

    失败就像感冒，非常频繁地发生。主要的伤害有：   
    - 自尊受挫。 
    - 让我们感到被动与无奈。 
    - 引发更多焦虑和恐惧。 
    - 对失败的过度反应会投射在孩子身上。

13. 失败的治疗方法

    获得支持: 在痛苦的失败之后，除了获得情感支持，我们还要客观评估失败的经验和教训。如果没有后者，仅仅是情感认同，会起到反作用。 
    
    专注于你能控制的因素: 制定现实而具体的目标；将大目标分解为小目标；为目标设定时间框架；列出可能的挫折原因，并制定解决方案。优先做那些在你控制范围内的事。  
    
    承担责任，承认恐惧: 承认失败通常会唤起一定程度的恐惧和焦虑，这时最好承认它们，从而防止它们不自觉地影响我们的行为。承认这种感觉的最佳方式就是和支持我们的人谈论它们。或者写在日记里。  
    
    从压力中分散自己注意力: 哼歌和吹口哨的确可以驱散焦虑情绪，考试时自言自语也是不错的方法。在紧张的时候写一段小文字肯定一下自己的优点可以有效消除过大的压力。

14. 自卑会伤害你的情感免疫系统

    人们经常在自卑和自恋间徘徊。科学家发现，就自尊程度而言，处于平均值是最好的。自卑可以造成三种类型的心理创伤：
    
    A. 使我们更加脆弱。
    
    B. 让我们抵制正面的反馈和情感滋养。
    
    C. 让我们更容易放弃对合理权力的争取。

15. 自卑的治疗方案

    压制脑中自我批评的声音: 我们对待自己往往比对待别人更苛刻，但实际上，自我同情能够更好地建设我们的情感免疫系统。
    
    具体步骤：写下一件令你自卑的事；想象一下这件事发生在朋友身上，他很难过；你决定给他写一封信安慰他；现在重新看待这件事。
    
    找出并肯定自己的长处: 找两张白纸，在一张纸上写下你的重要特质和才能（至少10项）。如果这时冒出了消极评价，就写在另一张纸上。从第一张纸选出特别有意义的项目，写一篇短文。写完后，把第二张纸揉成球，扔进垃圾桶。
    
    提升对赞扬的宽容度: 当别人赞扬你时，只需要微笑说：谢谢！没事时回想你的伴侣、家人或朋友对你表达欣赏或喜欢的场景。
    
    提升个人力量: 通过在生活中的某个领域表现出自信，从而可以像滚雪球一样迅速积累个人力量。从可控的范围内开始，制定改变的计划，一件一件开始实施。
    
    提高自我控制的能力: 运用正念的方法观想各种冲动和渴望。提高了自我控制力的时候，能够有效提升自尊感。使用此方法时，要保证体力充沛和体内的葡萄糖含量。

你可能不会同时有以上七个问题需要解决，但也很难一个问题也没有。建议针对自己最需解决的问题尝试相应的方法。

### The Emotional Life of Your Brain

> Richard J. Davidson & Sharon Begley (Contributor)

> Why are some people so quick to recover from setbacks? Why are some so attuned to others that they seem psychic? Why are some people always up and others always down? Richard J. Davidson discovered that each of us has an Emotional Style, composed of Resilience, Outlook, Social Intuition, Self-Awareness, Sensitivity to Context, and Attention. Where we fall on these six continuums determines our own “emotional fingerprint.” The book shows how you can change them.

一、找出自己的情绪风格 情绪风格，指的是情绪反应在类型、强度和持续时间上的差异。

情绪风格是怎样被发现的 经过大量的研究实验，作者终于发现了积极情绪和消极情绪的大脑机制，这一发现宣告了情绪神经科学这门新学科的诞生。作者在对情绪的神经基础进行了系统研究之后发现，人们对各种生活经验的反应可能有很大的差异，这些差异的根源就在于不同的大脑活动模式，情绪风格的思想就在这个时候诞生了。

情绪的六个维度

（1）Resilience：在面对困境时，你是会陷入崩溃境地还是百折不挠、抗争到底？在遭遇打击时，是束手就擒还是激流勇进？情绪调整分为迅速恢复和缓慢恢复。 

（2）Outlook：面对生活的态度是乐观还是悲观，也就是积极思维还是消极思维。 

（3）Social Intuition：指的是你是否能清楚地读懂别人的心理状态或情绪状态，分为社交直觉敏锐和社交直觉迟钝。

（4）Self-Awareness: 这指的是对内在的自我是不是有清楚的了解，分为自我觉察能力敏锐和自我觉察能力迟钝。 

（5）Sensitivity to Context：指的是能否区分不同社交场合的交往习惯和规矩，分为情境敏感和情境迟钝。 

（6）Attention：指的是能否排除情绪等因素的干扰，保持注意力集中，分为注意力集中和注意力分散。

不同的人有不同的情绪风格，你身上这六种成分的不同含量，决定了你是什么情绪风格。情绪风格可以千变万化，就像指纹和面孔一样，每个人都是独一无二的。

二、情绪风格如何影响你的生活

经过对哮喘病人的研究发现，压力可以让身体对过敏原的生理反应出现显著恶化。最敏感的哮喘患者在情绪调整这个维度上，靠近缓慢恢复这个水平，而自我觉察能力下降对哮喘患者有好处。 大量的实验证明，积极情绪在很大程度上会对健康产生好的影响。具体说就是积极情绪能够直接作用于生理机能，抑制心血管系统、神经内分泌系统或者荷尔蒙系统，还能够提高生长激素、催乳素和催产素的水平，能够更有效地抗击感染，降低血压，所以，情绪风格不仅会影响你的生理系统，进而还能决定你的健康。

值得注意的是，不存在理想的情绪风格，不需要刻意把自己变成某一种所谓理想型情绪风格的人。不过有时候一个人的情绪风格可能会过于极端，甚至影响了正常生活，这就进入了病态的范畴，就需要改变和调整了。

三、情绪风格是可以改变的

研究人员发现，先天视觉障碍的人在学习了用手触摸的盲文之后，他们大脑中的运动皮质和躯体感觉皮质都产生了变化，面积和活跃程度都有所增加。更让人惊讶的是，他们大脑中的视觉皮质干脆转行了，开始处理从手指传来的触觉信号，而不是眼睛发出的视觉信号了。由此可见，有视觉障碍的人听觉特别灵敏，有听觉障碍的人眼睛特别敏锐，这种补偿性变化不是没有道理的，感觉经验能够让大脑重新分区。也就是说，大自然赋予了人类大脑一种灵活性，使得人脑能够不断调整，适应周围世界的需求，大脑并不是静态的，而是可以发生改变的，具有可塑性。 纯粹的意念也可以给大脑带来根本上的改变，书中介绍了一个虚拟钢琴学习的例子。

每一种情绪维度，都对应一种特定的大脑活动模式。脑成像技术证明，情绪维度其实是皮质和边缘系统等区域中可以度量的生物活动。也就是说，情绪风格是所有大脑机能的产物，这些大脑机能包括联系、回路、结构上或功能上的关系以及神经化学机制。既然大脑可以发生变化，那么，情绪风格也是可以改变的。

四、如何改变情绪风格

- 认知行为疗法

它其实就是一种心理训练，在20世纪60年代被提出。这种疗法的目的，是让患者学会更加健康地对自己的情绪、思想和行为做出反应。认知行为疗法引导患者反思自己错误的思维方式，让他们意识到导致自己出现心理障碍的是思维方式，摆脱错误的思维方式就可以使自己解脱。如果你的自我觉察能力过于敏锐，以至于出现了疑病症、恐慌症、强迫症，你就可以尝试使用这种方法予以矫正，长期坚持，不仅可以治愈，而且不会复发。

- 禅修

正念禅修是抑制杏仁核和眶额皮质活动的有效方法。这种练习要求你不予评判地观察自己每一个当下的念头、心情和感觉，如实地观察它们的本来面目，不加任何的扭曲和简化。

- 改变环境

你也可以通过外部也就是重新安排自己的周围环境，来实现对情绪风格的改变。人有一部分天生的性格特征是由基因决定的，大概占到全部性格特征的一半左右，但基因本身并不足以让某一种性格特质显现出来，基因还需要被开启。研究表明，生活经验可以让基因开启或者关闭，基因的表达程度受到环境很大的影响。如果生活环境保持稳定，你的气质和情绪风格也同样会保持稳定，反之则相反。

## Negotiation

### 谈判思考的技术 {#negociation1}

《谈判思考的技术》是泷本哲史的超高人气课程“谈判论”的精华内容，通过“谈判思考六堂课” 实战练习，传授年轻人职场成功必备武器，是一门实用的学问。以独特的切入点，立足于培养谈判“思考方法”,实操性强，迅速扭转时下年轻人的思维方式，新时势及新经济模式下的职场生存指南。

一、为什么大家要学习“谈判”？

1. 谈判是一种人与人之间最常见的交流方式，并且在这个时代，由上至下的命令模式开始瓦解，组织内部、机构之间一般来说是平等自由的关系，谈判成了信息传达与反馈最常用的模式。
2. 年轻人要学会通过谈判来达成目标，而不是像小孩撒娇一样地索取。
3. 为了同一目标，要准备好“与自己水火不容的人”并肩作战，谈判就是达成目标的必要手段。
4. 未来，计算机能代替人类大量的工作，只有“伴随着谈判的工作”能够幸存下来，所以学会谈判非常重要，这项能力可以让你免于被人工智能所替代。

二、谈判中如何打动对方？将对方的“利害”作为思考的焦点

谈判是几方共同决策，讨论投入分配和利益分配的过程，所以，不能忽视，对方也同样拥有决策权。

谈判误区一：让对方理解自己的立场很重要。这是错误的。你理解对方的利害关系更重要。不要表现出自己很可怜或者自己的立场有多正确，而应该着重向对方说明，你的提议对他很有利。
  
谈判误区二：谈判意味着抢夺。这是错误的。当你重新衡量自己和对方的目标，就会发现事情并不一定是这样的。
  
谈判误区三：在谈判中得到的越多越好。这是错误的。谈判不是零和博弈，只是取几方都满意的中间值。所以一味贪多，可能反而会破坏谈判。 “BATNA”是最强大的武器

1. BATNA (Best Alternative to a Negotiated Agreement)分析法是助你谈判成功最重要的武器。
2. 拥有备选项之后再去谈判，这是对自己最有利的。如何才能成功涨薪？是得到别的公司的offer之后。
3. 谈判的胜负取决于你所收集到的信息量。谈判，80%取决于事先的准备，大部分是对BATNA的准备。

三、“锚定术”和“让步”

1. “锚定术”指设立谈判的起始条件。即便是谈判高手，也难免会受锚定基点影响，所以在一开始尽量向对方提出一个苛刻的条件。
2. “让步”的策略是：（1）绝不能做出无条件让步（2）做出让步的条件必须是对自己价值很小，对对方价值很大的。
3. 对方做出的让步，不要急于接受，不动声色是最好的回应。
4. 对谈判过程中的主要争论点进行梳理，避免让思维陷入“二选一”的模式，按重要性的高、中、低定义自己和对方的关切点，看是否有让步的可能。
5. 注意谈判对手背后的人物，他们往往是真正的老板。


四、搞定“非理性的人”

1. 追求“价值上的理解和共鸣”的人。试图与对方的价值观产生共鸣，再考虑利益。
2. 重视“信任感”的人。五种方法建立信任感。
3. 拘泥于“自我主张”的人。不要为对方分析利弊，提供相关的材料，让他自己做出判断。
4. 看重“自我重要程度”的人。哪怕再无理，也要相信他们的话背后有鲜为人知的原因。提高反馈速度，用行动让对方感觉受到重视。
5. “等级主义者”。以其人之道还治其人之身。
6. 具有“动物性反应”的人。顾及对方感受，并缓和气氛。

五、做好自己的“功课”

1. 谈判最重要的就是不放弃。
2. 用热情和切实可行的计划打动对方。
3. 语言是最强大的“武器”。
4. 在集团中心形成凝聚力。

### Getting More

本书强调人的作用，而非专业知识和谈判流程。需要摒弃兵不厌诈的思想，不能欺骗，反对使用赤裸裸应用权力。人和人之间的信任和尊重对谈判至关重要。

1. 本书独特之处

    - 目标至上
    - 重视对手
    - 情感投资
    - 谈判形势判断
    - 循序渐进
    - 交换评价不同的东西：对方在意什么？
    - 对方谈判准则
    - 积极，诚心，避免操纵谈判
    - 保持沟通顺畅，指出显而易见的问题，将对方引至己方设定的道路。
    - 找出问题的结症并将其转化成机会
    - 接受双方差异
    - 准备清单
2. 无形的谈判技巧

    - 同仇敌忾可以顺利建立人际关系（找到共同点：都喜欢夏天，喜欢看书等等）
    - 关注他人的想法，需求。通过沟通弄清对方真正的意图。沟通也可以消除成见，因为成见产生的原因是无知。

3. 谈判新定义

    - 让对方按照你的思路思考
    - 让对方理解你想让他们理解的观念
    - 让对方感受到你想让他们感受的：出现压力风险时，人容易感情用事。当对方意识到你在意他们感受时，他们会更愿意倾听，更容易被说服。
4. 谈判目标：确定自己的谈判目标时什么，在谈判一开始就要对此做到心中有数，而且还要在谈判过程中不断提醒自己：“什么是我想在这次会议结束时想要得到而现在尚未得到的东西？”

    - 谈判目标越具体越好
    - 帮助所有相关的人实现他们的目标
    - 目标写下来随时查看
5. 步子迈小些：贪婪会让对方厌恶你，不信任你，从而使你得到的更少。本书的主题是强调“争取更多”不是“获得一切”。

6. 一切谈判与情境密切相关

    - 我的谈判目标是什么？
    - 他们是谁？
    - 要想说服他们，需要采用哪些策略和技巧？
7. 你的态度，可信度和透明度

    - 做真实的自己
