# Physics

## 大设计

重新理解生命、自然和宇宙的存在。作者史蒂芬霍金在一开头就提出：哲学已死。他认为，哲学的发展脚步已经跟不上现代科学了，尤其是跟不上物理学，那面追求生命意义的大旗已经从哲学家手里交到科学家手中。

我们生活的这个世界真的存在吗？
“禁止金鱼养在弯曲的鱼缸内”的提案引发的思考。霍金在书中提到：你怎么指导人类所观察到的世界就不是被扭曲过的呢？难道我们人类就不能处在一个巨大的鱼缸当中吗？谁敢说我们的处境一定比金鱼强呢？

金鱼的世界并没有被扭曲
我们生存的这个世界难道是真实吗？
什么是真实？传统的“实在论”认为，被观察者和观察者都是客观存在对象。但霍金认为，除非一个粒子的位置和速度被观察者测量到，否则这个粒子的位置和速度都不确定。当没有人看到我，我可能出现在宇宙中的任何地方。
历史也并非唯一
历史是什么？牛顿流派认为是，已经发生过的唯一的不可更改的事实。但是霍金这一流派的物理学家却不这么认为。
量子物理的三个特性：微观粒子具有波粒二象性，微观粒子具有不确定性，观测系统必然会改变其过程。
双缝实验。历史是没有确定形状的，此刻对历史的观测都会影响历史的过去。
“可择宇宙”原理
一些古老的宇宙形成的传说。世界各地的创世传说。

证实了人类在很早以前就是尝试回答自身的来历问题，为什么存在一个宇宙，为什么世界是现在这个样子？

“大爆炸理论”。宇宙起源：宇宙是以所有可能的方式开始，包括我们已知的和未知的，碰巧赶上了“大爆炸”的时机。

“历史求和”和“可择历史”。人类虽然并不特殊，但可诞生生命的宇宙却是非常特殊的。为何自然定律被这么精细地调谐至让我们这样的生命存在？地球的“偏心率”，太阳系的“幸运属性”，“弱人择”原理，“可择宇宙”原理。

其他有趣的理论
比如，承认有十一维度存在的“M理论”；比如，一张纸一支笔能玩一年的“生命游戏”。

正是我们的存在赋予确定我们从何处在何时可能观测宇宙的规则。也就是说，我们存在的事实限制了我们发现自己处于其中的一类环境特征。这个原则称为弱人存原理。
过去没有确定的形状，这一事实意味着你现在对一个系统进行的观测影响它的过去。
如果我们要回溯得甚至更远并理解宇宙的起源，就必须将我们关于广义相对论所知的与量子论结合。
12.2 时间的形状

Einstein那个聪明的大脑是怎么推导出这么奇葩的公式的呢？让我们回到事情的原点，看看在Einstein之前的科学家们到底碰上了什么样的难题。

谣言粉碎机
必须了解的4个概念：
Popper Falsifiability
Occam’s Razor
Thought Experiment
Simpson’s Paradox
两朵乌云
1900年，开尔文勋爵有一个在物理学界著名的演讲，提到了当年物理学界最头疼的两个问题，形容为两朵乌云。

开尔文断言，一切物理现象都可以归结为某种运动。牛顿关于运动和力的方程式那么的优美。热不过是分子运动。光不过是以太界面行进的电磁波。开尔文最后总结，虽然现在洛伦兹有办法打补丁解决问题，但是在我看来，这一朵乌云还是很浓密的。

开尔文讲的第二朵乌云则是有关能量均分学说。Michelson–Morley experiment被称为“科学史上最成功的失败”。以太这东西到底是什么？为什么几个实验的结论都是互相矛盾的？一系列的实验结果互相矛盾使得人们不得不重新审视过去的观念。

奇葩的狭义相对论
以太被大家认为是光的传播媒介，是物理学界追寻了100年的东西。一系列相关实验相互矛盾，尤其是Michelson–Morley experiment。以太根本没法检测。Einstein否定了以太，根据电磁学理论，光速和观察者无关。真空中光速是不变的。根据光速不变和相对性原理，Einstain推导出了狭义相对论，其结论有：光速是极限速度、钟慢尺短、质量和能量是一码事、双生子佯谬……为了解决引力问题，Einstain花了8年之久琢磨出了广义相对论。简而言之就是时空告诉物质如何运动，物质告诉时空如何弯曲。爱丁顿测量了星光偏移认定是Einstain正确。广义相对论的结论有：星光偏移、水星进动、黑洞、虫洞、引力波、宇宙大爆炸……

万物至理
Einstain晚年一直在研究统一场理论。Einstain不仅是相对论的开创者，也是量子力学的开创者之一。可惜量子力学与广义相对论是不兼容的。因此他一直想统一当前所有的物理学定律，但到死也没有成功。

那么万有理论又是什么呢？统一场是要用“场”的思想去解决一切问题，万有理论没有这个限制，反正妮全能解释就行，是不是场没关系。（Hui：这里“场”的定义是什么？）万有理论还有个目标，就是解释各种物理常数是怎么来的。这一方面要求比统一场多。