# Art

## The Story of Art (By E.H. Gombrich)

Hui: Gombrich illustrates art elegantly like music. There are two threads:
Explicit thread: time
Implicit thread: the inconsistency between what you see and what you know
明线：时间
作者详细叙述了从古至今，从非洲土著到东西方艺术的发展历程，以及艺术与当时社会状态之间的关系。每个时代人们的世界观都有所不同，艺术的目的也就随之改变。

古希腊艺术来自大海对岸的古埃及。但由于社会形态不同，个人价值被挖掘出来，艺术家们不再受神的约束，艺术就逐渐走入求真求美的状态，亚历山大大帝创造出辉煌的帝国之后，古希腊的艺术也达到顶峰，同时在完美的真实这个角度上也达到高峰。

很遗憾古希腊松散的城邦制度没法让他长期保持辉煌，最后被古罗马取代。古罗马不像前者那样充满不切实际的幻想，而是更加注重当下。所以从艺术的角度上也更加注重现实。

在罗马帝国眼里，天主教是旁门左道，古希腊的神话才是正牌宗教系统。但是无论政府怎么迫害，天主教还是发展起来了，最后渗透到宫廷之中，宫廷不得不承认它的位置。从此宗教艺术登上舞台。

教会逐渐取代了世俗权力，为了巩固自己的位置，教会改造了艺术。把艺术当成自己的宣传工具，艺术又回到古埃及那种充满神圣感，泯灭人性的状态。直到我们熟悉的文艺复兴，人们打着复兴古希腊古罗马艺术的旗号，实际上在呼唤人性，渴望自我价值。

文艺复兴是西方艺术的又一次开始，在这之后百家争鸣，但总体上都是一个趋势，渴望自由与平等。欧洲也逐渐形成了今天的格局。艺术下一次发生巨大变化不再是依赖政体和宗教，而是科学。当光学研究有重大突破，照相机被发明之后，艺术受到的冲击比以往任何一次都要大。艺术家们的技巧在照相机面前失去价值，人们能轻易获得真实的时候，艺术久转而追求其他东西。现代艺术开始了。

暗线： 所见和所知的矛盾
这个矛盾时艺术史发展的内在动力。

古埃及人不相信所见的，因为人眼无知而片面，所以他们的艺术要表现所知。无论我们看雕塑，建筑还是绘画，古埃及都有一种规则，就是表现事物最美、最有经验的角度。金字塔一定是均衡的三个面。人物必须是侧面头像正面身体。

古希腊艺术家更重视所见，解刨透视都是这个时期开始的。艺术家想真实的反应自然，寻找自然中美好的东西。所以我们说古希腊的艺术完美。

古罗马把希腊的自然精神发挥到极致，每一个罗马皇帝的雕像都是非常写实的，艺术家已经不再修饰他的创作，而是要更贴近事实。

宗教艺术又回归强调所知，没人见过上帝，所以上帝可以被画成人和形象，但这样做对于教会来说不利于权威。宗教艺术的桎梏被文艺复新打破，新技术的发明更有利于人们描绘自然，从文艺复兴之后的宗教画都发生了变化，圣母有的被描绘成天真无邪的少女，有的被描绘成慈爱的母亲。每一名圣人也都有各自的特点，看起来就像我们平常人一样。这就是所见又重新回归。这次回归的高峰就是印象派，画家们已经开始走进大自然，面对面的感受清晨正午的光线变化，感受阴晴圆缺。

后印象派不崇尚看到的自然，而是倾听自己内心的声音。所知又回到舞台。每个艺术家不同的情感经历，对世界的不同感受开始左右他们的艺术。如果你想要看所见，照相机会给你真正的所见，而艺术家的工作就是画出妮看不到的真实世界。

艺术家
Gombrich认为，艺术是不存在的，存在的只有艺术家。每一个艺术家的贡献连起来就是艺术史。古希腊开始艺术家成为受人尊重的职业，他们有资格可以主导艺术的变化，这其中最有名Praxiteles（most renowned of the Attic sculptors of the 4th century BC.）的技艺已经成为后人的标准。

文艺复兴
Giotto（[’dʒɔtəu]乔托）几乎是一个人就开启了文艺复兴
Leonardo da Vinci（达芬奇）、Michelangelo[ˌmaɪkəlˈændʒəˌlo]和Raphael把文艺复兴推到了高潮
Rembrandt、Rubens（著名的巴洛克绘画艺术家）、caravaggio和Courbet继续推动1
印象派（Impressionism）和现代艺术
Manet、Pissarro、Monnai这些印象派画家开始亲自面对自然写生
Post-Impressionism： Cezannes、Gauguin、Van Gogh改变印象派，他们三个的贡献才开启了现代艺术
Picasso，Dali，Bacon则是把现代主义扩展到更广泛的领域