# Jokes

## 中文笑话

### 2017-12-9: 毒鸡汤

有时候你不逼自己一把，怎么知道自己做不到呢

竹子用了4年的时间， 仅仅长了3cm， 在第五年开始，却以每天30cm的速度疯狂的生长， 仅仅用了六周的时间就长到了15米。其实，在前面的四年， 竹子将根在土壤里延伸了数百平米， 做人做事亦是如此， 不要担心你此时此刻的付出得不到回报， 因为这些付出都是为了扎根，厚积薄发。Where There is a Will There is a Way，所以不要浮躁，每天做好自己，努力扎根，努力成长，不要轻言放弃，总有一天，你会知道原来自己是个土豆。

陪你聊几天你就喜欢他，谈恋爱还没几个月就想过一辈子，交个朋友稍微对你好点就想来往一生，难怪你的怨气那么重、悲伤那么多，这都是天真的代价。

孩子，穷怎么了？穷也要挺起胸膛来，让别人看看，你不仅穷而且还矮。矮又如何？抬起你的头来，让他们知道，你不仅矮，而且还丑！丑不要紧，用你的言谈举止让其他人明白：你还是一个没有内涵的人。没有内涵也不要放弃，从现在开始学习。当你读了足够多的书的时候，你会发现：自己还笨。

别看那些有钱人表面上很风光， 其实， 他们私底下更风光。

如果你的脑海里出现了“放弃”两个字，一定要坚定地告诉自己：你都一无所有了，哪来东西让你放弃！

一个人如果没有梦想， 跟无忧无虑有什么区别呢？

黄鼠狼在养鸡场山崖边立了块碑，写道：“不勇敢地飞下去，你怎么知道自己原来是一只搏击长空的鹰？！”

从此以后

黄鼠狼每天都能在崖底吃到那些摔死的鸡

和妹子相处，要义就是： 若她涉世未深，就带她看尽人间繁华； 若她心已沧桑，就带她坐旋转木马。
和男人相处，要义就是：若他情窦初开，你就宽衣解带；若他阅人无数，你就灶边炉台。

哪有什么选择恐惧症，还不是因为穷；哪有什么优柔寡断，还不是因为怂。

你这么努力，忍受了那么多寂寞和痛苦。可也没见得你有多优秀啊！

岁月是把杀猪刀是针对那些长得好看的说的,对于那些丑的,岁月拿他们一点办法也没有…

注重细节，从小事做起，因为你根本做不了大事。

你无法叫醒一个不回你消息的人，但是红包能。

每当我找到成功的钥匙，就发现有人把锁芯给换了。

物以类聚人以穷分。有钱人终成眷属。

钱那么靠谱的东西都有假的，更何况是人说的话呢？

年轻的时候多吃点苦是好事 这样老了你就习惯了。

好人成佛需要九九八十一难 而坏人只需要放下屠刀。

白雪公主的故事告诉我们 七个小屌丝对她再好也不如王子的一个吻。

人生就是这样，有欢笑也有泪水。一部分人主要负责欢笑，另一部分人主要负责泪水。
世上无难事，只怕有钱人。 ### ～2016-4-5

56个民族55个加分
期末考啦，老娘不给你露一手，你还以为你教的好呢！
毕业不分手，异地绿成狗
千万不要以为你高中单身是因为学校禁止早恋…

Hui: 还有，也千万不要以为你学习不好是因为高中早恋…

婚姻就像围城，城里外的人想进去，城里的人玩的好开心。
据说新不孝有三：学文、考研、没对象。
淘宝精神: 为了省钱而花光身上所有钱的精神。
民主是一种很复杂的东西，复杂到这是中国人唯一没能山寨成功的东西。
某博士的毕业答辩会上，一个评委抱怨说：“你这论文写的什么啊，我看了3天都没看懂！”博士暴怒到：“这篇论文我写了3年，你才看了3天居然就想看懂，你当我在写小说啊？！”会场一篇寂静，遂全票通过答辩。
妈妈说，该学习的时候我在谈对象，该上班了我又跑去搞学业了，现在该谈对象的时候又在忙工作，然后就变成剩女了！说完最后还总结了一下说，我这辈子都在着重搞副业……
据说这是最早的呻吟体：
……..密……封……线……内……不……要……答……题……
你瘦的时候在我心里，后来胖了，卡在里面出不来了。
唾沫是用来数钞票的，而不是用来讲道理的。
人生五大标准答案 ：喜欢就买 不行就分 多喝点水 注意安全 重启试试
一帮老头儿老太太无所事事，就去上老年大学，有一天集体忘记做作业了…… 校长闻知大怒，罚他们集体操场罚站，同时还带来了一个道士，好一阵的舞剑、画符、念咒、烧纸……老人们都看的不明就里，就问这是要干啥，校长很严肃的说道：干啥？请家长！
从来扯着嗓门喊着要走的人，都是最后自己把摔了一地的玻璃碎片，闷头弯腰一片一片拾了起来。而真正想离开的人，只是挑了一个风和日丽的下午，裹了件最常穿的大衣，出了门，然后就再也没有回来过。
刚刚一个很帅的帅哥在我面前，我们相视了很久，谁都没有打破这份平静。直到手累，我才慢慢的放下了镜子。
生子当如孙仲谋,找爹就找金日成。
这小伙子长得,把脸挡上跟个演员似的…
有刺青的不一定是流氓,他可能是岳飞。
都说女人是一本书，姑娘，您这身材，是合订本……
一个和尚挑水喝,两个和尚抬水喝,三个和尚没水喝,四个和尚斗地主,五个和尚可以去扮福娃了
拿什么来拯救你你这个贱人。
您真是贱人多忘事啊
黑猩猩不小心踩到了长臂猿拉的大便，长臂猿温柔细心地帮其擦洗干净后它们相爱了。别人问起他们是怎么走到一起的？黑猩猩感慨地说：猿粪！都是猿粪啊！
明天你醒来，枕边躺着一只蚊子，身边有一封遗书，上书：我奋斗了一晚，也没能刺破你的脸，你的脸皮厚得让我无颜活在这世上！主啊~宽恕他吧！我是自杀的。
一日 一对苍蝇母 子在一起吃午餐, 儿子问苍蝇妈妈:为什么我们每天都吃大便啊?苍蝇妈妈生气的说:吃饭的时候不要说这么恶心的话,趁热吃!!
两个饺子结婚了，送走客人后新郎回到卧室，竟发现床上躺着一个肉丸子！新郎大惊，忙问新娘在哪？肉丸子害羞的说：讨厌，人家脱了衣服你就不认识啦!
某晚，一裸男叫了一辆出租车，女司机目不转睛盯着看他，裸男大怒，吼道：你他妈没见过裸男呀！女司机也大怒：我看你他妈从哪儿掏钱！
狼崽从出生就吃素。狼爸狼妈绞尽脑汁训练狼崽捕猎。终于有天狼爸狼妈欣慰地看到儿子狂追兔子。狼崽抓住兔子凶相毕露恶狠狠地说：小子！把胡萝卜交出来！
巴黎圣母院少个敲钟的，就你了。
你出生时是不是被扔上去过３次而只被接住过２次？
你的牙如同天上的繁星，色泽鲜艳，相距甚远
《翻身姐妹》经典语录：
一个在前男友面前把礼服撑爆的人，什么事儿都干的出来的。
这是释放金钱和欲望的时刻，是渴望良知与本能的战争。我们的敌人非常强大，却又不堪一击；非常疯狂，却又想时刻保持着理智；一个伟大的党派，一个通知全宇宙的党派，它的名字就叫作，剁手党！
“嗷嗷有钱”、“36D从不偷工减料，人送外号110”、“完美长腿110” 、“颜值爆表姐妹团”、 ”腹黑麻辣段子手 ”、“火腿肠海滩照大法”、“多挣钱，养好膘，世界末日也风骚”、“你不爱我的钱，我怎么带你愉快的玩耍”
我的人生就像西直门的立交桥，你是永远都不可能找到方向的。
别闹了，这世界上怎么会有女汉子呢？只不过都是些又穷又丑的女吊丝罢了。
你不可能一辈子绝望下去的，时间久了就习惯了呗。
说个上大学时候的事，寝室有位仁兄，整天对着电脑玩魔兽，衣服差不多一个星期洗一次，每次都是一大堆全放进盆里，用洗衣粉泡着，十几分钟后用水一冲搞定，问他都不用刷也不用揉的吗？这牲口瞟都没瞟我一眼回句：我用的是奥妙全自动。奥妙全自动？全自动？
晚自习的时候考试，拿出手机搜答案，突然，老师把灯一关，我……亮了。
感觉别人都是吃几口就饱了，而我是吃饱了还能再吃几口…
心情不好我就坐公交车，坐在有长头发后面的给她剪头发。
Hui: 谁家养大的熊孩子，主意这么损你爸妈知道么？-_-!

在学校宿舍，我杯子里的水总被偷喝，用涂改液在杯子上写了：“别喝！”水还是不断减少，某天吃完药，剩两片不想再吃了，顺手扔杯子里了，第二天早晨来刚坐下，听见后方某男生低沉的声音幽怨地说：“够狠的啊，下药了！”
话说有一个美国小伙来中国留学，跟同宿舍的一个中国同学很是要好，俩人约定互相教对方语言，一年后，中国小伙顺利的通过了英语八级考试，而美国小伙则操着一口流利的河南话回到了美国。
下午去求个佛珠，小和尚告诉我说：方丈去进货了。
我一生气就想买东西,一买东西就得花钱,一花钱钱就少,钱一少我就生气。
只要瘦，什么都百搭，要是胖，什么都白搭。
几个吊丝出去秋游，坐车的时候，售票员问：你们从哪里来，要去哪里啊？ 他们幽默地齐声答道：“我们从东土大唐而来，要到西天取经去。。。”全车的人都笑了。售票员回道：“几位大师坐错车了，我这是往东南方向的，往西去的请到路对面去坐！”其中一个来了句：“那我们先去南海见下观音姐姐….”
红孩儿到底是不是牛魔王的儿子？铁扇公主会不会跟太上老君有什么不可告人的关系？芭蕉扇是太上老君摘的，却在铁扇公主手里；牛魔王根本不会三昧真火，红孩儿却天生就会。。。真TMD耐人寻味！吴承恩下了很大一盘棋？！
Hui: Hahaa~~这个信息量太大了

火车上，一乘客对乘务员说：“给我来瓶可乐，多少钱？” 乘务员：“8块。”乘客：“多大一瓶的？”乘务员：“就是外面卖3块钱的那种!”
上小学的时候，在路边买了个小葫芦，上课的时候偷偷在下面玩，不巧却被老师发现，问我在干什么，我不知道哪来的勇气，脑残的把葫芦举起来，对着他，说了一句：“我叫你一声，你敢答应吗……”
小时候的的三大偶像：雷锋、张海迪、小兵张嘎。简称“雷迪嘎嘎”
人生就像高压锅。压力太大的时候自己就熟了。
如果我能原谅你的庸俗，那么你能原谅我的装逼么？
蓝精灵对着阿凡达唱：“长大后，我就成了你”。
本人女，身高165，特羡慕那些娇小依人的小女生。某天晚上我弱弱的问道：老公，你是不是特羡慕那些老婆小鸟依人型的？我好像这辈子也没个机会了…老公看都木有看我一眼，说：“没关系，我是杨过。”心下暗喜，难道老公以为我是小龙女般的~“为什么呀？”想不到这厮来了句：身边跟个大雕。。。[Hui: Haha~~]
刘备问诸葛亮“你最喜欢是歌手是谁”。诸葛亮说“Justin Bieber”。刘备又问“为什么”？诸葛亮回答：“因为我特别喜欢他的一首歌”。刘备好奇的说“唱两句听听呗”。诸葛亮脸一红，唱到：“备备，备备，备备，哦…”
如果世界上只剩下他和一块砖头，我一定用板砖拍死他……
只要你努力，世上没什么事情搞不砸
24.1.2 2016-4-6 ~ 2016-6-23

我老觉得我网名不够好，你帮我取一个吧”，“有什么要求？”，“高贵点的，有女人味最好能带点淡淡的忧伤”，“爱新觉罗·痛经……”
Hui: haha……好高贵好忧伤啊。

有一舍友的手机铃声是婴儿的哭声。一天，舍友上厕所，便秘，在厕所里待了很久。只听他大叫一声，啊话音未落手机铃声响起，从此他在学校出名了。。。

今天，我们这一老太太去世了，家人都在痛哭呢，突然一人手机响了，山寨的声音巨大……今天是个好日子，心想的事儿都能成，顿时他们都不哭了！

Hui: 缺乏基本品味的后果有时是难以预测的……

经过分析，自从用了智能移动电话后，我的智能，移动和电话都在减少。
现在才发现你们这群小年轻，都以为穿的少是帅，吸引妹子的目光，我要是现在上学绝对穿个军大衣过去，看到妹子冷的死去活来，哥哥霸气的把大衣打开说：里面还能塞个人，你来么？
今天翻阅儿子的手机电话谱，发现有个叫和平使者的女孩。一时好奇就问儿子是什么意思，儿子回答说：这货放了我几十次鸽子！我…….
“医生，请救救我，我好像得了一种超级容易被别人无视的病。” “下一个，谢谢。”
今天在医院挂水，没有WiFi的情况下我发现了一个小秘密。一瓶250毫升的吊水竟然有3564滴。
懒是一个很好的托辞，说得好像勤快就真能干出什么大事儿一样。胖是一个很好的托辞，说得好像瘦之后就真能有多好看一样。不想谈恋爱是一个很好的托辞，说得好像想恋爱时真能被人看上一样。年轻是一个很好的托辞，说得好像成熟了之后就真能有多大出息一样……
24.1.3 2016-4-24 ~

时间就像乳沟，挤一挤总会有的，但是只要一躺下就什么都没有了……
Hui: Hahaa~~不能懒

老师问：“有钱，任性”的下联是？” 学生答：“没钱，认命”。 老师哑然！
老师问：“用一句话形容现代男人的婚后生活！” 学生：“娶了个祖宗生了个爹！”
老师再问：“古代女人为什么要裹脚？” 学生大声道：“怕她们逛街”。
老师接着问：“那么为什么现在不裹了” 学生：“现在有了支付宝，裹脚也没用。”老师：“来来来、你讲课…
病榻前，金正日拉着三胖的手，断断续续地嘱咐，“儿子，谨记四件事：一、坚持主体思想；二、继续发展核武；三、不忘民族统一；四、不要辜负……”咽气了。金正恩含泪望着离去的父亲不住点头：“不要姑父，不要姑父…”可怜的姑父啊！（姑夫）成泽到阴间见到金正日，正日大惊：成泽，你不保护三胖，来这里干什么？成泽大怒：你把话说完了再死好不好 ？
养育一个小屁孩就象发射卫星，花费十几年心血确保每个环节和数据的正确。最后一朝发送成功，考上大学，然后卫星就消失在茫茫的外太空，只剩下定期不定期的发回来一些微弱的信号。。。给点钱。。。给点钱。。。 把钱发给了卫星，叮嘱吃好穿暖。卫星又发回来微弱的信号。。。别啰嗦。。。别啰嗦。。。 等信号稳定了，又要花一辈子的积蓄帮他建立空间站。如此坑爹的事情，居然还号召大家造两颗……
你虽可以像只猪一样懒，却无法像只猪一样懒得心安理得。
我吃了太多盐，闲的总去想你啊。
生前何必久睡，死后自会长眠
其实，大多情况下，没有你想象的那么严重：“你的抑郁症是矫情，你的拖延症是懒，你的强迫症是闲的发慌，你的失眠是根本不困，你的选择恐惧症是因为穷。”
刚才去银行办理业务，看到隔壁一个老大爷在填一张表，我看老大爷有些为难，我就多瞅了一眼，其中有一个选项是证件类型，老大爷琢磨了半天，颤颤抖抖的写了个“长方形”。
以后你结婚了，如果新郎不是我，我就搬到你家隔壁去住，对你孩子比对亲生的还好，直到让你老公怀疑人生。
春天坐你的保时捷兜风，夏天吃你藏好钻石的冰激凌，秋天数着和落叶一样多的钱，冬天和你在皮草堆里取暖。想要这样纯粹的爱情，没有一丝杂质，简简单单，只与钱有关。
我从小就懂得节约用电，甚至晚上写作业都不舍得开灯，而是开着冰箱门，借着保鲜室的灯光学习。
在街头散步，看到地上有一叠百元大钞，我激动得晕了过去，等我醒来时，看到钱居然还在，又激动得晕了过去。
你的话，我连标点符号都不信。
陪我一起数星星吧，你智商低你就数月亮吧！
我能抵抗一切，除了诱惑……
人又不聪明，还学别人秃顶。
我又不是人民币，怎么能让人人都喜欢我？
执子之手，方知子丑，泪流满面，子不走我走。
一个小测试, 发给你暧昧的对象 喜欢的人,“今天我吃药时候看到一则新闻”如果他问「是什么新闻」而不是问你「吃什么药」就代表他不喜欢你
优秀的女孩子，连胸都是A
记者：“大爷，您今年贵庚啊？” 大爷：“九十有六了。” 记者：“这么大岁数怎么还在外面卖桃子了？” 大爷：“哎，别提了，我也不想啊” 记者：“怎么回事呢？” 大爷：“卖不完回家我妈不让我吃饭！”
Hui: 好有才啊。

活着的时候开心点，因为我们要死很久。
有次等公交时，遇到一女神，于是上前搭讪，“姐,等车呀？”“等生意。”女神的回复令我一生难忘。
我一直学习成绩很好，而我妈是个农村人，没什么文化。有一天，我妈抚摸我的头说：“儿砸，我相信你总有人头落地的一天…”

一哥们儿一天看到一个笑话。感觉特别好笑，便回家讲给老婆听。 可是老婆还没反应过来，柜子里便传来了笑声···

经济 economy 依靠农民
海关custom 卡死他们
雄心 ambition 俺必胜
地主 landlord 懒得劳动
怀孕 pregnant 扑来个男的
救护车 ambulance 俺不能死
律师 lawyer 捞呀

春天与出轨的共同点是：绿得不知不觉
生活小常识：通过掌纹，可以看出女朋友的性格。如果她的掌纹经常出现在你的脸上，说明她性格比较暴躁。
不与女友吵架的要领是，要像在安装软件或注册网站会员时阅读“服务条款”那样，直接忽略所有的内容，到最后勾选“我同意”，然后点击“确定”。
在麦当劳看到一对穿校服的小情侣，貌似在吵架，我认真的听了一下，女生大声问男生：“说！你和那个96年的老女人是怎么回事？”尼玛，听的老子的汉堡差点掉地上……
如果你一个月挣2000想买一套100平的房子，那么没关系，可以先定个能实现的小目标，比方说：我先活它个500年，然后再向天借500年。
地铁上很挤，我忽然感觉有人摸我。我大叫道：“有变态呀。” 大家齐刷刷的盯住我后面的那个秀气男子。 “变态！”“不要脸！”……我大喊。 那秀气男子脸涨的通红，辩解道：“我不是变态！我……我只是小偷。”
昨天有一对情侣过来问我去快捷酒店怎么走，我毫不犹豫的给他们指了去新华书店的方向，希望他们能在知识的海洋中找回迷失的自己。日行一善，善哉善哉！
老公喝酒晚回家了，我决定换个新奇的方式惩罚他，于是就让他对着镜子玩剪刀石头布，赢了才能睡觉。
半夜睡不着，起来到客厅，看见一只蟑螂。就对着它聊了起来，聊我对上司的不满，对生活的看法和各种因素的压力。烟抽完了，于是一脚就把它踩死了，谁让它知道这么多了！

24.2 中文笑话－神回复

24.2.1 ～2016-4-5

「滚床单」有哪些优雅的叫法？ @：管鲍之交。

分手100天了，还没有走出来怎么办？ @：替换文件永远比删除文件更彻底。

为什么女生有「体香」，而男人没有？ @：化妆品腌入味了→_→

健身会导致停经吗？@：要看你和教练的关系…

你会在意你的恋人有异性闺蜜吗？@：女人永远不会明白男人为什么怀疑她跟别的男人的友谊，因为男人太了解男人了！

在拥有爱情之前，男人和女人最好要知道什么？@：假装爱一个你不爱的人，即是最大的不自爱。真实地爱一个不爱你的人，并不是丢脸。以爱来绑架一个不爱你的人，则是下作。

你同意「不以结婚为目的谈恋爱就是耍流氓」这个观点吗？@：不以恋爱为过程的结婚才是耍流氓。

Hui: 现在终于明白为什么流氓生生不息了，自然选择的结果啊……

情人节没情人怎么办？ @：家里没死人的难道还得在清明节前费劲弄死一个两个的么？ 没有就不过。
Hui: Hahahahaha~~这个太好笑啦

追到女生后马上失去兴趣，怎么办？@：“诗人只有在吻到姑娘之前，才歌颂爱情。 他们得到一个女人之后，就开始歌颂自由。”

帮我想个旅游节目宣传语，需要主题明确，意境突出，既能尊重别人，又可以突出自己。内容要略带性感，不显浮华，最好让人听一遍就记住。@：大爷，来玩撒！

24.3 English Jokes

Get your facts first, then you can distort them as you please.[MT]

All you need in this life is ignorance and confidence, and then success is sure. [MT]

There was once a young man who, in his youth, professed his desire become a great writer. When asked to define “great” he said: “I want to write stuff that the whole world will read, stuff that people will react to on a truly emotional level, stuff that will make them scream, cry, howl in pain and anger!”

He now works for Microsoft, writing error messages.

A Mathematician, a Biologist and a Physicist are sitting in a street cafe watching people going in and coming out of the house on the other side of the street. First they see two people going into the house, Time passes. After a while they notice three persons coming out of the house.
The Physicist says: “The measurement wasn’t accurate.”
The Biologist concludes: “They have reproduced.”
The Mathematician says: “Now if another person enters the house, it’ll be empty again.”
Hui: Mathematical induction?! Statistician would say:“The sample size is too small to get any conclusion.” Statistician can never be wrong because all is chance : )

Mark Twain once said, “The coldest winter I ever had was one summer in San Francisco.” [from Prof. Norm Matloff]

Two guys are walking down a dark alley when a mugger approaches them and demands their money. They both grudgingly pull out their wallets and begin taking out their cash. Just then, one guy turns to the other and hands him a bill. “Hey, here’s that twenty dollars I own you.”

Hui: You need to be very careful about what kind of friend you make. : )

A statistician gave birth to twins, but only had one of them baptised. She kept the other as a control.

One day a mathematician decides that he is sick of math and wants to be a fireman. So, the mathematician walks down to the fire department and announces that he wants to become a fireman and need to answer some questions. “You’re walking in the alley and you see the dumpster here is on fire. What do you do?” The mathematician replies, “Well, I hook up the hose to the spicket, turn the water on, and put out the fire.” The fire chief says, “That’s great… perfect. Now I have to ask you just one more question. What do you do if you’re walking down the alley and you see the dumpster is not on fire?” The mathematician puzzles over the question for awhile and the finally says, “I light the dumpster on fire.” The chief yells, “What? Why?” The mathematician replies, “Well, that way I reduce the problem to one I’ve already solved.”

News bulletin: A local Physicist declared that he has figured out the ingredients in McDonald’s secret sauce: protons, nuetrons, and electrons.

If it’s green and wiggles, it’s biology.
If it stinks, it’s chemistry.
If it doesn’t work, it’s Physics.

Engineers think that equations approximate the real world.
Scientists think that the real world approximates equations.
Mathematicians don’t care.

An engineer, a physicist, and a mathematician were on a train heading north, and had just crossed the border into Scotland.
The engineer looked out of the window and said “Look! Scottish sheep are black!”
The physicist said, “No, no. Some Scottish sheep are black.”
The mathematician looked irritated. “There is at least one field, containing at least one sheep, of which at least one side is black.”
The statistician : “It’s not significant. We only know there’s one black sheep”
The computer scientist : “Oh, no! A special case!”
Neuroscientist joke: the hypothalamus regulates the four essential F’s of life: flighting, fleeing, feeding and mating. [T.S]

(This one was told by the famous statistician Manny Parzen.) A university class was taking a multiple-choice exam. One student was busy flipping a coin to determine his answers. Even after all the other students finished the exam and left, the student was still flipping the coin. The professor said, “I can’t stop you from flipping the coin, but everyone else is done.” The student answered, “Oh, I’m done too. I’m just checking my answers.” [from Prof. Norm Matloff]

The famous comedian Bob Hope (non-Jewish) once told this joke: The most important thing for success is sincerity. Once you learn to fake that, you’re all set." [from Prof. Norm Matloff]

Someone asks an American, a Russian and an Israeli (one can substitute New York or Hong Kong for Israel), “Excuse me, what do you think of the meat shortage?” The American says, “What’s a shortage?” The Russian says, “What’s meat?” The Israeli says, “What’s ‘excuse me’?” [from Prof. Norm Matloff]

Man is the only animal that blushes – and the only animal that needs to. [MT]

A husband stepped on one of those penny scales that tell you your fortune and weight and dropped in a coin. “Listen to this,” he said to his wife, showing her a small white card. “It says I’m energetic, bright, resourceful, and a great person.” “Yeah,” his wife nodded, “and it has your weight wrong too.”

A man driving on a highway is pulled over by a police officer. The officer asks: “Did you know your wife and children fell out of your car a mile back?” A smile creeps onto the man’s face and he exclaims: “Thank God! I thought I was going deaf!”

A guy goes to the hospital for a check-up. After weeks of tests, a doctor comes to see him and says that he has some good news and some bad news. “What is the bad news?” asks the man. “I am afraid we think you have a very rare and incurable disease,” says the doctor. “Oh, my God, that;s terrible. What is the good news?” says the man. “Well,” replies the doctor, “we are going to name it after you.”

A man walking down the street sees another man with a very big dog. The man says:“Does your dog bite?” The other man replies:“No, my dog doesn’t bite.” The first man then pats the dog and has his hand bitten off, and shouts, “I thought you said your dog didn’t bites” The other man replies: “That is not my dog.”

A weed scientist goes into a shop. He asks: “Hey, you got any of that inhibitor of 3-phosphoshikimate-carboxyvinyl transferase? Shopkeeper:”You mean Roundup?" Scientist: “Yeah, that’s it. I can never remember that dang name.” [From Dan McCammon]

A bartender says, “We don’t serve faster than light particles in here.” A tachyon walks into a bar. [From Bill Rand]

300 yrs ago Thomas Bayes, a minister, revolutionized statistics w/a simple theorem
300 yrs ago Thomas Bayes, a minister, revolutionized statistics w/a simple theorem

[Joke from Norm Matloff: Here’s another joke I just thought of. It was told by famous comedian Jack Benny, I think on his TV show, but I only read about it.]

Benny was famous for being very stingy with his money. (That was his persona on the show, but apparently in real life he was quite generous.) One day a robber confronted him with a gun, and said, “Your money or your life!” A few seconds passed without Benny replying or complying, so the robber said again, louder, “YOUR MONEY OR YOUR LIFE!” Benny then replied, “I’m thinking, I’m thinking.”

Two hunters are in the woods when one of them collapses. He doesn’t seem to be breathing. His eyes are glazed. The other guy takes out his cell phone and frantically calls 911. He gasps: “My friend is dead! What should I do?” The operator says: “Calm down, I can help. First, let’s make sure he’s dead.” There is a silence, then a gunshot is heard. Back on the phone, the guy says: “OK, now what?”