# Development

Developmental psychology deals with foundational questions

- morality and the origin of moral thought. Two very different views:
    - we start off as immoral or at best amoral
    - we're basically good then we can be corrupted (Jean-Jacques Rousseau). In contemporary discussions, we talk about prejudice and racism, and they'll insist that we're not naturally, prejudice or racist. We can become that way is because of the corrupting influence of culture.
- The extent to which the way we are right now, was sort of set in stone. Either when we were born, because of our genes, or at least but a time or two or three. It's an interesting question for instance, how much an interview with a three-year-old can predict the way the three-year-old would turn out. It turns out that when studies are done, a 90-minute interview for three-year-old does predict personality on certain standard scales, the quality of their personal relationships, whether or not they have a job, criminal behavior, and so on.
- how much of what we know now we're born with, and how much we have to learn? Psychologists, developmental psychologists talk about three different views,
    1. empiricism, which is we start off empty and then we learn and learn and learn and learn. You've seen this in the last lecture and discussions of behaviors and this was the behaviors idea. 
    2. Nativism, which is associative Noam Chomsky, rejects the idea that learning plays a critical role and it says, we actually are born with rich powerful structure systems in our brain. 
    3. constructivist (John Piaget) I'm going to talk about this in the next two sections and you'll see that it shares with the empiricist view. The idea of learning, interaction dealing with the environment, makes us who we are. But it shares with the nativist view, the idea that the mind is actually quite complex, and the course of learning is not merely the accumulation of information, let alone the accumulation of conditioned responses, but rather something far more interesting and far more elegant.

## Piaget

- Jean Piaget was the founder of the modern study of developmental psychology. His research program was genetic epistemology and he was interested in the development of knowledge  in the human species.
- He pursued his research by looking at it in children.
- **ontogeny recapitulates phylogeny**: you can see the development of the species is repeated,  recapitulated, in the development of every individual.
- Piaget thought of children as active thinkers, constantly trying to construct more advanced understandings of the world.
- described these understandings as schemas these schemas were **frameworks that develop to help organize knowledge**.
- two psychological mechanisms  that lead to the transformation of these schemas and the creation of new schemas. 1) assimilation: the process of taking in new information and  new experiences and matching it up with an already existing schema.  2) accommodation: the process by which existing schemas are changed, or  new schemas are created, in order to fit the new information and new experience.
- Approach:  he asked children to solve problems, and then asked them about their reasoning behind the solution.
- View: children think in entirely different ways than adults.  So he's not a nativist suggesting that children know it all from the start nor is he an empiricist or a behaviorist who viewed  learning simply as the accumulation of new knowledge.  Or for the behaviorist, new conditioning and new responses.  Rather, Piaget believed that children have theories of the world, and so do we.  And children's theories are very different from ours.
- he proposed that theories transform  and that you could capture the development in terms of a series of stages.  Each stage corresponding to a different style of thinking,  a different way of making sense of how the world works. Different from Freud's psychosexual theory, Piaget's theory is more intellectual and scientific grounding.

## Piaget's Developmental Stage Theory

Stage 1: Sensorimotor 

- 0 - 2
- Info is gained through the senses and motor actions
- The child perceives and manipulates but does not reason
- Object permanence
    - The understanding that objects exist independent of one's actions or perceptions of them
    - Before 6 months infants act as if objects removed from sight cease to exist

Stage 2: Pre-operational

- 2-7
- Emergence of symbolic thought
- Reasoning develops, but not high level
- Egocentrism: can't see the world from the others' eyes (three mountains experiment)
- Lack of the concept of conservation

Stage 3: concrete operational 

- 7-12
- Understanding of mental operations leading to increasingly logical thought
- Less egocentric
- Inability to reason abstractly or hypothetically

Stage 4: Formal operational 

- 12-adult
- Abstract and scientific reasoning

## Scientific evaluation of Piaget

- Falsifiable and interesting claims
- Rich theoretical framework
- Striking findings

Limitations

- Theoretical: Does he really explain development?

    If you ask: "How does assimilation accommodation really work to transform from one stage to another?"... no clear answer

- Methodological: limitations of Q&A with children
    - Children are not very verbal, sensitive to task demands (say things to please emperimenter)
    - They don't know the working of their mind
- Factual: what do infants and children really know? Children are smarter than you think.

## Methods for studying infants

- use MRI to understand babies (brain scans)
- Sucking and looking: explore what babies know
    - Does a baby enjoy listening to the sound of the mother or someone else? You can't ask.  But you can put a pacifier in a baby's mouth and put headphone on the baby's ears. suck pacifier when hear the mother's voice.

## How are children different from adults?

- From 4.5 to 5, they begin to think about other people's thoughts. They begin to think that somebody can think something different from what they know, that people's thoughts are private and maybe incorrect. People can have false thoughts about something that they know to be true. Once you understand that, then you can explain all sorts of things about why people do things which seem strange to you. They're looking for things and you know that's not where they are. It also means that you can understand how to surprise people, how to trick people because once you've met the split between the mind and the world, then you can think about people's minds and manipulate the way the world is, so that they come to believe certain things about it.
- Sally & Anne

## Explanations for development

- Neural explanation

A lot of what goes on in early brain development is pruning, the getting rid of neural connections. And it's this that somehow makes more advanced, more mature thought possible. 

Another aspect of brain development is modernization. And what this means is that the **myelin [ˈmaɪəlɪn] sheath [ʃiːθ]** around neurons that makes them run faster and more effectively takes time to develop. This develops all the way through adolescence. In fact, more generally parts of the brain are not fully developed until quite late in life. And in particular, the frontal lobes, the part of brain just behind your forehead, takes considerable time to develop and is not fully developed in adolescence, let alone in children or babies. And this can be telling because it could be part of a child's problem has to do with **inhibition**, which is what the frontal lobes are good at.

- Open questions

Open question 1: large scale v.s. specific modules

**Freud, Piaget, Carey**: **large scale changes**

v.s.

**Chomsky, Fodor:** The brain contains **specific modules** that are special systems of the head. Separate, partially pre-wired systems for reasoning about the physical and social world

- For example: Autism is due to a damaged module

Open question 2: if there are modules, what are they?

Open question 3: Could profound general differences between the minds of children and adults be an effect of learning language? 

# Language

Whether we're talking about philosophers like Aristotle, Plato, Hume, Locke, psychologists like Freud and Skinner, modern day approaches that computational analysis or cognitive nerve science, evolutionary theory, cross cultural psychology, if you can't explain language, you're not in the game.

What do I mean by language? And when I talk about language, at least for this beginning phase, I mean systems like English and Dutch and French and Navajo and Mandarin and so on. Now, you could use language in other ways. You could use the word language to describe animal communication or music or any communication system you want.

- **The Language Instinct** by Steven Pinker, which is a classic introduction to the science of language.
- **The Power of Babel** by John McWhorter, which takes a somewhat different approach than Pinker and looks more at language as a historical artifact, how it changes over time. Less psychology, less evolution, but a lot more history, and they're both wonderful books.

## Basic facts about language

- Every human society has language: fits with Darwin's idea that language is instinctive and natural, it shows up everywhere.
- This **doesn't** show that languages is **instinctive** or that is built into the brain. Because language might have even been invented once and spread through history. But there's good reason to believe that it's not and that Darwin is right.
- Creolization [ˌkriːələˈzeɪʃn]: it involves people who are involved in the slave trade, the production of tobacco, cotton, coffee, sugar who would bring together and mix slaves and laborers from different language backgrounds. So these people would work together but they didn't have a common language. What often happens is they develop a makeshift jargon which is called a pidgin, P-I-D-G-I-N which involve strings of words borrowed from the language of the plantation owners, often from people's own native tongues. But there's no word or no grammar, imagine yourself locked in a room working with a bunch of people with no common language, but you had to work together so you'd make a sort of common communication system. Now, the question which arises is, the children in these societies, the children of the slaves were often brought up independently from their parents in a collective setting and what they heard was mostly a pidgin, and so the question is what would they come to know? And you might imagine well, you're exposed to a pidgin, you'll learn a pidgin. But this isn't actually what happens. What's interesting is children are built so that they take this non-linguistic system as **rudimentary** system and transform it into a real language with syntax and **morphology** and **phonology**. But a real language, which is known as creole (*a language that has developed from a mixture of different languages and has become the main language in a particular place*). So when you hear about a creole now of which many people speak, that remarks in this historical origin of creole was once a pidgin and has been transformed into a language and that tells us something about the human mind. There are actually some modern cases of creolization that had been studied. So imagine a child who is born deaf to hearing parents, so the parents understandably enough want to communicate with the child so they quickly learn a sign language through which to communicate with the child. Because it's a second language learning which is difficult. The language that the parents use is more of a pidgin and children are exposed to a pidgin. But what often happens particularly if children are raised in a community of other children in the same situation? Is that they creolize, they take this simple communication system that they're exposed to and they transform it into a full-blown language. This tells us something about our capacity and our expectations with regard to language.
- Every normal human has language. This is true by definition if a child reaches the age of three or four and doesn't speak, there's a serious problem going on which requires serious attention and that's different from other things. Not everybody knows chess or rides a bicycle, but language seems to be the sort of thing that everybody comes to possess. It's no surprise that there are specific areas in the brain that are devoted to language. We'll talk a little bit more about these later on in the course. What's a little more controversial is what these brain areas do and these genes cause. There's no doubt that humans have a special capacity for language, but the precise nature of this capacity whether it's something specific and designed for language or whether it's a more general set of capacities that allow people to learn language that's a matter of controversy.
- what else can we say about language? Well, when linguists talk about language, they say that language has the property of creativity and this can mean different things, it creative, is often used to describe special abilities and that's not what we're talking about here. For normal use of language, people can say what they choose to say and can produce a virtually infinite number of sentences by one estimate, the number of sentences under 20 words long is 1 with 30 zeros after it. So if it took you five seconds to say a sentence, in order to say all of them you'd have to spend about 100 trillion years. This suggests that language understanding, language comprehension, language production, can't just be a matter of rote memory. If you understood what I said and understand I'm saying now, it can't be because at some point you've memorized the meanings of these sentences, you have to have some way of taking strings of words that are put together in order you've never heard before and making sense out of them. So how do we do this? Well, we do this through rules and principles.
- We have these abstract and unconscious rules in our heads that let us take strings of words and make sense of them. When I'm talking about rules of language, I'm not talking about things like don't say ain't or don't end a sentence with a preposition, these are not rules that you're forced to comply within school, they're not what linguists call prescriptive rules which is how you should use language, rather these are abstract and unconscious rules that you have. You don't even know you have them that allow you to figure out the virtually infinite strings of sentences you could be exposed to. These are what the things that linguists study. So for instance, you hear a sentence, "The pig is eager to eat," and instinctively you understand that the eating here is to be done by the pig. But if you hear a sentence, "The pig is easy to eat," in the same fraction of a second you realize this means that the eating is of the pig not by the pig.
- Or take a sentence, "Bill knew John liked him." Any speaker of English realizes that this could mean that Bill knew John liked Bill, it could have other meanings but it could mean that Bill knew John like Bill. But if you hear the sentence, "Bill knew that John liked himself." This can't mean that Bill knew that John liked Bill, it has to mean that Bill knew that John liked John.
- we characterize languages in terms of these rules and principles and it turns out that language can be characterized at different levels.
    - sound system: phonology
    - words and how words are composed: morphology
    - how words are combined to make phrases and sentences: syntax

## Phonology, Morphology and Syntax

1) **Phonology**: It studies what phonemes are, and how they're put together to construct words.

2) **Morphology**: It studies morphemes, issues of meaning.

> The arbitrariness of the sign.  by French linguist Ferdinand de Saussure

A **morpheme** is the smallest meaningful unit. 

- You can't infer the meaning of a morpheme, it's arbitrary and you have to learn it.
- This is different from a word because you can combine morphemes to make words.
- You can understand certain words even if you've never heard them before.
- Syntax is generative, allowing us to understand sentences and phrases we never heard before.
- Words are also generative, and that morphemes can combine together to create words we've never heard before.

3) **Syntax**: What we have in language is a set of distinct symbols, words or phrases or categories that words and phrases belong to, and rules that order these symbols, and then other rules that call upon these rules giving rise to the possibility of infinite production of symbol strings, what's called a recursion.

> Infinite use of finite media. by Wilhelm von Humboldt

## Language acquisition

Norm Chomsky is probably the best known linguists in the world. He is strongly identified to **nativism**. What it means for a psychologist or philosopher, is the idea that **we're born with a lot of knowledge** (innate). Chomsky has argued this particularly in the domain of language.

- we should see the development of language not so much as learning, but as growth

> "No one would take seriously the proposal that the human organism learns through experience to have arms rather than wings, or that the basic structure of particular organs results from accidental experience. [Language] proves to be no less marvelous and intricate than these physical structures.. Why, then, should we not study the acquisition of a cognitive structure like language more or less as we study some complex bodily organ?"

Now, I have some sympathy for this view and I want to, later on, present some evidence that language does seem to show certain patterns that hint at universality. Hint that in some way we can see language as akin to a bodily organ and different from a product of culture like baseball games or British history. But at the same time, it's clear that language development does involve learning, that is, it's impossible to explain how we come to know language without accepting that we attend to what others around us do and do as they do and pick up the way they speak. This has to be the case, because language is different. So, consider an example from each of our three domains. In English, there's a phonetic distinction between L and R. So, I'm giving you the letters, but it's really the sounds associated with them. We know this because words can differ in meaning, depending on which phoneme is used. There's a different in lip, which is a part of the mouth versus rip. Which means to tear up something. The other languages don't make this distinction. Part of what it is to come to know a language has come to learn their phonetic properties language. Another thing is part of what is to know a language is to learn the meanings of words, morphology.  

Finally, there's syntax. So, in English, if you wanted to say that Bill hit John, that Bill was to hitter and John was hit, you'd say in this order, Bill hit John. If all you knew was English you would think this is inevitable, how else would you do it? But in fact, other languages just do it differently. Some languages would say, Bill hit John, by saying, Bill John hit, or even John hit Bill, where the phrases are in different order to capture the same meaning. 

All of this phenology, morphology and syntax has to be learned. But, as Chomsky points out, if it is learning is learning of a fundamentally different character than other forms of learning.

For one thing as mentioned before, everybody learns language, it's a universal part of development, all normal children come to have it and this is true in every human society. More interestingly, there are specific impairments of language. So, things can happen to you as an adult, like brain damage, or trauma, or stroke, or as a child as an a developmental disorder, or a genetic disorder, that could leave you bereft of language. It could leave you unable to speak or understand. This is relevant because many people believe that all that you need to learn language is, for instance, to be very smart, or to want to communicate. But plainly, that can't be true, because there are people who are walking around who are very smart and desperately want to communicate and they can't learn language. This supports the idea, that language is to some degree special, it is not reducible to other human capacities. Also, on the theme of learning, language is learned, but it's not learned in through feedback or specific training. There are many people who believe that if you don't really teach your kid to talk, your kid won't talk. Just as in other societies, people would believe that if you don't teach your kid to stand up or walk, he'll never walk. There are some societies, for instance, where they pile up sand under the kids butt so they could gradually gets more and more upright until he's walking. Anything if you didn't do that he never learned to walk. We look at that and say that's silly, you don't need it, kids learn to walk on their own. But, those societies would look at our society with this obsession with flashcards, and drills, and learning how to calibrate your speech to the kid, and tremendous focus on what you say to a kid to make them learn to speak, and they'd say that's silly, you don't need to do that. They're right, cross-cultural leads to great differences in how we speak to our children, or whether we speak to our young children and all. 

This seem to have little or no effect on whether or not kids talk, all kids talk regardless. Now, it's also true that in Western societies people give feedback to their children. So, often you'll correct your child if he says something. Some people have speculated along lines of behaviorism, that this feedback perhaps as a reward and punishment, shapes the child's learning. 

But, we now know that this isn't true. For one thing, you don't need it. Again, even in Western societies some parents don't reinforce and punish their kids for what they say and yet kids nonetheless learn to talk. Moreover, even the parents who do give their kids reinforcement and punishment don't tend to do it for the phenology, or the morphology, or the grammar, but more for the appropriateness or cuteness of what kids say. So, we correct kids if they get their facts wrong. We don't typically correct them if they get their grammar wrong. Children learn language by absorbing the language around them, that much has to be true. But, it doesn't seem as if any teaching, certainly any reinforcement or punishment plays a critical role. 

So, what do we know about language development? Well, what I'll do now is, I'll just kind of walk through this stages without saying much about the psychological mechanisms that drive kids from one stage to another, but provide you with descriptive overview what happens. So, the child's born and when a child is born, he or she likes listening to his or her own language. There's all sorts of clever studies that explored this. 

What's particularly cool is very early on, children can discriminate all the Phonemes of natural language. I said before there are many many phonemes in English and every other languages just chooses a subset of them. But kids are sensitive to them from the very start your average, your kid born in America to English-speaking parents can distinguish between bar and par, which are English distinctions, but also can make distinctions between Phonemes in Czech and Hindi, which are not expressed in English. 

What's really cool is, this capacity goes away. So, this is one way in which kids are better than adults. It's that there are not many examples of this, but this is one example. A baby can make distinctions, can hear distinctions that you can't. This capacity you start off oversensitive and then we whittled down our sensitivity until we're just understanding the distinctions made in their own language. 

Around age seven months starts babbling, kids go Ba-Ba-Ba Pa-Pa-Pa, make sounds like that. Fascinatingly, deaf children learning sign language also babble, they babble with their hands producing the equivalent of Ba-Ba-Ba Pa-Pa-Pa. 

At around the kids first birthday, and there's quite a lot of variance for this, parents shouldn't panic if kids take longer than 12 months, but you know you get the first words, mama, dada, typically words for objects, actions, properties, milk, give, up, hot, words like that. Early on using clever methods, it turns out that there are some sensitivity to word order. 

So, for instance, you could put a **one-year-old** down, even a one-year-old who isn't yet producing sentences, and put the kid down and there's two screens. On one screen, first, you find out the kid can recognize big burden Cookie Monster Sesame Street characters, if not you could use other characters. Then you have two screens, in one screen, big bird is pushing Cookie Monster, in the other screen, Cookie Monster's pushing big bird, and you say to the kids something like, look big birds pushing Cookie Monster and you'll see where the kid looks. Very early on, you find that the kid looks in an appropriate direction, in a screen that matches the English sentence expressing that action, showing that very early on you have some understanding of word order. 

Around 18 months, the kid starts to increase the rate of learning words, produces two word sentences, what's called a telegraphic speech. There aren't telegrams anymore, but telegrams used to be ways to communicate where each word you used was very expensive, so you had to kind of put things together, you wouldn't say, "Oh, I'm traveling through Spain and I've lost my wallet please send me money right now", you'd say, "Spain-lost-wallet-need-money." That's how kids talk early on, as if words are very expensive. Then, gradually at this point, function morphemes, we talked about them before like, in, of, a, the plural marker 's', the past tense marker 'ed', gradually begin to appear. 

Language continues to develop, then at some certain point, it becomes more difficult to learn a language and people are rarely fully successful. This is true both for second languages and also studies of deaf children learning sign language for first languages. For instance, some really interesting studies to illustrate this looked at people and these were all people who have been in America for about 30 years, so they've learned a language as well as their aboriginal learn it. The comparison was, when did they start? Did they start as babies? Did they start as young children? Did they start as adolescents? Did they start after the age of 17? what you can see in this graph is, that the older you start, past about age three, the less good you are. So, if you start learning English at age three you're fine, but if you start learning English at age 10, at age 15, or age 20, even if you were to speak it for 30 years, you still will not be perfectly fluent. This suggests that, the biological capacity to learn language has a clock on it. Like other capacities psychologists have studied, there's a critical period you have to do it within a certain period of development, or you'll never be fully successful.

## Language and thought

- Language in the brain
- Neurological and cognitive nature of language disorders
- Reading
- Bilingual and multilingualism

Other language topics:

- Communication in other species: do other animals process the same type of languages? People have vast different views on this.
    - a finite list of calls
    - a continuous analog signal, e.g. bees
    - random variations on a theme, e.g. birds

    No: phonology, morphology, syntax

- What about primates trained by humans?
    - Few words
    - Very slow learning
    - Limited ordering

Language processing

Language and thought: 

- does the language you learn change the way you think?
- is language necessary for abstract thought?
