# Happiness

# Humility and Optimism

We have a review of psychology, some more in-depth than others. 

- memory
- language
- child development
- how the brain works
- why people are different and have different personalities
- the social influences on our lives
- what makes us afraid
- what leads to different forms of mental illness
- what factors influence our happiness

**Humility**

There are some very basic questions about the mind that nobody knows the answer to yet. 

- We know that the brain is the source of mental life, but we don't have any real understanding of how a physical object, a lump of meat, can give rise to conscious experience. We haven't yet solved what philosophers call, the hard problem.
- We know that about half the variation in personality is a result of genes, and so too for intelligence and happiness, and many other things, but we don't really know how to explain where the other half comes from, what experiences make us what we are.
- We know about the social influences that can make us do certain things, including bad things, but we don't yet know why some people are immune to these influences, and act and sometimes do great and heroic things, regardless of the circumstances that they find themselves in.

**Optimism**

The most important and intimate aspects of ourselves, our beliefs and emotions, the capacity to make decisions, our sense of right and wrong, can be explained through constructing and testing scientific hypotheses.
